// manager/frontend-vue-backup/src/components/common/AgentForm.vue
<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { useLocale } from '../../composables/useLocale'
import { buildAgentPayload, useAgentFormOptions } from '../../composables/useAgentFormOptions'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Switch } from '@/components/ui/switch'
import { Select, SelectTrigger, SelectContent, SelectItem, SelectValue } from '@/components/ui/select'

const { t } = useLocale()

const props = defineProps({
  modelValue: { type: Object, required: true },
  isAdmin: { type: Boolean, default: false },
  mode: { type: String, default: 'create' },
  labelPosition: { type: String, default: 'top' },
  labelWidth: { type: String, default: '120px' }
})

const emit = defineEmits(['update:modelValue'])

const form = computed({
  get: () => props.modelValue,
  set: (v) => emit('update:modelValue', v)
})

const targetUserId = computed(() => props.isAdmin ? Number(form.value.user_id || 0) : 0)

const {
  users, llmConfigs, ttsConfigs, knowledgeBases, mcpServiceOptions,
  voiceOptions, cloneVoices, loading,
  loadUsers, loadConfigs, loadKnowledgeBases, loadMcpServiceOptions,
  loadVoiceOptions, loadCloneVoices
} = useAgentFormOptions({ isAdmin: computed(() => props.isAdmin), targetUserId })

// ── Voice handling ──────────────────────────────────────────────────────────
const MAX_VISIBLE_VOICE_OPTIONS = 300
const voiceSearchKeyword = ref('')
const filteredVoiceOptions = ref([])
const previousTtsConfigId = ref(null)
const suppressTtsConfigWatch = ref(false)

const selectedTtsConfig = computed(() => ttsConfigs.value.find((c) => c.config_id === form.value.tts_config_id) || null)

const limitVoiceOptions = (voices) => {
  const list = Array.isArray(voices) ? voices : []
  const visible = list.slice(0, MAX_VISIBLE_VOICE_OPTIONS)
  const selected = String(form.value.voice || '').trim()
  if (selected && !visible.some((v) => v.value === selected)) {
    const opt = list.find((v) => v.value === selected)
    if (opt) visible.unshift(opt)
  }
  return visible
}

const syncFilteredVoiceOptions = () => {
  const keyword = String(voiceSearchKeyword.value || '').trim().toLowerCase()
  if (!keyword) { filteredVoiceOptions.value = limitVoiceOptions(voiceOptions.value); return }
  const matched = voiceOptions.value.filter((v) => {
    return String(v.label || '').toLowerCase().includes(keyword) || String(v.value || '').toLowerCase().includes(keyword)
  })
  filteredVoiceOptions.value = limitVoiceOptions(matched)
}

const refreshVoiceOptions = async ({ clearInvalid = true, previousConfigId = previousTtsConfigId.value } = {}) => {
  const provider = selectedTtsConfig.value?.provider
  if (!form.value.tts_config_id || !provider) {
    voiceOptions.value = []; filteredVoiceOptions.value = []; form.value.voice = null; previousTtsConfigId.value = null; return
  }
  const previousConfig = ttsConfigs.value.find((c) => c.config_id === previousConfigId)
  if (clearInvalid && previousConfig?.provider && previousConfig.provider !== provider) form.value.voice = null
  const voices = await loadVoiceOptions({ provider, configId: form.value.tts_config_id }).catch(() => [])
  await loadCloneVoices(form.value.tts_config_id).catch(() => [])
  if (clearInvalid && form.value.voice && voices.length) {
    if (!voices.some((v) => v.value === form.value.voice)) form.value.voice = null
  }
  syncFilteredVoiceOptions()
  previousTtsConfigId.value = form.value.tts_config_id
}

const setTtsConfig = async (configId, options = {}) => {
  const previousConfigId = form.value.tts_config_id
  suppressTtsConfigWatch.value = true
  form.value.tts_config_id = configId || null
  try {
    await refreshVoiceOptions({ clearInvalid: true, previousConfigId, ...options })
  } finally {
    Promise.resolve().then(() => { suppressTtsConfigWatch.value = false })
  }
}

const applyCloneVoice = async (clone) => {
  if (!clone?.tts_config_id || !clone?.provider_voice_id) return
  await setTtsConfig(clone.tts_config_id, { clearInvalid: false })
  form.value.voice = clone.provider_voice_id
}

// ── MCP services multi-select ───────────────────────────────────────────────
const selectedMcpServices = computed({
  get: () => String(form.value.mcp_service_names || '').split(',').map((i) => i.trim()).filter(Boolean),
  set: (items) => { form.value.mcp_service_names = Array.isArray(items) ? items.join(',') : '' }
})

const toggleMcpService = (svc) => {
  const curr = selectedMcpServices.value
  selectedMcpServices.value = curr.includes(svc) ? curr.filter((s) => s !== svc) : [...curr, svc]
}

// ── OpenClaw keyword tags ───────────────────────────────────────────────────
const newEnterKeyword = ref('')
const newExitKeyword = ref('')

const addEnterKeyword = () => {
  const kw = newEnterKeyword.value.trim()
  if (kw && !(form.value.openclaw_enter_keywords || []).includes(kw)) {
    form.value.openclaw_enter_keywords = [...(form.value.openclaw_enter_keywords || []), kw]
  }
  newEnterKeyword.value = ''
}
const removeEnterKeyword = (kw) => {
  form.value.openclaw_enter_keywords = (form.value.openclaw_enter_keywords || []).filter((k) => k !== kw)
}
const addExitKeyword = () => {
  const kw = newExitKeyword.value.trim()
  if (kw && !(form.value.openclaw_exit_keywords || []).includes(kw)) {
    form.value.openclaw_exit_keywords = [...(form.value.openclaw_exit_keywords || []), kw]
  }
  newExitKeyword.value = ''
}
const removeExitKeyword = (kw) => {
  form.value.openclaw_exit_keywords = (form.value.openclaw_exit_keywords || []).filter((k) => k !== kw)
}

// ── Lifecycle ───────────────────────────────────────────────────────────────
const userLabel = (user) => {
  const name = user?.username || user?.name || t('user_id_fallback', { id: user?.id })
  return `${name} (ID: ${user?.id})`
}

const loadTargetUserOptions = async () => {
  await Promise.all([
    loadKnowledgeBases().catch(() => []),
    loadCloneVoices(form.value.tts_config_id || '').catch(() => [])
  ])
  const validKbIds = new Set(knowledgeBases.value.map((i) => Number(i.id)))
  if (validKbIds.size) {
    form.value.knowledge_base_ids = (form.value.knowledge_base_ids || []).filter((id) => validKbIds.has(Number(id)))
  } else if (props.isAdmin && targetUserId.value) {
    form.value.knowledge_base_ids = []
  }
}

const applyDefaultConfigs = () => {
  if (props.mode !== 'create') return
  if (!form.value.llm_config_id) {
    const d = llmConfigs.value.find((c) => c.is_default)
    if (d) form.value.llm_config_id = d.config_id
  }
  if (!form.value.tts_config_id) {
    const d = ttsConfigs.value.find((c) => c.is_default)
    if (d) form.value.tts_config_id = d.config_id
  }
}

const reloadOptions = async () => {
  await Promise.all([
    props.isAdmin ? loadUsers().catch(() => []) : Promise.resolve([]),
    loadConfigs(),
    loadMcpServiceOptions().catch(() => [])
  ])
  applyDefaultConfigs()
  await loadTargetUserOptions()
  await refreshVoiceOptions({ clearInvalid: false })
}

watch(() => form.value.user_id, async (next, prev) => {
  if (!props.isAdmin || next === prev) return
  form.value.knowledge_base_ids = []; form.value.voice = null; previousTtsConfigId.value = null
  await loadTargetUserOptions()
  await refreshVoiceOptions({ clearInvalid: true })
})

watch(() => form.value.tts_config_id, async (next, prev) => {
  if (next === prev || suppressTtsConfigWatch.value) return
  await refreshVoiceOptions({ clearInvalid: true, previousConfigId: prev })
})

onMounted(() => reloadOptions())

// ── Exposed API ─────────────────────────────────────────────────────────────
const validate = () => {
  if (props.isAdmin && !form.value.user_id) {
    ElMessage.error(t('select_owner_user')); return Promise.reject(new Error('validation'))
  }
  if (!String(form.value.name || '').trim()) {
    ElMessage.error(t('enter_agent_name')); return Promise.reject(new Error('validation'))
  }
  if (!String(form.value.nickname || '').trim()) {
    ElMessage.error(t('enter_agent_nickname')); return Promise.reject(new Error('validation'))
  }
  return Promise.resolve(true)
}
const resetFields = () => {}
const clearValidate = () => {}
const buildPayload = () => buildAgentPayload(form.value, { isAdmin: props.isAdmin })
const hasLlmConfig = (id) => !id || llmConfigs.value.some((c) => c.config_id === id)
const hasTtsConfig = (id) => !id || ttsConfigs.value.some((c) => c.config_id === id)

defineExpose({ validate, resetFields, clearValidate, reloadOptions, refreshVoiceOptions, setTtsConfig, buildPayload, hasLlmConfig, hasTtsConfig })
</script>

<template>
  <div class="grid gap-4">
    <!-- Owner user (admin) -->
    <div v-if="isAdmin" class="grid gap-1.5">
      <label class="text-sm font-medium text-[var(--color-text)]">{{ t('owner_user') }}</label>
      <Select v-model="form.user_id">
        <SelectTrigger class="w-full"><SelectValue :placeholder="t('select_owner_user')" /></SelectTrigger>
        <SelectContent>
          <SelectItem v-for="user in users" :key="user.id" :value="user.id">{{ userLabel(user) }}</SelectItem>
        </SelectContent>
      </Select>
    </div>

    <!-- Name + Nickname -->
    <div class="grid grid-cols-2 gap-4">
      <div class="grid gap-1.5">
        <label class="text-sm font-medium text-[var(--color-text)]">{{ t('agent_name') }}</label>
        <Input v-model="form.name" :placeholder="t('enter_admin_display_name')" maxlength="50" />
      </div>
      <div class="grid gap-1.5">
        <label class="text-sm font-medium text-[var(--color-text)]">{{ t('agent_nickname') }}</label>
        <Input v-model="form.nickname" :placeholder="t('model_display_name_hint')" maxlength="50" />
      </div>
    </div>

    <!-- Custom prompt -->
    <div class="grid gap-1.5">
      <label class="text-sm font-medium text-[var(--color-text)]">{{ t('role_description') }}</label>
      <Textarea v-model="form.custom_prompt" :placeholder="t('enter_role_prompt')" rows="4" maxlength="10000" />
    </div>

    <!-- Knowledge bases (multi-select checkboxes) -->
    <div class="grid gap-1.5">
      <label class="text-sm font-medium text-[var(--color-text)]">{{ t('link_knowledge_base') }}</label>
      <div :class="['border border-[var(--color-line)] rounded-lg max-h-32 overflow-y-auto p-1.5', (isAdmin && !form.user_id) && 'opacity-50 pointer-events-none']">
        <div v-if="!knowledgeBases.length" class="text-xs text-[var(--color-text-tertiary)] p-2 text-center">{{ t('select_linked_knowledge_base') }}</div>
        <label v-for="kb in knowledgeBases" :key="kb.id" class="flex items-center gap-2 p-1.5 rounded hover:bg-[var(--color-surface-muted)] cursor-pointer text-sm">
          <input type="checkbox" :value="kb.id" v-model="form.knowledge_base_ids" class="accent-[var(--color-primary)]" />
          <span>{{ kb.name || t('kb_default_label', { id: kb.id }) }}</span>
        </label>
      </div>
    </div>

    <!-- LLM + TTS configs -->
    <div class="grid grid-cols-2 gap-4">
      <div class="grid gap-1.5">
        <label class="text-sm font-medium text-[var(--color-text)]">{{ t('language_model') }}</label>
        <Select v-model="form.llm_config_id">
          <SelectTrigger class="w-full"><SelectValue :placeholder="t('select_language_model')" /></SelectTrigger>
          <SelectContent>
            <SelectItem v-for="cfg in llmConfigs" :key="cfg.config_id" :value="cfg.config_id">
              {{ cfg.is_default ? t('tts_default_label', { name: cfg.name }) : cfg.name }}
            </SelectItem>
          </SelectContent>
        </Select>
      </div>
      <div class="grid gap-1.5">
        <label class="text-sm font-medium text-[var(--color-text)]">{{ t('tts_config_label') }}</label>
        <Select v-model="form.tts_config_id">
          <SelectTrigger class="w-full"><SelectValue :placeholder="t('select_tts_config')" /></SelectTrigger>
          <SelectContent>
            <SelectItem v-for="cfg in ttsConfigs" :key="cfg.config_id" :value="cfg.config_id">
              {{ cfg.is_default ? t('tts_default_label', { name: cfg.name }) : cfg.name }}
            </SelectItem>
          </SelectContent>
        </Select>
      </div>
    </div>

    <!-- Voice (allow-create datalist) -->
    <div v-if="form.tts_config_id" class="grid gap-1.5">
      <label class="text-sm font-medium text-[var(--color-text)]">{{ t('tts_voice') }}</label>
      <Input v-model="form.voice" list="agent-form-voice-datalist" :placeholder="t('select_or_enter_timbre')" />
      <datalist id="agent-form-voice-datalist">
        <option v-for="v in filteredVoiceOptions" :key="v.value" :value="v.value">{{ v.label || v.value }}</option>
      </datalist>
    </div>

    <!-- Clone voice presets -->
    <div v-if="cloneVoices.length" :class="['flex flex-wrap gap-1.5 -mt-2', loading.cloneVoices && 'opacity-50']">
      <button
        v-for="clone in cloneVoices"
        :key="clone.id"
        type="button"
        :class="['inline-flex items-center px-2.5 py-1 rounded-lg text-xs border transition-colors cursor-pointer',
          form.tts_config_id === clone.tts_config_id && form.voice === clone.provider_voice_id
            ? 'border-[var(--color-primary)] bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400'
            : 'border-[var(--color-line)] text-[var(--color-text-secondary)] hover:border-[var(--color-primary)]']"
        :title="`${clone.tts_config_name || clone.tts_config_id} · ${clone.provider_voice_id}`"
        @click="applyCloneVoice(clone)"
      >{{ clone.name || clone.provider_voice_id }}</button>
    </div>

    <!-- ASR speed + Memory mode + Speaker chat mode -->
    <div class="grid grid-cols-3 gap-4">
      <div class="grid gap-1.5">
        <label class="text-sm font-medium text-[var(--color-text)]">{{ t('asr_speed') }}</label>
        <Select v-model="form.asr_speed">
          <SelectTrigger class="w-full"><SelectValue /></SelectTrigger>
          <SelectContent>
            <SelectItem value="normal">{{ t('normal') }}</SelectItem>
            <SelectItem value="patient">{{ t('patience') }}</SelectItem>
            <SelectItem value="fast">{{ t('fast') }}</SelectItem>
          </SelectContent>
        </Select>
      </div>
      <div class="grid gap-1.5">
        <label class="text-sm font-medium text-[var(--color-text)]">{{ t('memory_mode') }}</label>
        <Select v-model="form.memory_mode">
          <SelectTrigger class="w-full"><SelectValue /></SelectTrigger>
          <SelectContent>
            <SelectItem value="none">{{ t('no_memory') }}</SelectItem>
            <SelectItem value="short">{{ t('short_memory') }}</SelectItem>
            <SelectItem value="long">{{ t('long_memory') }}</SelectItem>
          </SelectContent>
        </Select>
      </div>
      <div class="grid gap-1.5">
        <label class="text-sm font-medium text-[var(--color-text)]">{{ t('voiceprint_chat_limit') }}</label>
        <Select v-model="form.speaker_chat_mode">
          <SelectTrigger class="w-full"><SelectValue /></SelectTrigger>
          <SelectContent>
            <SelectItem value="off">{{ t('close') }}</SelectItem>
            <SelectItem value="identified_only">{{ t('voiceprint_only_chat') }}</SelectItem>
          </SelectContent>
        </Select>
      </div>
    </div>

    <!-- MCP services multi-select -->
    <div class="grid gap-1.5">
      <label class="text-sm font-medium text-[var(--color-text)]">{{ t('mcp_service') }}</label>
      <div class="border border-[var(--color-line)] rounded-lg max-h-32 overflow-y-auto p-1.5">
        <div v-if="!mcpServiceOptions.length" class="text-xs text-[var(--color-text-tertiary)] p-2 text-center">{{ t('leave_blank_all_enabled') }}</div>
        <label v-for="svc in mcpServiceOptions" :key="svc" class="flex items-center gap-2 p-1.5 rounded hover:bg-[var(--color-surface-muted)] cursor-pointer text-sm">
          <input type="checkbox" :checked="selectedMcpServices.includes(svc)" @change="toggleMcpService(svc)" class="accent-[var(--color-primary)]" />
          <span>{{ svc }}</span>
        </label>
      </div>
    </div>

    <!-- OpenClaw panel -->
    <div class="border border-[var(--color-line)] rounded-xl p-4 bg-[var(--color-surface-muted)] grid gap-3">
      <div class="flex items-center justify-between gap-3">
        <span class="text-sm font-semibold text-[var(--color-text)]">{{ t('allow_openclaw_mode') }}</span>
        <Switch :model-value="!!form.openclaw_allowed" @update:model-value="(v) => form.openclaw_allowed = v" />
      </div>
      <div class="grid grid-cols-2 gap-4">
        <!-- Enter keywords -->
        <div class="grid gap-1.5">
          <label class="text-xs font-medium text-[var(--color-text-secondary)]">{{ t('openclaw_enter_keyword') }}</label>
          <div class="flex flex-wrap gap-1 min-h-[28px]">
            <span v-for="kw in (form.openclaw_enter_keywords || [])" :key="kw" class="inline-flex items-center gap-0.5 px-2 py-0.5 rounded-full text-xs bg-blue-50 text-blue-700 border border-blue-200 dark:bg-blue-900/30 dark:text-blue-400 dark:border-blue-800">
              {{ kw }}<button type="button" class="hover:opacity-70 ml-0.5" @click="removeEnterKeyword(kw)">×</button>
            </span>
          </div>
          <Input v-model="newEnterKeyword" class="h-7 text-xs" :placeholder="t('enter_press_add_keywords')" @keydown.enter.prevent="addEnterKeyword" />
        </div>
        <!-- Exit keywords -->
        <div class="grid gap-1.5">
          <label class="text-xs font-medium text-[var(--color-text-secondary)]">{{ t('openclaw_exit_keyword') }}</label>
          <div class="flex flex-wrap gap-1 min-h-[28px]">
            <span v-for="kw in (form.openclaw_exit_keywords || [])" :key="kw" class="inline-flex items-center gap-0.5 px-2 py-0.5 rounded-full text-xs bg-blue-50 text-blue-700 border border-blue-200 dark:bg-blue-900/30 dark:text-blue-400 dark:border-blue-800">
              {{ kw }}<button type="button" class="hover:opacity-70 ml-0.5" @click="removeExitKeyword(kw)">×</button>
            </span>
          </div>
          <Input v-model="newExitKeyword" class="h-7 text-xs" :placeholder="t('enter_press_add_keywords')" @keydown.enter.prevent="addExitKeyword" />
        </div>
      </div>
    </div>
  </div>
</template>

// manager/frontend/src/components/agents/agent-form.tsx
import { forwardRef, useEffect, useImperativeHandle, useRef } from 'react'
import { toast } from 'sonner'
import { useAgentFormOptions } from '@/hooks/use-agent-form-options'
import type { AgentFormData, LLMConfig, TTSConfig } from '@/features/agents/types'
import { buildAgentPayload } from '@/features/agents/types'
import { useLocale } from '@/hooks/use-locale'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Switch } from '@/components/ui/switch'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'

export interface AgentFormHandle {
  validate: () => Promise<boolean>
  buildPayload: () => Record<string, unknown>
  reloadOptions: () => Promise<void>
}

interface Props {
  value: AgentFormData
  onChange: (data: AgentFormData) => void
  isAdmin?: boolean
  mode?: 'create' | 'edit'
}

const Field = ({ label, children }: { label: string; children: React.ReactNode }) => (
  <div className="grid gap-1.5">
    <label className="text-sm font-medium text-[var(--color-text)]">{label}</label>
    {children}
  </div>
)

export const AgentForm = forwardRef<AgentFormHandle, Props>(({ value, onChange, isAdmin = false, mode = 'create' }, ref) => {
  const { t } = useLocale()
  const opts = useAgentFormOptions()
  const ttsRef = useRef<string | null>(value.tts_config_id)

  const set = (patch: Partial<AgentFormData>) => onChange({ ...value, ...patch })

  const getProvider = (cfgs: TTSConfig[], id: string | null) => cfgs.find((c) => c.config_id === id)?.provider ?? ''

  const handleTtsChange = async (newId: string | null) => {
    const prev = ttsRef.current
    ttsRef.current = newId
    set({ tts_config_id: newId, voice: null })
    const provider = getProvider(opts.ttsConfigs, newId)
    if (newId && provider) {
      const voices = await opts.refreshVoices({ ttsConfigId: newId, provider, clearInvalid: true, previousConfigId: prev })
      if (mode === 'create' && !value.voice && voices.length) set({ tts_config_id: newId, voice: null })
    } else {
      await opts.refreshVoices({ ttsConfigId: null })
    }
  }

  const applyClone = async (clone: { tts_config_id: string; provider_voice_id: string }) => {
    if (clone.tts_config_id !== value.tts_config_id) await handleTtsChange(clone.tts_config_id)
    set({ voice: clone.provider_voice_id })
  }

  const toggleMcp = (svc: string) => {
    const curr = value.mcp_service_names.split(',').map((s) => s.trim()).filter(Boolean)
    const next = curr.includes(svc) ? curr.filter((s) => s !== svc) : [...curr, svc]
    set({ mcp_service_names: next.join(',') })
  }

  const addKeyword = (field: 'openclaw_enter_keywords' | 'openclaw_exit_keywords', kw: string) => {
    const trimmed = kw.trim()
    if (!trimmed || value[field].includes(trimmed)) return
    set({ [field]: [...value[field], trimmed] })
  }
  const removeKeyword = (field: 'openclaw_enter_keywords' | 'openclaw_exit_keywords', kw: string) => {
    set({ [field]: value[field].filter((k) => k !== kw) })
  }

  useEffect(() => {
    opts.load({ isAdmin, userId: isAdmin ? value.user_id : null, ttsConfigId: value.tts_config_id }).then(async () => {
      if (value.tts_config_id) {
        const provider = getProvider(opts.ttsConfigs, value.tts_config_id)
        if (provider) await opts.refreshVoices({ ttsConfigId: value.tts_config_id, provider, clearInvalid: false })
      }
      if (mode === 'create') {
        const patch: Partial<AgentFormData> = {}
        if (!value.llm_config_id) { const d = opts.llmConfigs.find((c: LLMConfig) => c.is_default); if (d) patch.llm_config_id = d.config_id }
        if (!value.tts_config_id) { const d = opts.ttsConfigs.find((c: TTSConfig) => c.is_default); if (d) patch.tts_config_id = d.config_id }
        if (Object.keys(patch).length) set(patch)
      }
    })
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  useImperativeHandle(ref, () => ({
    validate: async () => {
      if (isAdmin && !value.user_id) { toast.error(t('select_owner_user')); return false }
      if (!value.name.trim()) { toast.error(t('enter_agent_name')); return false }
      if (!value.nickname.trim()) { toast.error(t('enter_agent_nickname')); return false }
      return true
    },
    buildPayload: () => buildAgentPayload(value, { isAdmin }),
    reloadOptions: async () => opts.load({ isAdmin, userId: isAdmin ? value.user_id : null, ttsConfigId: value.tts_config_id }),
  }))

  const selectedMcpSet = new Set(value.mcp_service_names.split(',').map((s) => s.trim()).filter(Boolean))

  return (
    <div className="grid gap-4">
      {isAdmin && (
        <Field label={t('owner_user')}>
          <Select value={value.user_id ? String(value.user_id) : ''} onValueChange={(v) => set({ user_id: Number(v) || null })}>
            <SelectTrigger><SelectValue placeholder={t('select_owner_user')} /></SelectTrigger>
            <SelectContent>{opts.users.map((u) => <SelectItem key={u.id} value={String(u.id)}>{u.username || u.name} (ID: {u.id})</SelectItem>)}</SelectContent>
          </Select>
        </Field>
      )}
      <div className="grid grid-cols-2 gap-4">
        <Field label={t('agent_name')}><Input value={value.name} onChange={(e) => set({ name: e.target.value })} maxLength={50} placeholder={t('enter_admin_display_name')} /></Field>
        <Field label={t('agent_nickname')}><Input value={value.nickname} onChange={(e) => set({ nickname: e.target.value })} maxLength={50} placeholder={t('model_display_name_hint')} /></Field>
      </div>
      <Field label={t('role_description')}>
        <Textarea value={value.custom_prompt} onChange={(e) => set({ custom_prompt: e.target.value })} rows={4} maxLength={10000} placeholder={t('enter_role_prompt')} />
      </Field>
      <Field label={t('link_knowledge_base')}>
        <div className="border border-[var(--color-line)] rounded-lg max-h-32 overflow-y-auto p-1.5">
          {opts.knowledgeBases.length === 0 ? (
            <p className="text-xs text-[var(--color-text-tertiary)] p-2 text-center">{t('select_linked_knowledge_base')}</p>
          ) : opts.knowledgeBases.map((kb) => (
            <label key={kb.id} className="flex items-center gap-2 p-1.5 rounded hover:bg-[var(--color-surface-muted)] cursor-pointer text-sm">
              <input type="checkbox" checked={value.knowledge_base_ids.includes(kb.id)} onChange={(e) => set({ knowledge_base_ids: e.target.checked ? [...value.knowledge_base_ids, kb.id] : value.knowledge_base_ids.filter((id) => id !== kb.id) })} className="accent-[var(--color-primary)]" />
              <span>{kb.name}</span>
            </label>
          ))}
        </div>
      </Field>
      <div className="grid grid-cols-2 gap-4">
        <Field label={t('language_model')}>
          <Select value={value.llm_config_id ?? ''} onValueChange={(v) => set({ llm_config_id: v || null })}>
            <SelectTrigger><SelectValue placeholder={t('select_language_model')} /></SelectTrigger>
            <SelectContent>{opts.llmConfigs.map((c) => <SelectItem key={c.config_id} value={c.config_id}>{c.is_default ? t('tts_default_label', { name: c.name }) : c.name}</SelectItem>)}</SelectContent>
          </Select>
        </Field>
        <Field label={t('tts_config_label')}>
          <Select value={value.tts_config_id ?? ''} onValueChange={(v) => handleTtsChange(v || null)}>
            <SelectTrigger><SelectValue placeholder={t('select_tts_config')} /></SelectTrigger>
            <SelectContent>{opts.ttsConfigs.map((c) => <SelectItem key={c.config_id} value={c.config_id}>{c.is_default ? t('tts_default_label', { name: c.name }) : c.name}</SelectItem>)}</SelectContent>
          </Select>
        </Field>
      </div>
      {value.tts_config_id && (
        <Field label={t('tts_voice')}>
          <Input value={value.voice ?? ''} onChange={(e) => set({ voice: e.target.value || null })} list="agent-voice-list" placeholder={t('select_or_enter_timbre')} />
          <datalist id="agent-voice-list">{opts.filteredVoiceOptions.map((v) => <option key={v.value} value={v.value}>{v.label || v.value}</option>)}</datalist>
        </Field>
      )}
      {opts.cloneVoices.length > 0 && (
        <div className="flex flex-wrap gap-1.5 -mt-2">
          {opts.cloneVoices.map((clone) => (
            <button key={clone.id} type="button" onClick={() => applyClone(clone)}
              className={`inline-flex items-center px-2.5 py-1 rounded-lg text-xs border transition-colors cursor-pointer ${value.tts_config_id === clone.tts_config_id && value.voice === clone.provider_voice_id ? 'border-[var(--color-primary)] bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400' : 'border-[var(--color-line)] text-[var(--color-text-secondary)] hover:border-[var(--color-primary)]'}`}>
              {clone.name || clone.provider_voice_id}
            </button>
          ))}
        </div>
      )}
      <div className="grid grid-cols-3 gap-4">
        {([['asr_speed', [['normal', t('normal')], ['patient', t('patience')], ['fast', t('fast')]], t('asr_speed')],
          ['memory_mode', [['none', t('no_memory')], ['short', t('short_memory')], ['long', t('long_memory')]], t('memory_mode')],
          ['speaker_chat_mode', [['off', t('close')], ['identified_only', t('voiceprint_only_chat')]], t('voiceprint_chat_limit')],
        ] as [keyof AgentFormData, [string, string][], string][]).map(([field, opts2, label]) => (
          <Field key={field} label={label}>
            <Select value={String(value[field])} onValueChange={(v) => set({ [field]: v } as Partial<AgentFormData>)}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>{opts2.map(([val, lbl]) => <SelectItem key={val} value={val}>{lbl}</SelectItem>)}</SelectContent>
            </Select>
          </Field>
        ))}
      </div>
      <Field label={t('mcp_service')}>
        <div className="border border-[var(--color-line)] rounded-lg max-h-32 overflow-y-auto p-1.5">
          {opts.mcpServiceOptions.length === 0 ? (
            <p className="text-xs text-[var(--color-text-tertiary)] p-2 text-center">{t('leave_blank_all_enabled')}</p>
          ) : opts.mcpServiceOptions.map((svc) => (
            <label key={svc} className="flex items-center gap-2 p-1.5 rounded hover:bg-[var(--color-surface-muted)] cursor-pointer text-sm">
              <input type="checkbox" checked={selectedMcpSet.has(svc)} onChange={() => toggleMcp(svc)} className="accent-[var(--color-primary)]" />
              <span>{svc}</span>
            </label>
          ))}
        </div>
      </Field>
      <div className="border border-[var(--color-line)] rounded-xl p-4 bg-[var(--color-surface-2)] grid gap-3">
        <div className="flex items-center justify-between gap-3">
          <span className="text-sm font-semibold text-[var(--color-text)]">{t('allow_openclaw_mode')}</span>
          <Switch checked={!!value.openclaw_allowed} onCheckedChange={(v) => set({ openclaw_allowed: v })} />
        </div>
        <div className="grid grid-cols-2 gap-4">
          {(['openclaw_enter_keywords', 'openclaw_exit_keywords'] as const).map((field) => (
            <div key={field} className="grid gap-1.5">
              <label className="text-xs font-medium text-[var(--color-text-secondary)]">{field === 'openclaw_enter_keywords' ? t('openclaw_enter_keyword') : t('openclaw_exit_keyword')}</label>
              <div className="flex flex-wrap gap-1 min-h-[28px]">
                {value[field].map((kw) => (
                  <span key={kw} className="inline-flex items-center gap-0.5 px-2 py-0.5 rounded-full text-xs bg-blue-50 text-blue-700 border border-blue-200 dark:bg-blue-900/30 dark:text-blue-400 dark:border-blue-800">
                    {kw}<button type="button" className="hover:opacity-70 ml-0.5" onClick={() => removeKeyword(field, kw)}>×</button>
                  </span>
                ))}
              </div>
              <Input className="h-7 text-xs" placeholder={t('enter_press_add_keywords')}
                onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); addKeyword(field, (e.target as HTMLInputElement).value); (e.target as HTMLInputElement).value = '' } }} />
            </div>
          ))}
        </div>
      </div>
    </div>
  )
})

AgentForm.displayName = 'AgentForm'
