// manager/frontend/src/components/user/SpeakerGroupDialog.vue
<template>
  <el-dialog
    v-model="visible"
    :title="mode === 'add' ? t('create_voiceprint_group') : t('edit_voiceprint_group')"
    width="600px"
  >
    <el-form ref="formRef" :model="groupForm" :rules="groupRules" label-width="100px">
      <el-form-item :label="t('link_agent')" prop="agent_id">
        <el-select v-model="groupForm.agent_id" :placeholder="t('select_agent')" style="width: 100%">
          <el-option v-for="agent in agents" :key="agent.id" :label="agent.name" :value="agent.id" />
        </el-select>
      </el-form-item>
      <el-form-item :label="t('voiceprint_name')" prop="name">
        <el-input v-model="groupForm.name" :placeholder="t('enter_voiceprint_name')" :maxlength="100" show-word-limit />
      </el-form-item>
      <el-form-item label="Prompt" prop="prompt">
        <el-input v-model="groupForm.prompt" type="textarea" :rows="4" :placeholder="t('role_prompt_ph')" />
      </el-form-item>
      <el-form-item :label="t('description')" prop="description">
        <el-input v-model="groupForm.description" type="textarea" :rows="3" :placeholder="t('desc_optional_ph')" :maxlength="200" show-word-limit />
      </el-form-item>
      <el-form-item :label="t('my_cloned_voice')" v-if="cloneVoicePresets.length > 0">
        <div class="clone-voice-line" v-loading="cloneVoicesLoading">
          <button
            v-for="clone in cloneVoicePresets"
            :key="clone.id"
            type="button"
            class="clone-voice-item"
            :class="{ active: isCloneVoiceSelected(clone) }"
            :title="`${clone.tts_config_name || clone.tts_config_id} · ${clone.provider_voice_id}`"
            @click="emit('apply-clone-voice', clone)"
          >
            <span class="clone-voice-name">{{ clone.name || clone.provider_voice_id }}</span>
          </button>
        </div>
        <div class="form-help">{{ t('click_auto_fill') }}</div>
      </el-form-item>
      <el-form-item :label="t('tts_config_label')" prop="tts_config_id">
        <el-select
          v-model="groupForm.tts_config_id"
          :placeholder="t('select_tts_config_opt')"
          clearable
          style="width: 100%"
          @change="(v) => emit('tts-config-change', v)"
        >
          <el-option
            v-for="ttsConfig in ttsConfigs"
            :key="ttsConfig.config_id"
            :label="ttsConfig.is_default ? t('tts_default_label', { name: ttsConfig.name }) : ttsConfig.name"
            :value="ttsConfig.config_id"
          >
            <div class="config-option">
              {{ ttsConfig.name }}
              <el-tag v-if="ttsConfig.is_default" type="success" size="small" style="margin-left: 8px;">{{ t('default') }}</el-tag>
            </div>
            <span class="config-desc">{{ ttsConfig.provider || t('no_description_alt') }}</span>
          </el-option>
        </el-select>
        <div class="form-help" v-if="groupForm.tts_config_id">{{ currentTtsConfigInfo }}</div>
      </el-form-item>
      <el-form-item :label="t('voice_timbre')" prop="voice" v-if="groupForm.tts_config_id">
        <el-select v-model="groupForm.voice" :placeholder="t('select_or_enter_voice')" filterable allow-create clearable style="width: 100%">
          <el-option v-for="voice in currentVoiceOptions" :key="voice.value" :label="voice.label" :value="voice.value" />
        </el-select>
        <div class="form-help">{{ t('current_tts_config_hint', { name: currentTtsConfigName }) }}</div>
      </el-form-item>
    </el-form>
    <template #footer>
      <el-button @click="visible = false">{{ t('cancel') }}</el-button>
      <el-button type="primary" @click="submit" :loading="submitting">
        {{ mode === 'add' ? t('create') : t('save') }}
      </el-button>
    </template>
  </el-dialog>
</template>

<script setup>
import { ref } from 'vue'
import { useLocale } from '../../composables/useLocale'

const { t } = useLocale()

const props = defineProps({
  mode: { type: String, default: 'add' },
  groupForm: { type: Object, required: true },
  groupRules: { type: Object, required: true },
  agents: { type: Array, default: () => [] },
  ttsConfigs: { type: Array, default: () => [] },
  currentVoiceOptions: { type: Array, default: () => [] },
  cloneVoicePresets: { type: Array, default: () => [] },
  cloneVoicesLoading: { type: Boolean, default: false },
  submitting: { type: Boolean, default: false },
  currentTtsConfigName: { type: String, default: '' },
  currentTtsConfigInfo: { type: String, default: '' },
  isCloneVoiceSelected: { type: Function, required: true }
})

const visible = defineModel({ default: false })
const emit = defineEmits(['submit', 'apply-clone-voice', 'tts-config-change'])

const formRef = ref()

// Expose formRef so parent can reset it
defineExpose({ formRef })

const submit = async () => {
  emit('submit', formRef)
}
</script>

<style scoped>
.clone-voice-line { display: flex; flex-wrap: wrap; gap: 6px; width: 100%; }
.clone-voice-item {
  display: inline-flex; align-items: center; max-width: 220px; min-width: 0;
  padding: 4px 10px; border: 1px solid #d1d5db; border-radius: 999px;
  background: #f8fafc; color: #374151; cursor: pointer; transition: all 0.2s ease;
  line-height: 1.2; outline: none;
}
.clone-voice-item:hover { border-color: #93c5fd; background: #f1f7ff; }
.clone-voice-item.active { border-color: #3b82f6; background: #e9f2ff; color: #1d4ed8; box-shadow: 0 0 0 1px rgba(59,130,246,0.1); }
.clone-voice-name { font-size: 12px; font-weight: 500; max-width: 100%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.form-help { color: #909399; font-size: 12px; margin-top: 4px; }
.config-option { display: flex; align-items: center; }
.config-desc { font-size: 12px; color: #909399; }
</style>

// manager/frontend/src/components/speakers/speaker-group-dialog.tsx
import { Loader2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { useLocale } from '@/hooks/use-locale'
import { cn } from '@/lib/utils'

interface Agent { id: number; name: string }
interface TtsConfig { config_id: string; name: string; is_default: boolean }
interface VoiceOption { value: string; label: string }
interface CloneVoicePreset { id: string; name?: string; provider_voice_id: string; tts_config_id: string; tts_config_name?: string }

export interface SpeakerGroupForm {
  agent_id: number | ''
  name: string
  prompt: string
  description: string
  tts_config_id: string
  voice: string
}

interface Props {
  open: boolean
  mode: 'add' | 'edit'
  form: SpeakerGroupForm
  onChange: (patch: Partial<SpeakerGroupForm>) => void
  onClose: () => void
  onSubmit: () => void
  agents: Agent[]
  ttsConfigs: TtsConfig[]
  currentVoiceOptions: VoiceOption[]
  cloneVoicePresets: CloneVoicePreset[]
  cloneVoicesLoading?: boolean
  submitting?: boolean
  currentTtsConfigName?: string
  currentTtsConfigInfo?: string
  isCloneVoiceSelected: (clone: CloneVoicePreset) => boolean
  onApplyCloneVoice: (clone: CloneVoicePreset) => void
  onTtsConfigChange: (id: string) => void
}

export function SpeakerGroupDialog({
  open, mode, form, onChange, onClose, onSubmit,
  agents, ttsConfigs, currentVoiceOptions, cloneVoicePresets,
  cloneVoicesLoading, submitting, currentTtsConfigName, currentTtsConfigInfo,
  isCloneVoiceSelected, onApplyCloneVoice, onTtsConfigChange,
}: Props) {
  const { t } = useLocale()

  return (
    <Dialog open={open} onOpenChange={(v) => { if (!v) onClose() }}>
      <DialogContent className="max-w-[580px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>
            {mode === 'add' ? t('create_voiceprint_group') : t('edit_voiceprint_group')}
          </DialogTitle>
        </DialogHeader>

        <div className="grid gap-4 py-2">
          {/* Agent */}
          <div className="grid gap-1.5">
            <label className="text-sm font-medium text-[var(--color-text)]">{t('link_agent')}</label>
            <Select value={form.agent_id ? String(form.agent_id) : ''} onValueChange={(v) => onChange({ agent_id: Number(v) })}>
              <SelectTrigger className="w-full"><SelectValue placeholder={t('select_agent')} /></SelectTrigger>
              <SelectContent>
                {agents.map((a) => <SelectItem key={a.id} value={String(a.id)}>{a.name}</SelectItem>)}
              </SelectContent>
            </Select>
          </div>

          {/* Name */}
          <div className="grid gap-1.5">
            <label className="text-sm font-medium text-[var(--color-text)]">{t('voiceprint_name')}</label>
            <Input value={form.name} onChange={(e) => onChange({ name: e.target.value })}
              placeholder={t('enter_voiceprint_name')} maxLength={100} />
          </div>

          {/* Prompt */}
          <div className="grid gap-1.5">
            <label className="text-sm font-medium text-[var(--color-text)]">Prompt</label>
            <Textarea value={form.prompt} onChange={(e) => onChange({ prompt: e.target.value })}
              placeholder={t('role_prompt_ph')} rows={4} />
          </div>

          {/* Description */}
          <div className="grid gap-1.5">
            <label className="text-sm font-medium text-[var(--color-text)]">{t('description')}</label>
            <Textarea value={form.description} onChange={(e) => onChange({ description: e.target.value })}
              placeholder={t('desc_optional_ph')} rows={3} maxLength={200} />
          </div>

          {/* Clone voice presets */}
          {cloneVoicePresets.length > 0 && (
            <div className="grid gap-1.5">
              <label className="text-sm font-medium text-[var(--color-text)]">{t('my_cloned_voice')}</label>
              <div className={cn('flex flex-wrap gap-1.5', cloneVoicesLoading && 'opacity-50')}>
                {cloneVoicePresets.map((clone) => (
                  <button key={clone.id} type="button"
                    title={`${clone.tts_config_name ?? clone.tts_config_id} · ${clone.provider_voice_id}`}
                    onClick={() => onApplyCloneVoice(clone)}
                    className={cn(
                      'inline-flex items-center px-3 py-1 rounded-full text-xs border transition-colors cursor-pointer',
                      isCloneVoiceSelected(clone)
                        ? 'status-primary'
                        : 'border-[var(--color-line)] bg-[var(--color-surface-1)] text-[var(--color-text-secondary)] hover:border-[var(--color-primary)]',
                    )}>
                    {clone.name ?? clone.provider_voice_id}
                  </button>
                ))}
              </div>
              <p className="text-xs text-[var(--color-text-tertiary)]">{t('click_auto_fill')}</p>
            </div>
          )}

          {/* TTS config */}
          <div className="grid gap-1.5">
            <label className="text-sm font-medium text-[var(--color-text)]">{t('tts_config_label')}</label>
            <Select value={form.tts_config_id} onValueChange={(v) => { onChange({ tts_config_id: v }); onTtsConfigChange(v) }}>
              <SelectTrigger className="w-full"><SelectValue placeholder={t('select_tts_config_opt')} /></SelectTrigger>
              <SelectContent>
                {ttsConfigs.map((cfg) => (
                  <SelectItem key={cfg.config_id} value={cfg.config_id}>
                    {cfg.is_default ? t('tts_default_label', { name: cfg.name }) : cfg.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {form.tts_config_id && currentTtsConfigInfo && (
              <p className="text-xs text-[var(--color-text-tertiary)]">{currentTtsConfigInfo}</p>
            )}
          </div>

          {/* Voice (datalist) */}
          {form.tts_config_id && (
            <div className="grid gap-1.5">
              <label className="text-sm font-medium text-[var(--color-text)]">{t('voice_timbre')}</label>
              <Input value={form.voice} onChange={(e) => onChange({ voice: e.target.value })}
                list="speaker-group-voice-datalist" placeholder={t('select_or_enter_voice')} />
              <datalist id="speaker-group-voice-datalist">
                {currentVoiceOptions.map((v) => <option key={v.value} value={v.value}>{v.label}</option>)}
              </datalist>
              <p className="text-xs text-[var(--color-text-tertiary)]">
                {t('current_tts_config_hint', { name: currentTtsConfigName })}
              </p>
            </div>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={onClose} disabled={submitting}>{t('cancel')}</Button>
          <Button onClick={onSubmit} disabled={submitting}>
            {submitting && <Loader2 className="w-4 h-4 mr-1.5 animate-spin" />}
            {mode === 'add' ? t('create') : t('save')}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
