// manager/frontend/src/components/MobileLayout.vue
<template>
  <div class="mobile-layout">
    <MobileNavBar
      :title="pageTitle"
      :show-back="showBack"
      class="mobile-nav-bar"
    >
      <template #right>
        <van-icon name="user-o" class="user-entry-icon" @click="handleUserClick" />
      </template>
    </MobileNavBar>

    <div class="mobile-content" :class="{ 'with-tabbar': showTabBar }">
      <router-view v-slot="{ Component }">
        <transition name="fade" mode="out-in">
          <component :is="Component" />
        </transition>
      </router-view>
    </div>

    <MobileTabBar v-if="showTabBar" class="mobile-tabbar" />

    <!-- User menu popup -->
    <van-popup
      v-model:show="showUserMenu"
      position="bottom"
      :style="{ padding: '20px' }"
    >
      <div class="user-menu">
        <div class="user-info">
          <van-icon name="user-circle-o" size="48" />
          <div class="user-details">
            <div class="username">{{ authStore.user?.username }}</div>
            <div class="user-role">{{ roleText }}</div>
          </div>
        </div>
        <van-cell-group inset>
          <van-cell :title="t('more_features')" is-link @click="handleGoMore" />
          <van-cell v-if="!authStore.isAdmin" title="API Token" is-link @click="handleGoApiTokens" />
          <van-cell v-if="authStore.isAdmin" :title="t('config_wizard')" is-link @click="handleGoConfigWizard" />
          <van-cell :title="t('logout')" is-link @click="handleLogout" />
        </van-cell-group>
      </div>
    </van-popup>
  </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { showConfirmDialog, showSuccessToast } from 'vant'
import MobileNavBar from './MobileNavBar.vue'
import MobileTabBar from './MobileTabBar.vue'
import { useAuthStore } from '../stores/auth'
import { isMobile } from '../utils/device'
import { useLocale } from '../composables/useLocale'
const { t } = useLocale()

const route = useRoute()
const router = useRouter()
const authStore = useAuthStore()

const showUserMenu = ref(false)

// Page title
const pageTitle = computed(() => {
  const key = route.meta?.title
  return key ? t(key) : t('xiaozhi_management_system')
})

// Show back button when not on home and not on a tab-bar page
const showBack = computed(() => {
  const hideBackPages = ['/dashboard', '/agents', '/user/speakers', '/more', '/login']
  const currentPath = route.path
  return !hideBackPages.some(path => currentPath === path || currentPath.startsWith(path + '/'))
})

// Show bottom tab bar
const showTabBar = computed(() => {
  const hideTabBarPages = [
    '/login',
    '/setup',
    '/test',
    '/simple-login'
  ]
  const currentPath = route.path

  // Hide tab bar on detail pages
  if (currentPath.includes('/edit') || currentPath.includes('/detail') || currentPath.includes('/history')) {
    return false
  }

  return !hideTabBarPages.includes(currentPath)
})

// Role label
const roleText = computed(() => {
  return authStore.isAdmin ? t('admin') : t('normal_user')
})

// User avatar click
const handleUserClick = () => {
  showUserMenu.value = true
}


const handleGoMore = () => {
  router.push('/more')
  showUserMenu.value = false
}

const handleGoApiTokens = () => {
  router.push('/user/api-tokens')
  showUserMenu.value = false
}

const handleGoConfigWizard = () => {
  router.push('/admin/config-wizard')
  showUserMenu.value = false
}

// Logout
const handleLogout = async () => {
  try {
    await showConfirmDialog({
      title: t('hint'),
      message: t('confirm_logout')
    })

    authStore.logout()
    showSuccessToast(t('logged_out'))
    router.push('/login')
    showUserMenu.value = false
  } catch {
    // User cancelled
  }
}

// Close user menu on route change
watch(
  () => route.path,
  () => {
    showUserMenu.value = false
  }
)
</script>

<style scoped>
.mobile-layout {
  height: 100dvh;
  background:
    radial-gradient(circle at top left, rgba(0, 122, 255, 0.08), transparent 28%),
    linear-gradient(180deg, #fbfcfe 0%, var(--apple-bg) 100%);
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.mobile-content {
  flex: 1;
  min-height: 0;
  overflow-y: auto;
  padding-bottom: 0;
  -webkit-overflow-scrolling: touch;
}

.mobile-content.with-tabbar {
  padding-bottom: calc(84px + env(safe-area-inset-bottom));
}

/* Page transition animation */
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}


.user-entry-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  border-radius: 12px;
  background: rgba(0, 122, 255, 0.08);
  color: var(--apple-primary);
  font-size: 16px;
  line-height: 1;
}

.user-menu {
  padding: 4px 0 10px;
}

.user-info {
  display: flex;
  align-items: center;
  padding: 12px 16px 18px;
  margin-bottom: 16px;
}

.user-info .van-icon {
  margin-right: 16px;
  color: var(--apple-primary);
}

.user-details {
  flex: 1;
}

.username {
  font-size: 18px;
  font-weight: 700;
  color: var(--apple-text);
  margin-bottom: 4px;
}

.user-role {
  font-size: 14px;
  color: var(--apple-text-secondary);
}

:deep(.van-popup) {
  border-radius: 24px 24px 0 0;
  border: 1px solid rgba(255, 255, 255, 0.88);
}

:deep(.van-cell-group--inset) {
  margin: 0;
}
</style>

// manager/frontend/src/components/layout/mobile-layout.tsx
import { useState } from 'react'
import { Outlet, Link, useRouterState, useRouter } from '@tanstack/react-router'
import { ChevronLeft, User, Home, Settings, Users, MoreHorizontal, Bot, Mic } from 'lucide-react'
import { cn } from '@/lib/utils'
import { Sheet, SheetContent } from '@/components/ui/sheet'
import { useAuthStore } from '@/stores/auth'
import { useLocale } from '@/hooks/use-locale'
import { getPageTitle } from '@/utils/page-title'

const HIDE_BACK = ['/dashboard', '/agents', '/user/speakers', '/more', '/login']
const HIDE_TAB = ['/login', '/setup']

function MobileNavBar({ title, showBack }: { title: string; showBack: boolean; onUserClick: () => void }) {
  const router = useRouter()
  const { onUserClick: _unused, ..._ } = { onUserClick: () => {} }
  void _unused; void _
  return (
    <header className="flex items-center h-12 px-3 mx-3 mt-3 rounded-2xl border border-[var(--color-line)] bg-[var(--color-surface-1)] sticky top-3 z-10 shadow-sm">
      {showBack && (
        <button
          type="button"
          onClick={() => router.history.back()}
          className="flex items-center justify-center min-w-[44px] h-full -ml-1 mr-1 rounded-xl text-[var(--color-text)]"
        >
          <ChevronLeft className="w-5 h-5" />
        </button>
      )}
      <h1 className="flex-1 text-base font-bold text-[var(--color-text)] truncate">{title}</h1>
    </header>
  )
}

function MobileTabBar() {
  const { t } = useLocale()
  const isAdmin = useAuthStore((s) => s.isAdmin)
  const pathname = useRouterState({ select: (s) => s.location.pathname })

  const isActive = (path: string) => pathname === path || pathname.startsWith(path + '/')

  const tabs = isAdmin
    ? [
        { path: '/dashboard', label: t('home'), icon: Home },
        { path: '/admin/config-overview', label: t('config'), icon: Settings },
        { path: '/admin/users', label: t('manage'), icon: Users },
        { path: '/more', label: t('more'), icon: MoreHorizontal },
      ]
    : [
        { path: '/agents', label: t('agent'), icon: Bot },
        { path: '/user/speakers', label: t('voiceprint'), icon: Mic },
        { path: '/more', label: t('more'), icon: MoreHorizontal },
      ]

  return (
    <nav
      className="mx-3 mb-3 flex rounded-2xl border border-[var(--color-line)] bg-[var(--color-surface-1)] overflow-hidden shadow-sm"
      style={{ paddingBottom: 'env(safe-area-inset-bottom, 0px)' }}
    >
      {tabs.map((tab) => {
        const Icon = tab.icon
        return (
          <Link
            key={tab.path}
            to={tab.path}
            className={cn(
              'flex-1 flex flex-col items-center justify-center py-3 gap-1 transition-colors',
              isActive(tab.path)
                ? 'text-[var(--color-primary)]'
                : 'text-[var(--color-text-tertiary)] hover:text-[var(--color-text)]'
            )}
          >
            <Icon className="w-5 h-5" />
            <span className="text-[10px] font-medium">{tab.label}</span>
          </Link>
        )
      })}
    </nav>
  )
}

export function MobileLayout() {
  const { t } = useLocale()
  const { user, isAdmin, logout } = useAuthStore()
  const pathname = useRouterState({ select: (s) => s.location.pathname })
  const [showUserMenu, setShowUserMenu] = useState(false)
  const router = useRouter()

  const showBack = !HIDE_BACK.some((p) => pathname === p || pathname.startsWith(p + '/'))
  const showTab = !HIDE_TAB.includes(pathname) &&
    !pathname.includes('/edit') && !pathname.includes('/detail') && !pathname.includes('/history')

  const pageTitle = getPageTitle(pathname, isAdmin, t)

  const handleLogout = () => {
    logout()
    router.navigate({ to: '/login' })
    setShowUserMenu(false)
  }

  return (
    <div className="flex flex-col h-dvh bg-[var(--color-bg)] overflow-hidden">
      <div className="flex items-center">
        <div className="flex-1">
          <MobileNavBar title={pageTitle} showBack={showBack} onUserClick={() => setShowUserMenu(true)} />
        </div>
        <button
          type="button"
          onClick={() => setShowUserMenu(true)}
          className="flex items-center justify-center w-9 h-9 rounded-xl bg-[var(--color-primary-soft)] text-[var(--color-primary)] mr-4 mt-3 shrink-0"
        >
          <User className="w-4 h-4" />
        </button>
      </div>

      <main className="flex-1 min-h-0 overflow-y-auto overscroll-contain">
        <Outlet />
      </main>

      {showTab && <MobileTabBar />}

      {/* User menu bottom sheet */}
      <Sheet open={showUserMenu} onOpenChange={setShowUserMenu}>
        <SheetContent side="bottom" className="rounded-t-3xl px-0 pb-0">
          <div className="flex items-center gap-4 px-5 py-5 border-b border-[var(--color-line)]">
            <div className="flex items-center justify-center w-14 h-14 rounded-2xl bg-[var(--color-primary-soft)] text-[var(--color-primary)] shrink-0">
              <User className="w-7 h-7" />
            </div>
            <div>
              <div className="text-lg font-bold text-[var(--color-text)]">{user?.username}</div>
              <div className="text-sm text-[var(--color-text-secondary)]">
                {isAdmin ? t('admin') : t('normal_user')}
              </div>
            </div>
          </div>
          <div className="divide-y divide-[var(--color-line)]">
            <button type="button" onClick={() => { router.navigate({ to: '/more' }); setShowUserMenu(false) }}
              className="flex items-center w-full px-5 py-4 text-sm text-[var(--color-text)] hover:bg-[var(--color-surface-2)] transition-colors text-left">
              {t('more_features')}<span className="ml-auto text-[var(--color-text-tertiary)] text-base">›</span>
            </button>
            {!isAdmin && (
              <button type="button" onClick={() => { router.navigate({ to: '/user/api-tokens' }); setShowUserMenu(false) }}
                className="flex items-center w-full px-5 py-4 text-sm text-[var(--color-text)] hover:bg-[var(--color-surface-2)] transition-colors text-left">
                API Token<span className="ml-auto text-[var(--color-text-tertiary)] text-base">›</span>
              </button>
            )}
            {isAdmin && (
              <button type="button" onClick={() => { router.navigate({ to: '/admin/config-wizard' }); setShowUserMenu(false) }}
                className="flex items-center w-full px-5 py-4 text-sm text-[var(--color-text)] hover:bg-[var(--color-surface-2)] transition-colors text-left">
                {t('config_wizard')}<span className="ml-auto text-[var(--color-text-tertiary)] text-base">›</span>
              </button>
            )}
            <button type="button" onClick={handleLogout}
              className="flex items-center w-full px-5 py-4 text-sm text-[var(--color-danger)] hover:bg-[color-mix(in_srgb,var(--color-danger)_8%,transparent)] transition-colors text-left">
              {t('logout')}
            </button>
          </div>
          <div style={{ height: 'max(16px, env(safe-area-inset-bottom))' }} />
        </SheetContent>
      </Sheet>
    </div>
  )
}
