// manager/frontend/src/views/admin/ChatSettings.vue
<template>
  <div class="config-page">
    <div class="page-actions">
      <el-button @click="loadSettings" :loading="loading">{{ t('refresh') }}</el-button>
      <el-button type="primary" @click="saveSettings" :loading="saving">{{ t('save_settings') }}</el-button>
    </div>

    <el-card v-loading="loading">
      <el-form ref="formRef" :model="form" :rules="rules" label-width="180px" style="max-width: 720px;">
        <el-divider content-position="left">{{ t('identity_verification') }}</el-divider>
        <el-form-item :label="t('enable_device_activation')" prop="auth.enable">
          <el-switch v-model="form.auth.enable" />
        </el-form-item>
        <el-form-item :label="t('login_digit_verify')" prop="auth.login_captcha_enabled">
          <el-switch
            v-model="form.auth.login_captcha_enabled"
            active-:text="t('enable')"
            :inactive-text="t('close')"
          />
          <div class="form-help">
            {{ t('captcha_enabled_hint') }}</div>
        </el-form-item>

        <el-divider content-position="left">{{ t('chat_params') }}</el-divider>
        <el-form-item :label="t('session_max_idle_time')" prop="chat.max_idle_duration">
          <el-input-number v-model="form.chat.max_idle_duration" :min="0" :step="1000" style="width: 100%;" />
          <div class="form-help">
            {{ t('session_idle_hint') }}</div>
        </el-form-item>
        <el-form-item :label="t('sentence_end_silence_threshold')" prop="chat.chat_max_silence_duration">
          <el-input-number v-model="form.chat.chat_max_silence_duration" :min="0" :step="10" style="width: 100%;" />
          <div class="form-help">
            {{ t('chat_silence_hint') }}
          </div>
        </el-form-item>
        <el-form-item :label="t('realtime_interrupt_mode')" prop="chat.realtime_mode">
          <el-select v-model="form.chat.realtime_mode" style="width: 100%;">
            <el-option :value="1" :label="t('vad_interrupt_mode_1')" />
            <el-option :value="2" :label="t('asr_interrupt_mode')" />
            <el-option :value="3" :label="t('asr_voiceprint_interrupt')" />
            <el-option :value="4" :label="t('asr_result_interrupt')" />
          </el-select>
        </el-form-item>
        <el-form-item :label="t('global_system_prompt_desc')" prop="chat.global_system_prompt">
          <el-input
            v-model="form.chat.global_system_prompt"
            type="textarea"
            :rows="6"
            maxlength="8000"
            show-word-limit
            :placeholder="t('system_prompt_prefix_hint')"
          />
          <div class="form-help">
            {{ t('system_prompt_order_hint') }}</div>
        </el-form-item>
      </el-form>
    </el-card>
  </div>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import api from '../../utils/api'
import { useLocale } from '../../composables/useLocale'
const { t } = useLocale()

const loading = ref(false)
const saving = ref(false)
const formRef = ref()

const form = reactive({
  auth: {
    enable: false,
    login_captcha_enabled: true
  },
  chat: {
    max_idle_duration: 30000,
    chat_max_silence_duration: 400,
    realtime_mode: 4,
    global_system_prompt: ''
  }
})

const rules = {
  'chat.max_idle_duration': [
    { required: true, message: t('enter_max_idle_time'), trigger: 'blur' }
  ],
  'chat.chat_max_silence_duration': [
    { required: true, message: t('enter_sentence_end_silence'), trigger: 'blur' }
  ],
  'chat.realtime_mode': [
    { required: true, message: t('select_interrupt_mode'), trigger: 'change' }
  ],
  'chat.global_system_prompt': [
    { max: 8000, message: t('global_system_prompt_max'), trigger: 'blur' }
  ]
}

const loadSettings = async () => {
  loading.value = true
  try {
    const res = await api.get('/admin/chat-settings')
    const data = res.data?.data || {}
    form.auth.enable = !!data.auth?.enable
    form.auth.login_captcha_enabled = data.auth?.login_captcha_enabled !== false
    form.chat.max_idle_duration = Number(data.chat?.max_idle_duration ?? 30000)
    form.chat.chat_max_silence_duration = Number(data.chat?.chat_max_silence_duration ?? 400)
    form.chat.realtime_mode = Number(data.chat?.realtime_mode ?? 4)
    form.chat.global_system_prompt = String(data.chat?.global_system_prompt ?? '')
  } catch (error) {
    ElMessage.error(t('load_chat_settings_failed'))
    console.error(error)
  } finally {
    loading.value = false
  }
}

const saveSettings = async () => {
  if (!formRef.value) return
  const valid = await formRef.value.validate().catch(() => false)
  if (!valid) return

  saving.value = true
  try {
    await api.put('/admin/chat-settings', {
      auth: {
        enable: !!form.auth.enable,
        login_captcha_enabled: form.auth.login_captcha_enabled !== false
      },
      chat: {
        max_idle_duration: Number(form.chat.max_idle_duration),
        chat_max_silence_duration: Number(form.chat.chat_max_silence_duration),
        realtime_mode: Number(form.chat.realtime_mode),
        global_system_prompt: String(form.chat.global_system_prompt || '')
      }
    })
    ElMessage.success(t('chat_settings_save_success'))
  } catch (error) {
    ElMessage.error(t('chat_settings_save_failed'))
    console.error(error)
  } finally {
    saving.value = false
  }
}

onMounted(() => {
  loadSettings()
})
</script>

<style scoped>
.config-page {
  padding: 20px;
}

.page-actions {
  display: flex;
  justify-content: flex-end;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
  margin-bottom: 20px;
}

.form-help {
  margin-top: 6px;
  color: #909399;
  font-size: 12px;
  line-height: 1.5;
}
</style>

// manager/frontend/src/routes/_auth/_layout/admin/chat-settings.tsx
import { useEffect, useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { toast } from 'sonner'
import api from '@/utils/api'
import { useLocale } from '@/hooks/use-locale'
import { Button } from '@/components/ui/button'
import { Switch } from '@/components/ui/switch'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { Input } from '@/components/ui/input'
import { PageHeader } from '@/components/ui/page-header'

interface ChatSettingsData {
  auth: { enable: boolean; login_captcha_enabled: boolean }
  chat: { max_idle_duration: number; chat_max_silence_duration: number; realtime_mode: number; global_system_prompt: string }
}

const defaults: ChatSettingsData = {
  auth: { enable: false, login_captcha_enabled: true },
  chat: { max_idle_duration: 30000, chat_max_silence_duration: 400, realtime_mode: 4, global_system_prompt: '' },
}

function ChatSettingsPage() {
  const { t } = useLocale()
  const [loading, setLoading] = useState(false)
  const [saving, setSaving] = useState(false)
  const [form, setForm] = useState<ChatSettingsData>(defaults)

  const setAuth = (patch: Partial<ChatSettingsData['auth']>) => setForm((f) => ({ ...f, auth: { ...f.auth, ...patch } }))
  const setChat = (patch: Partial<ChatSettingsData['chat']>) => setForm((f) => ({ ...f, chat: { ...f.chat, ...patch } }))

  const load = async () => {
    setLoading(true)
    try {
      const res = await api.get('/admin/chat-settings')
      const d = res.data?.data || {}
      setForm({
        auth: { enable: !!d.auth?.enable, login_captcha_enabled: d.auth?.login_captcha_enabled !== false },
        chat: {
          max_idle_duration: Number(d.chat?.max_idle_duration ?? 30000),
          chat_max_silence_duration: Number(d.chat?.chat_max_silence_duration ?? 400),
          realtime_mode: Number(d.chat?.realtime_mode ?? 4),
          global_system_prompt: String(d.chat?.global_system_prompt ?? ''),
        },
      })
    } catch { toast.error(t('load_chat_settings_failed')) }
    finally { setLoading(false) }
  }

  const save = async () => {
    setSaving(true)
    try {
      await api.put('/admin/chat-settings', form)
      toast.success(t('chat_settings_save_success'))
    } catch { toast.error(t('chat_settings_save_failed')) }
    finally { setSaving(false) }
  }

  useEffect(() => { load() }, []) // eslint-disable-line react-hooks/exhaustive-deps

  if (loading) return <div className="p-6 text-center text-sm text-[var(--color-text-secondary)]">{t('loading')}</div>

  return (
    <div className="grid gap-4 px-6 pb-8">
      <PageHeader title={t('chat_settings')} />
      <div className="flex justify-end items-center gap-2">
        <Button variant="outline" onClick={load}>{t('refresh')}</Button>
        <Button disabled={saving} onClick={save}>{t('save_settings')}</Button>
      </div>

      <div className="max-w-[720px] rounded-xl border border-[var(--color-line)] bg-[var(--color-surface-1)]">
        <div className="p-6 grid gap-6">
          <div>
            <p className="text-xs font-bold tracking-widest uppercase text-[var(--color-text-tertiary)] mb-4">{t('identity_verification')}</p>
            <div className="grid gap-5">
              <div className="flex items-center justify-between gap-4">
                <label className="text-sm font-semibold text-[var(--color-text)]">{t('enable_device_activation')}</label>
                <Switch checked={form.auth.enable} onCheckedChange={(v) => setAuth({ enable: v })} />
              </div>
              <div className="grid gap-1.5">
                <div className="flex items-center justify-between gap-4">
                  <label className="text-sm font-semibold text-[var(--color-text)]">{t('login_digit_verify')}</label>
                  <Switch checked={form.auth.login_captcha_enabled} onCheckedChange={(v) => setAuth({ login_captcha_enabled: v })} />
                </div>
                <p className="text-xs text-[var(--color-text-secondary)]">{t('captcha_enabled_hint')}</p>
              </div>
            </div>
          </div>

          <div className="pt-6 border-t border-[var(--color-line)]">
            <p className="text-xs font-bold tracking-widest uppercase text-[var(--color-text-tertiary)] mb-4">{t('chat_params')}</p>
            <div className="grid gap-5">
              <div className="grid gap-1.5">
                <label className="text-sm font-semibold text-[var(--color-text)]">{t('session_max_idle_time')}</label>
                <Input type="number" value={form.chat.max_idle_duration} onChange={(e) => setChat({ max_idle_duration: Number(e.target.value) })} />
                <p className="text-xs text-[var(--color-text-secondary)]">{t('session_idle_hint')}</p>
              </div>
              <div className="grid gap-1.5">
                <label className="text-sm font-semibold text-[var(--color-text)]">{t('sentence_end_silence_threshold')}</label>
                <Input type="number" value={form.chat.chat_max_silence_duration} onChange={(e) => setChat({ chat_max_silence_duration: Number(e.target.value) })} />
                <p className="text-xs text-[var(--color-text-secondary)]">{t('chat_silence_hint')}</p>
              </div>
              <div className="grid gap-1.5">
                <label className="text-sm font-semibold text-[var(--color-text)]">{t('realtime_interrupt_mode')}</label>
                <Select value={String(form.chat.realtime_mode)} onValueChange={(v) => setChat({ realtime_mode: Number(v) })}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="1">{t('vad_interrupt_mode_1')}</SelectItem>
                    <SelectItem value="2">{t('asr_interrupt_mode')}</SelectItem>
                    <SelectItem value="3">{t('asr_voiceprint_interrupt')}</SelectItem>
                    <SelectItem value="4">{t('asr_result_interrupt')}</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="grid gap-1.5">
                <label className="text-sm font-semibold text-[var(--color-text)]">{t('global_system_prompt_desc')}</label>
                <Textarea
                  value={form.chat.global_system_prompt}
                  onChange={(e) => setChat({ global_system_prompt: e.target.value })}
                  rows={6}
                  maxLength={8000}
                  placeholder={t('system_prompt_prefix_hint')}
                />
                <p className="text-xs text-[var(--color-text-secondary)] text-right">{form.chat.global_system_prompt.length} / 8000</p>
                <p className="text-xs text-[var(--color-text-secondary)]">{t('system_prompt_order_hint')}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export const Route = createFileRoute('/_auth/_layout/admin/chat-settings')({
  component: ChatSettingsPage,
})
