// manager/frontend/src/views/admin/Devices.vue
<template>
  <div class="admin-devices">
    <div class="toolbar">
      <el-button type="primary" @click="openAddDialog">
        <el-icon><Plus /></el-icon>
        {{ t('add_agent') }}
      </el-button>
      <el-button @click="loadDevices">
        <el-icon><Refresh /></el-icon>
        {{ t('refresh') }}
      </el-button>
    </div>

    <el-table :data="devices" v-loading="loading" stripe>
      <el-table-column prop="id" label="ID" width="80" />
      <el-table-column :label="t('device_nickname')" min-width="170">
        <template #default="{ row }">
          <span class="device-nick-name">{{ getDeviceDisplayName(row) }}</span>
        </template>
      </el-table-column>
      <el-table-column prop="device_code" :label="t('activation_code')" width="150" />
      <el-table-column :label="t('device_id')" width="190">
        <template #default="{ row }">
          <span class="device-id-text">{{ row.device_name || '-' }}</span>
        </template>
      </el-table-column>
      <el-table-column prop="user_id" :label="t('user_prefix') + 'ID'" width="100" />
      <el-table-column :label="t('link_agent')" width="150">
        <template #default="{ row }">
          <span v-if="row.agent_id > 0">
            {{ row.agent_name || t('agent_id_fallback', { id: row.agent_id }) }}
          </span>
          <el-tag v-else type="info" size="small">{{ t('no_agent_linked') }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column :label="t('activation_status')" width="100">
        <template #default="{ row }">
          <el-tag :type="row.activated ? 'success' : 'warning'">
            {{ row.activated ? t('active') : t('no_agent_linked') }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column :label="t('online_devices')" width="100">
        <template #default="{ row }">
          <el-tag :type="isDeviceOnline(row.last_active_at) ? 'success' : 'danger'">
            {{ isDeviceOnline(row.last_active_at) ? t('online') : t('close') }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column prop="last_active_at" :label="t('latest_data')" width="180">
        <template #default="{ row }">
          {{ row.last_active_at ? new Date(row.last_active_at).toLocaleString() : t('never_active') }}
        </template>
      </el-table-column>
      <el-table-column prop="created_at" :label="t('start_date')" width="180">
        <template #default="{ row }">
          {{ new Date(row.created_at).toLocaleString() }}
        </template>
      </el-table-column>
      <el-table-column :label="t('operation_failed').replace(t('failed'), '')" width="300">
        <template #default="{ row }">
          <el-button size="small" @click="editDevice(row)">
            {{ t('cancel_edit').replace(t('cancel'), '') }}
          </el-button>
          <el-button size="small" type="primary" @click="showDeviceMcp(row)">
            MCP
          </el-button>
          <el-button size="small" type="danger" @click="deleteDevice(row)">
            {{ t('delete') }}
          </el-button>
        </template>
      </el-table-column>
    </el-table>

    <!-- 添加/编辑设备对话框 -->

    <el-dialog v-model="showMcpDialog" :title="t('device_mcp_tools')" width="760px">
      <div v-loading="mcpLoading">
        <div class="mcp-tools-header">
          <el-button size="small" type="primary" @click="refreshDeviceMcpTools" :loading="toolsLoading">{{ t('refresh') }}</el-button>
        </div>

        <div v-if="mcpTools.length === 0" class="tools-empty">{{ t('no_mcp_endpoint_to_copy') }}</div>
        <div v-else class="tools-tags">
          <el-tag v-for="tool in mcpTools" :key="tool.name" class="tool-tag">{{ tool.name }}</el-tag>
        </div>

        <el-divider />

        <el-form :model="mcpCallForm" label-width="90px">
          <el-form-item :label="t('tool_name')">
            <el-select v-model="mcpCallForm.tool_name" :placeholder="t('select_tool')" style="width:100%" @change="handleMcpToolChange">
              <el-option v-for="tool in mcpTools" :key="tool.name" :label="tool.name" :value="tool.name" />
            </el-select>
          </el-form-item>
          <el-form-item :label="t('params_json_format_error').replace(t('format_error'), '')">
            <el-input v-model="mcpCallForm.argumentsText" type="textarea" :rows="6" :placeholder="t('mcp_args_placeholder')" />
          </el-form-item>
        </el-form>

        <el-button type="primary" @click="callDeviceMcpTool" :loading="callingTool">{{ t('call_device_tool') }}</el-button>

        <el-divider />
        <div class="endpoint-content">{{ mcpCallResult || t('no_mcp_endpoint_to_copy') }}</div>
      </div>
    </el-dialog>

    <el-dialog
      v-model="showAddDialog"
      :title="editingDevice ? t('device_update_success').replace(t('update_success'), t('edit')) : t('add_agent')"
      width="500px"
    >
      <DeviceForm
        ref="deviceFormRef"
        v-model="deviceForm"
        is-admin
        :mode="editingDevice ? 'edit' : 'create'"
      />
      <template #footer>
        <el-button @click="showAddDialog = false">{{ t('cancel') }}</el-button>
        <el-button type="primary" @click="saveDevice" :loading="saving">
          {{ editingDevice ? t('update_success').replace(t('success'), '') : t('add_agent').replace(t('agent'), '') }}
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, Refresh } from '@element-plus/icons-vue'
import api from '../../utils/api'
import DeviceForm from '../../components/common/DeviceForm.vue'
import { createDefaultDeviceForm, deviceToForm } from '../../composables/useAgentFormOptions'
import { useLocale } from '../../composables/useLocale'

const { t } = useLocale()

const devices = ref([])
const loading = ref(false)
const showAddDialog = ref(false)
const editingDevice = ref(null)
const saving = ref(false)
const deviceFormRef = ref()

const showMcpDialog = ref(false)
const mcpLoading = ref(false)
const toolsLoading = ref(false)
const callingTool = ref(false)
const currentDeviceId = ref(null)
const mcpTools = ref([])
const mcpCallResult = ref('')
const mcpCallForm = ref({ tool_name: '', argumentsText: '{}' })
const deviceForm = ref(createDefaultDeviceForm({ isAdmin: true }))

const loadDevices = async () => {
  loading.value = true
  try {
    const response = await api.get('/admin/devices')
    devices.value = response.data.data || []
  } catch (error) {
    ElMessage.error(t('load_device_list_failed'))
    console.error('Error loading devices:', error)
  } finally {
    loading.value = false
  }
}

const getDeviceDisplayName = (device) => {
  const nickName = String(device?.nick_name || '').trim()
  if (nickName) return nickName
  return String(device?.device_name || '').trim() || t('unnamed_device')
}

const openAddDialog = () => {
  editingDevice.value = null
  deviceForm.value = createDefaultDeviceForm({ isAdmin: true })
  showAddDialog.value = true
}

const editDevice = (device) => {
  editingDevice.value = device
  deviceForm.value = deviceToForm(device, { isAdmin: true })
  showAddDialog.value = true
}

const saveDevice = async () => {
  if (!deviceFormRef.value) return

  const valid = await deviceFormRef.value.validate().catch(() => false)
  if (!valid) return

  saving.value = true
  try {
    const payload = deviceFormRef.value.buildPayload()
    if (editingDevice.value) {
      await api.put(`/admin/devices/${editingDevice.value.id}`, payload)
      ElMessage.success(t('device_update_success'))
    } else {
      const response = await api.post('/admin/devices', payload)
      // 根据后端返回的消息显示不同的提示
      const message = response.data.message || t('device_bind_success')
      ElMessage.success(message)
    }
    showAddDialog.value = false
    resetForm()
    loadDevices()
  } catch (error) {
    const errorMessage = error.response?.data?.error || (editingDevice.value ? t('update_failed') : t('delete_failed'))
    ElMessage.error(errorMessage)
    console.error('Error saving device:', error)
  } finally {
    saving.value = false
  }
}

const deleteDevice = async (device) => {
  try {
    await ElMessageBox.confirm(
      t('confirm_delete_device_msg', { name: getDeviceDisplayName(device) }),
      t('confirm'),
      {
        confirmButtonText: t('confirm'),
        cancelButtonText: t('cancel'),
        type: 'warning'
      }
    )

    await api.delete(`/admin/devices/${device.id}`)
    ElMessage.success(t('device_delete_success'))
    loadDevices()
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error(t('device_delete_failed'))
      console.error('Error deleting device:', error)
    }
  }
}



const showDeviceMcp = async (device) => {
  currentDeviceId.value = device.id
  showMcpDialog.value = true
  mcpLoading.value = true
  mcpCallResult.value = ''
  mcpCallForm.value = { tool_name: '', argumentsText: '{}' }
  try {
    await refreshDeviceMcpTools()
  } finally {
    mcpLoading.value = false
  }
}

const refreshDeviceMcpTools = async () => {
  if (!currentDeviceId.value) return
  toolsLoading.value = true
  try {
    const response = await api.get(`/admin/devices/${currentDeviceId.value}/mcp-tools`)
    mcpTools.value = response.data.data?.tools || []
    if (!mcpCallForm.value.tool_name && mcpTools.value.length > 0) {
      mcpCallForm.value.tool_name = mcpTools.value[0].name
    }
  } catch (error) {
    ElMessage.error(t('fetch_device_mcp_failed'))
    mcpTools.value = []
  } finally {
    toolsLoading.value = false
  }
}



const buildExampleFromSchema = (schema = {}) => {
  if (!schema || typeof schema !== 'object') return {}
  if (Array.isArray(schema.enum) && schema.enum.length > 0) return schema.enum[0]

  const type = schema.type || 'object'
  if (type === 'object') {
    const props = schema.properties || {}
    const result = {}
    Object.keys(props).sort().forEach((key) => {
      result[key] = buildExampleFromSchema(props[key])
    })
    return result
  }
  if (type === 'array') {
    return [buildExampleFromSchema(schema.items || {})]
  }
  if (type === 'number') return 0.1
  if (type === 'integer') return 0
  if (type === 'boolean') return false
  return ''
}

const updateMcpExampleByTool = (toolName) => {
  const selectedTool = mcpTools.value.find(item => item.name === toolName)
  if (!selectedTool) return

  const example = buildExampleFromSchema(selectedTool.input_schema || {})
  mcpCallForm.value.argumentsText = JSON.stringify(example ?? {}, null, 2)
}

const handleMcpToolChange = (toolName) => {
  updateMcpExampleByTool(toolName)
}

const formatMcpCallResult = (payload) => {
  const MAX_PARSE_DEPTH = 8

  const tryParseJSONString = (value) => {
    if (typeof value !== 'string') return { parsed: false, value }
    let text = value.trim()
    if (!text) return { parsed: false, value }

    const fenced = text.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i)
    if (fenced) {
      text = fenced[1].trim()
    }

    const looksLikeJSON =
      (text.startsWith('{') && text.endsWith('}')) ||
      (text.startsWith('[') && text.endsWith(']'))
    if (!looksLikeJSON) return { parsed: false, value }

    try {
      return { parsed: true, value: JSON.parse(text) }
    } catch (_) {
      return { parsed: false, value }
    }
  }

  const deepParseJSONStrings = (value, depth = 0) => {
    if (depth >= MAX_PARSE_DEPTH || value == null) return value

    if (typeof value === 'string') {
      const parsed = tryParseJSONString(value)
      if (!parsed.parsed) return value
      return deepParseJSONStrings(parsed.value, depth + 1)
    }

    if (Array.isArray(value)) {
      return value.map((item) => deepParseJSONStrings(item, depth + 1))
    }

    if (typeof value === 'object') {
      const out = {}
      Object.keys(value).forEach((key) => {
        out[key] = deepParseJSONStrings(value[key], depth + 1)
      })

      if (Array.isArray(out.content) && out.content.length === 1) {
        const first = out.content[0]
        if (first && typeof first === 'object' && !Array.isArray(first) && first.type === 'text' && Object.prototype.hasOwnProperty.call(first, 'text')) {
          const textValue = first.text
          if (textValue && typeof textValue === 'object') {
            return textValue
          }
        }
      }

      return out
    }

    return value
  }

  const data = payload ?? {}
  const raw = (data && typeof data === 'object' && !Array.isArray(data) && Object.prototype.hasOwnProperty.call(data, 'result'))
    ? data.result
    : data

  return JSON.stringify(deepParseJSONStrings(raw), null, 2)
}

const callDeviceMcpTool = async () => {
  if (!currentDeviceId.value || !mcpCallForm.value.tool_name) {
    ElMessage.warning(t('select_tool'))
    return
  }

  let argumentsObj = {}
  try {
    argumentsObj = mcpCallForm.value.argumentsText ? JSON.parse(mcpCallForm.value.argumentsText) : {}
  } catch (e) {
    ElMessage.error(t('params_json_format_error'))
    return
  }

  callingTool.value = true
  try {
    const response = await api.post(`/admin/devices/${currentDeviceId.value}/mcp-call`, {
      tool_name: mcpCallForm.value.tool_name,
      arguments: argumentsObj
    })
    mcpCallResult.value = formatMcpCallResult(response.data.data || {})
    ElMessage.success(t('mcp_tool_call_success'))
  } catch (error) {
    mcpCallResult.value = JSON.stringify(error.response?.data || { error: error.message }, null, 2)
    ElMessage.error(t('mcp_tool_call_failed'))
  } finally {
    callingTool.value = false
  }
}

const resetForm = () => {
  editingDevice.value = null
  deviceForm.value = createDefaultDeviceForm({ isAdmin: true })
  if (deviceFormRef.value) {
    deviceFormRef.value.resetFields()
  }
}

// 判断设备是否在线（基于最后活跃时间）
const isDeviceOnline = (lastActiveAt) => {
  if (!lastActiveAt) return false
  const now = new Date()
  const lastActive = new Date(lastActiveAt)
  // 5分钟内有活动认为在线
  return (now - lastActive) < 5 * 60 * 1000
}

onMounted(() => {
  loadDevices()
})
</script>

<style scoped>
.admin-devices {
  padding: 20px;
}

.toolbar {
  margin-bottom: 20px;
  display: flex;
  gap: 12px;
  justify-content: flex-end;
  flex-wrap: wrap;
}

.device-nick-name {
  font-weight: 700;
  color: var(--apple-text, #1d1d1f);
}

.device-id-text {
  color: rgba(107, 114, 128, 0.72);
  font-family: monospace;
  font-size: 12px;
}

.form-tip {
  margin-top: 6px;
  color: rgba(107, 114, 128, 0.78);
  font-size: 12px;
  line-height: 1.5;
}

.tools-tags { display:flex; flex-wrap:wrap; gap:8px; margin-bottom:12px; }
.tools-empty { color:#909399; margin: 8px 0 16px; }
.endpoint-content {
  white-space: pre-wrap;
  font-family: monospace;
  background: #f8fafc;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  padding: 10px;
  min-height: 80px;
}
.mcp-tools-header { margin-bottom: 12px; }
</style>

// manager/frontend/src/routes/_auth/_layout/admin/devices.tsx
import { useEffect, useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { MoreHorizontal, Plus, RefreshCw } from 'lucide-react'
import { toast } from 'sonner'
import type { ColumnDef } from '@tanstack/react-table'
import { devicesApi } from '@/features/devices/api/devices-api'
import type { Device, DeviceFormData } from '@/features/devices/types'
import { createDefaultDeviceForm, getDeviceDisplayName, isDeviceOnline } from '@/features/devices/types'
import { DeviceForm } from '@/components/devices/device-form'
import { useLocale } from '@/hooks/use-locale'
import { Button } from '@/components/ui/button'
import { DataTable } from '@/components/ui/data-table'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import { ConfirmDialog } from '@/components/ui/confirm-dialog'
import { PageHeader } from '@/components/ui/page-header'
import { cn } from '@/lib/utils'
import type { McpTool } from '@/features/devices/types'

function AdminDevicesPage() {
  const { t } = useLocale()

  const [devices, setDevices] = useState<Device[]>([])
  const [total, setTotal] = useState(0)
  const [loading, setLoading] = useState(false)
  const [page, setPage] = useState(1)
  const pageSize = 20

  const [showForm, setShowForm] = useState(false)
  const [editing, setEditing] = useState<Device | null>(null)
  const [form, setForm] = useState<DeviceFormData>(createDefaultDeviceForm())
  const [saving, setSaving] = useState(false)

  const [deleteTarget, setDeleteTarget] = useState<Device | null>(null)
  const [deleting, setDeleting] = useState(false)

  const [showMcpDialog, setShowMcpDialog] = useState(false)
  const [mcpLoading, setMcpLoading] = useState(false)
  const [toolsLoading, setToolsLoading] = useState(false)
  const [callingTool, setCallingTool] = useState(false)
  const [currentDeviceId, setCurrentDeviceId] = useState<number | null>(null)
  const [mcpTools, setMcpTools] = useState<McpTool[]>([])
  const [mcpCallResult, setMcpCallResult] = useState('')
  const [mcpToolName, setMcpToolName] = useState('')
  const [mcpToolArgs, setMcpToolArgs] = useState('{}')

  const load = async (p = page) => {
    setLoading(true)
    try {
      const res = await devicesApi.getAdminDevices(p, pageSize)
      setDevices(res.items); setTotal(res.total)
    } catch { toast.error(t('load_device_list_failed')) }
    finally { setLoading(false) }
  }

  useEffect(() => { load(1) }, []) // eslint-disable-line react-hooks/exhaustive-deps

  const openAdd = () => { setEditing(null); setForm(createDefaultDeviceForm()); setShowForm(true) }
  const openEdit = (d: Device) => { setEditing(d); setForm({ agent_id: d.agent_id || null, identifier: '', nick_name: d.nick_name || '', device_name: d.device_name, device_code: d.device_code }); setShowForm(true) }

  const handleSave = async () => {
    setSaving(true)
    try {
      if (editing) {
        await devicesApi.adminUpdateDevice(editing.id, { nick_name: form.nick_name, agent_id: form.agent_id })
        toast.success(t('device_update_success'))
      } else {
        if (!form.agent_id) { toast.error(t('select_target_agent')); setSaving(false); return }
        if (!form.identifier?.trim()) { toast.error(t('enter_6digit_or_mac')); setSaving(false); return }
        await devicesApi.addDevice(form.agent_id, { identifier: form.identifier.trim(), nick_name: form.nick_name.trim() || undefined })
        toast.success(t('device_bind_success'))
      }
      setShowForm(false); await load(page)
    } catch (e) { toast.error((e as Error).message || t('update_failed')) }
    finally { setSaving(false) }
  }

  const handleDelete = async () => {
    if (!deleteTarget) return
    setDeleting(true)
    try {
      await devicesApi.adminDeleteDevice(deleteTarget.id)
      toast.success(t('device_delete_success'))
      setDeleteTarget(null); await load(page)
    } catch (e) { toast.error((e as Error).message || t('device_delete_failed')) }
    finally { setDeleting(false) }
  }

  const openMcp = async (device: Device) => {
    setCurrentDeviceId(device.id); setMcpCallResult(''); setMcpToolName(''); setMcpToolArgs('{}')
    setShowMcpDialog(true); setMcpLoading(true)
    try {
      const tools = await devicesApi.getDeviceMcpTools(device.id)
      setMcpTools(tools)
      if (tools.length) setMcpToolName(tools[0].name)
    } catch { toast.error(t('fetch_device_mcp_failed')) }
    finally { setMcpLoading(false) }
  }

  const refreshMcp = async () => {
    if (!currentDeviceId) return
    setToolsLoading(true)
    try {
      const tools = await devicesApi.getDeviceMcpTools(currentDeviceId)
      setMcpTools(tools)
    } catch { toast.error(t('fetch_device_mcp_failed')) }
    finally { setToolsLoading(false) }
  }

  const callMcp = async () => {
    if (!currentDeviceId || !mcpToolName) { toast.error(t('select_tool')); return }
    let args: Record<string, unknown> = {}
    try { args = JSON.parse(mcpToolArgs) } catch { toast.error(t('mcp_config_format_error')); return }
    setCallingTool(true)
    try {
      const result = await devicesApi.callDeviceMcpTool(currentDeviceId, mcpToolName, args)
      setMcpCallResult(typeof result === 'string' ? result : JSON.stringify(result, null, 2))
      toast.success(t('mcp_tool_call_success'))
    } catch (e) { setMcpCallResult((e as Error).message); toast.error(t('mcp_tool_call_failed')) }
    finally { setCallingTool(false) }
  }

  const totalPages = Math.ceil(total / pageSize) || 1

  const badgeClass = (active: boolean) => cn(
    'inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium',
    active ? 'status-success' : 'status-danger'
  )

  const columns: ColumnDef<Device>[] = [
    { accessorKey: 'id', header: 'ID', cell: ({ row }) => <span className="text-xs font-mono text-[var(--color-text-secondary)]">{row.original.id}</span> },
    { accessorKey: 'nick_name', header: t('device_nickname'), cell: ({ row }) => <span className="font-bold">{getDeviceDisplayName(row.original)}</span> },
    { accessorKey: 'device_code', header: t('activation_code'), cell: ({ row }) => <span className="text-xs">{row.original.device_code || '—'}</span> },
    { accessorKey: 'device_name', header: t('device_id'), cell: ({ row }) => <span className="font-mono text-xs text-[var(--color-text-secondary)]">{row.original.device_name || '—'}</span> },
    { accessorKey: 'user_id', header: t('user_prefix') + 'ID' },
    {
      accessorKey: 'agent_id', header: t('link_agent'),
      cell: ({ row }) => row.original.agent_id
        ? <span className="text-sm">{row.original.agent_name || `#${row.original.agent_id}`}</span>
        : <span className="inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium bg-gray-50 text-gray-500 border-gray-200 dark:bg-gray-800/40 dark:text-gray-400 dark:border-gray-700">{t('no_agent_linked')}</span>
    },
    {
      accessorKey: 'activated', header: t('activation_status'),
      cell: ({ row }) => <span className={cn('inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium', row.original.activated ? 'status-success' : 'status-warning')}>{row.original.activated ? t('activated') : t('not_activated')}</span>
    },
    {
      accessorKey: 'last_active_at', header: t('online_devices'),
      cell: ({ row }) => <span className={badgeClass(isDeviceOnline(row.original.last_active_at))}>{isDeviceOnline(row.original.last_active_at) ? t('online') : t('offline')}</span>
    },
    { accessorKey: 'last_active_at_fmt', header: t('latest_data'), cell: ({ row }) => <span className="text-sm text-[var(--color-text-secondary)]">{row.original.last_active_at ? new Date(row.original.last_active_at).toLocaleString() : t('never_active')}</span> },
    { accessorKey: 'created_at', header: t('start_date'), cell: ({ row }) => <span className="text-sm text-[var(--color-text-secondary)]">{new Date(row.original.created_at).toLocaleString()}</span> },
    {
      id: 'actions', header: () => <span className="sr-only">{t('actions')}</span>,
      cell: ({ row }) => (
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" size="icon" className="h-8 w-8"><MoreHorizontal className="h-4 w-4" /></Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem onClick={() => openEdit(row.original)}>{t('edit')}</DropdownMenuItem>
            <DropdownMenuItem onClick={() => openMcp(row.original)}>MCP</DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem className="text-destructive" onClick={() => setDeleteTarget(row.original)}>{t('delete')}</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      )
    },
  ]

  return (
    <div className="grid gap-4 px-6 pb-8">
      <PageHeader title={t('device_management')} />

      <div className="flex items-center justify-end gap-2">
        <Button variant="outline" onClick={() => load(page)}>
          <RefreshCw className="w-4 h-4 mr-1.5" />{t('refresh')}
        </Button>
        <Button onClick={openAdd}>
          <Plus className="w-4 h-4 mr-1.5" />{t('add_device')}
        </Button>
      </div>

      <DataTable columns={columns} data={devices} isLoading={loading} />

      <div className="flex items-center justify-between text-sm text-[var(--color-text-secondary)]">
        <span>{total} {t('total_items')}</span>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" disabled={page <= 1} onClick={() => { setPage(page - 1); load(page - 1) }}>{t('prev')}</Button>
          <span>{page} / {totalPages}</span>
          <Button variant="outline" size="sm" disabled={page >= totalPages} onClick={() => { setPage(page + 1); load(page + 1) }}>{t('next')}</Button>
        </div>
      </div>

      {/* Add/Edit dialog */}
      <Dialog open={showForm} onOpenChange={(v) => { if (!v) setShowForm(false) }}>
        <DialogContent className="max-w-lg">
          <DialogHeader><DialogTitle>{editing ? t('edit') : t('add_device')}</DialogTitle></DialogHeader>
          <DeviceForm value={form} onChange={setForm} agents={[]} />
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowForm(false)}>{t('cancel')}</Button>
            <Button disabled={saving} onClick={handleSave}>{editing ? t('save') : t('add')}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* MCP tools dialog */}
      <Dialog open={showMcpDialog} onOpenChange={setShowMcpDialog}>
        <DialogContent className="max-w-2xl">
          <DialogHeader><DialogTitle>{t('device_mcp_tools')}</DialogTitle></DialogHeader>
          {mcpLoading ? (
            <div className="py-8 text-center text-sm text-[var(--color-text-secondary)]">{t('loading')}</div>
          ) : (
            <div className="grid gap-4">
              <div className="flex items-center justify-between">
                <div className="flex flex-wrap gap-1.5">
                  {mcpTools.length === 0 ? (
                    <span className="text-sm text-[var(--color-text-secondary)]">{t('no_tool_data')}</span>
                  ) : mcpTools.map((tool) => (
                    <span key={tool.name} className="inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium bg-[var(--color-surface-2)] text-[var(--color-text-secondary)] border-[var(--color-line)]">{tool.name}</span>
                  ))}
                </div>
                <Button size="sm" variant="outline" disabled={toolsLoading} onClick={refreshMcp}>{t('refresh')}</Button>
              </div>
              <div className="border-t border-[var(--color-line)]" />
              <div className="grid gap-3">
                <div className="grid gap-1.5">
                  <label className="text-sm font-semibold text-[var(--color-text)]">{t('tool_name')}</label>
                  <Select value={mcpToolName} onValueChange={setMcpToolName}>
                    <SelectTrigger><SelectValue placeholder={t('select_tool')} /></SelectTrigger>
                    <SelectContent>
                      {mcpTools.map((tool) => <SelectItem key={tool.name} value={tool.name}>{tool.name}</SelectItem>)}
                    </SelectContent>
                  </Select>
                </div>
                <div className="grid gap-1.5">
                  <label className="text-sm font-semibold text-[var(--color-text)]">{t('args_json_label')}</label>
                  <Textarea value={mcpToolArgs} onChange={(e) => setMcpToolArgs(e.target.value)} rows={6} placeholder={t('mcp_args_placeholder')} className="font-mono text-sm resize-y" />
                </div>
                <Button disabled={callingTool} onClick={callMcp}>{t('call_device_tool')}</Button>
              </div>
              <div className="border-t border-[var(--color-line)]" />
              <pre className="whitespace-pre-wrap font-mono text-xs bg-[var(--color-surface-2)] border border-[var(--color-line)] rounded-lg p-3 min-h-[80px] max-h-[200px] overflow-auto">
                {mcpCallResult || t('no_call_results')}
              </pre>
            </div>
          )}
        </DialogContent>
      </Dialog>

      <ConfirmDialog
        open={!!deleteTarget}
        onClose={() => setDeleteTarget(null)}
        onConfirm={handleDelete}
        isLoading={deleting}
        title={t('confirm_delete')}
        description={deleteTarget ? t('confirm_delete_device_msg', { name: getDeviceDisplayName(deleteTarget) }) : ''}
      />
    </div>
  )
}

export const Route = createFileRoute('/_auth/_layout/admin/devices')({
  component: AdminDevicesPage,
})
