// manager/frontend/src/views/admin/MCPConfig.vue
<template>
  <div class="mcp-config">
    <el-form ref="formRef" :model="form" :rules="rules" class="config-form" v-loading="loading">
      <div class="config-layout">
        <el-card class="config-card config-card-main" shadow="never">
          <template #header>
            <div class="card-head">
              <div>
                <p class="card-kicker">Global MCP</p>
                <h3>{{ t('global_mcp_service') }}</h3>
                <p class="card-description">{{ t('mcp_server_management_desc') }}</p>
              </div>
              <el-tag :type="form.mcp.global.enabled ? 'success' : 'info'" effect="plain" round>
                {{ form.mcp.global.enabled ? t('enabled_server_count', { count: enabledServerCount }) : t('global_mcp_disabled') }}
              </el-tag>
            </div>
          </template>

          <div class="field-grid field-grid-main">
            <el-form-item :label="t('enable_global_mcp')" prop="mcp.global.enabled">
              <div class="switch-field">
                <div>
                  <div class="switch-title">{{ t('allow_mcp_server_connection') }}</div>
                  <div class="field-help">{{ t('allow_mcp_close_help') }}</div>
                </div>
                <el-switch v-model="form.mcp.global.enabled" />
              </div>
            </el-form-item>

            <el-form-item :label="t('reconnect_interval_sec')" prop="mcp.global.reconnect_interval">
              <el-input-number
                v-model="form.mcp.global.reconnect_interval"
                :min="1"
                :max="3600"
                controls-position="right"
                style="width: 100%"
              />
            </el-form-item>

            <el-form-item :label="t('max_reconnect_attempts')" prop="mcp.global.max_reconnect_attempts">
              <el-input-number
                v-model="form.mcp.global.max_reconnect_attempts"
                :min="1"
                :max="100"
                controls-position="right"
                style="width: 100%"
              />
            </el-form-item>
          </div>

          <div class="server-list">
            <div class="server-list-header">
              <div>
                <h4>{{ t('mcp_server_list_title') }}</h4>
                
              </div>
              <el-button type="primary" @click="addGlobalServer">
                <el-icon><Plus /></el-icon>
                {{ t('add_server') }}
              </el-button>
            </div>

            <div v-if="form.mcp.global.servers.length === 0" class="empty-state">
              <strong>{{ t('mcp_no_servers_title') }}</strong>
              <p>{{ t('mcp_no_servers_hint') }}</p>
            </div>

            <div v-for="(server, index) in form.mcp.global.servers" :key="index" class="server-item">
              <div class="server-item-header">
                <div class="server-title-row">
                  <strong>{{ t('server_label_n', { n: index + 1 }) }}</strong>
                  <el-tag size="small" :type="server.enabled ? 'success' : 'info'" effect="plain" round>
                    {{ server.enabled ? t('enabled') : t('deactivated') }}
                  </el-tag>
                  <el-tag size="small" :type="server.allowed_tools?.length ? 'warning' : 'info'" effect="plain" round>
                    {{ server.allowed_tools?.length ? t('tools_count', { count: server.allowed_tools.length }) : t('all_tools') }}
                  </el-tag>
                </div>

                <div class="server-actions">
                  <el-button size="small" :loading="server._tools_loading" @click="discoverGlobalServerTools(server)">{{ t('probe_tools') }}</el-button>
                  <el-button size="small" type="danger" @click="removeGlobalServer(index)">
                    <el-icon><Delete /></el-icon>
                    {{ t('delete') }}
                  </el-button>
                </div>
              </div>

              <div class="field-grid server-grid">
                <el-form-item :label="t('server_name')" :prop="`mcp.global.servers.${index}.name`">
                  <el-input v-model="server.name" :placeholder="t('mcp_server_name_ph')" />
                </el-form-item>

                <el-form-item :label="t('server_type')" :prop="`mcp.global.servers.${index}.type`">
                  <el-select v-model="server.type" :placeholder="t('select_server_type')" style="width: 100%">
                    <el-option label="SSE" value="sse" />
                    <el-option label="StreamableHTTP" value="streamablehttp" />
                  </el-select>
                </el-form-item>

                <el-form-item :label="t('server_url')" :prop="`mcp.global.servers.${index}.url`" class="field-span-full">
                  <el-input v-model="server.url" :placeholder="t('mcp_server_url_ph')" />
                </el-form-item>

                <el-form-item :label="t('enabled_status')" :prop="`mcp.global.servers.${index}.enabled`">
                  <div class="switch-field">
                    <div>
                      <div class="switch-title">{{ t('allow_connect_server') }}</div>
                      <div class="field-help">{{ t('allow_connect_help') }}</div>
                    </div>
                    <el-switch v-model="server.enabled" />
                  </div>
                </el-form-item>
              </div>

              <el-form-item :label="t('allow_tools')" class="tool-form-item">
                <div class="tool-picker">
                  <div class="field-help">
                    {{ t('allowed_tools_hint') }}
                  </div>
                  <el-select
                    v-model="server.allowed_tools"
                    multiple
                    filterable
                    clearable
                    collapse-tags
                    collapse-tags-tooltip
                    style="width: 100%"
                    :placeholder="t('select_allowed_tools_ph')"
                    :loading="server._tools_loading"
                  >
                    <el-option v-for="tool in server._tool_options" :key="tool.name" :label="tool.name" :value="tool.name">
                      <div class="tool-option-row">
                        <span class="tool-option-name">{{ tool.name }}</span>
                        <span class="tool-option-desc">{{ tool.description || t('no_description') }}</span>
                      </div>
                    </el-option>
                  </el-select>
                </div>
              </el-form-item>
            </div>
          </div>
        </el-card>

        <el-card class="config-card config-card-side" shadow="never">
          <template #header>
            <div class="card-head">
              <div>
                <p class="card-kicker">Local MCP</p>
                <h3>{{ t('local_mcp_capabilities') }}</h3>
                <p class="card-description">{{ t('local_mcp_desc') }}</p>
              </div>
            </div>
          </template>

          <div class="field-stack">
            <el-form-item :label="t('exit_conversation')" prop="local_mcp.exit_conversation">
              <div class="switch-field">
                <div>
                  <div class="switch-title">{{ t('allow_model_end_session') }}</div>
                  <div class="field-help">{{ t('allow_model_end_help') }}</div>
                </div>
                <el-switch v-model="form.local_mcp.exit_conversation" />
              </div>
            </el-form-item>

            <el-form-item :label="t('clear_history')" prop="local_mcp.clear_conversation_history">
              <div class="switch-field">
                <div>
                  <div class="switch-title">{{ t('allow_model_clear_context') }}</div>
                  <div class="field-help">{{ t('allow_model_clear_help') }}</div>
                </div>
                <el-switch v-model="form.local_mcp.clear_conversation_history" />
              </div>
            </el-form-item>

            <el-form-item :label="t('play_music')" prop="local_mcp.play_music">
              <div class="switch-field">
                <div>
                  <div class="switch-title">{{ t('allow_model_play_music') }}</div>
                  <div class="field-help">{{ t('allow_model_play_help') }}</div>
                </div>
                <el-switch v-model="form.local_mcp.play_music" />
              </div>
            </el-form-item>
          </div>
        </el-card>
      </div>

      <div class="footer-bar">
        <p class="footer-note">
          {{ t('mcp_save_hint') }}
        </p>
        <div class="footer-actions">
          <el-button plain :loading="loading" @click="loadConfig">{{ t('reset_to_current') }}</el-button>
          <el-button type="primary" :loading="saving" @click="handleSave">{{ t('save_config') }}</el-button>
        </div>
      </div>
    </el-form>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { Plus, Delete } from '@element-plus/icons-vue'
import api from '@/utils/api'
import { useLocale } from '../../composables/useLocale'
const { t } = useLocale()

const loading = ref(false)
const saving = ref(false)
const configId = ref(null)
const formRef = ref()

const createDefaultState = () => ({
  mcp: {
    global: {
      enabled: true,
      servers: [],
      reconnect_interval: 300,
      max_reconnect_attempts: 10
    }
  },
  local_mcp: {
    exit_conversation: true,
    clear_conversation_history: true,
    play_music: false
  }
})

const form = reactive(createDefaultState())

const rules = {
  'mcp.global.reconnect_interval': [
    { required: true, message: t('enter_reconnect_interval'), trigger: 'blur' },
    { type: 'number', min: 1, max: 3600, message: t('reconnect_interval_range'), trigger: 'blur' }
  ],
  'mcp.global.max_reconnect_attempts': [
    { required: true, message: t('enter_max_reconnects'), trigger: 'blur' },
    { type: 'number', min: 1, max: 100, message: t('max_reconnect_range_error'), trigger: 'blur' }
  ]
}

const createGlobalServer = () => ({
  name: '',
  type: 'streamablehttp',
  url: '',
  enabled: true,
  allowed_tools: [],
  _tool_options: [],
  _tools_loading: false
})

const mergeServerToolOptions = (server, tools = []) => {
  const merged = new Map()

  ;(tools || []).forEach((tool) => {
    if (!tool?.name) return
    merged.set(tool.name, {
      name: tool.name,
      description: tool.description || ''
    })
  })

  ;(server.allowed_tools || []).forEach((name) => {
    if (!name || merged.has(name)) return
    merged.set(name, {
      name,
      description: t('currently_selected')
    })
  })

  server._tool_options = Array.from(merged.values()).sort((a, b) => a.name.localeCompare(b.name))
}

const normalizeGlobalServer = (server = {}) => {
  const normalized = {
    ...server,
    name: server.name || '',
    type: server.type || 'streamablehttp',
    url: server.url || '',
    enabled: server.enabled !== false,
    allowed_tools: Array.isArray(server.allowed_tools) ? [...server.allowed_tools] : [],
    _tool_options: [],
    _tools_loading: false
  }
  mergeServerToolOptions(normalized)
  return normalized
}

const enabledServerCount = computed(() => form.mcp.global.servers.filter(server => server.enabled).length)

const resetForm = () => {
  const defaults = createDefaultState()
  form.mcp.global.enabled = defaults.mcp.global.enabled
  form.mcp.global.reconnect_interval = defaults.mcp.global.reconnect_interval
  form.mcp.global.max_reconnect_attempts = defaults.mcp.global.max_reconnect_attempts
  form.mcp.global.servers = defaults.mcp.global.servers
  form.local_mcp.exit_conversation = defaults.local_mcp.exit_conversation
  form.local_mcp.clear_conversation_history = defaults.local_mcp.clear_conversation_history
  form.local_mcp.play_music = defaults.local_mcp.play_music
}

const addGlobalServer = () => {
  form.mcp.global.servers.push(createGlobalServer())
}

const removeGlobalServer = (index) => {
  form.mcp.global.servers.splice(index, 1)
}

const sanitizeGlobalServers = () => {
  return form.mcp.global.servers.map((server) => {
    const sanitized = { ...server }
    delete sanitized._tool_options
    delete sanitized._tools_loading
    return sanitized
  })
}

const generateConfig = () => {
  return JSON.stringify({
    mcp: {
      global: {
        ...form.mcp.global,
        servers: sanitizeGlobalServers()
      }
    },
    local_mcp: { ...form.local_mcp }
  })
}

const discoverGlobalServerTools = async (server) => {
  if (!server?.url) {
    ElMessage.warning(t('fill_server_url'))
    return
  }

  server._tools_loading = true
  try {
    const response = await api.post('/admin/mcp-configs/discover-tools', {
      transport: server.type,
      url: server.url,
      headers: server.headers || null
    })
    mergeServerToolOptions(server, response.data?.data?.tools || [])
    ElMessage.success(t('probing_tools_count', { count: server._tool_options.length }))
  } catch (error) {
    mergeServerToolOptions(server)
    ElMessage.error(error.response?.data?.error || t('probe_tools_failed'))
  } finally {
    server._tools_loading = false
  }
}

const loadConfig = async () => {
  loading.value = true
  try {
    const response = await api.get('/admin/mcp-configs')
    const configs = response.data?.data || []

    resetForm()

    if (configs.length > 0) {
      const config = configs.find(item => item.is_default) || configs[0]
      configId.value = config.id

      try {
        const configData = JSON.parse(config.json_data || '{}')
        if (configData.global && !configData.mcp) {
          form.mcp.global = {
            ...form.mcp.global,
            ...configData.global,
            servers: Array.isArray(configData.global?.servers)
              ? configData.global.servers.map(normalizeGlobalServer)
              : []
          }
        } else if (configData.mcp?.global) {
          form.mcp.global = {
            ...form.mcp.global,
            ...configData.mcp.global,
            servers: Array.isArray(configData.mcp.global?.servers)
              ? configData.mcp.global.servers.map(normalizeGlobalServer)
              : []
          }
        }

        if (configData.local_mcp) {
          Object.assign(form.local_mcp, configData.local_mcp)
        }
      } catch (error) {
        ElMessage.warning(t('mcp_config_format_error'))
      }
    } else {
      configId.value = null
    }
  } catch (error) {
    ElMessage.error(t('load_mcp_config_failed'))
  } finally {
    loading.value = false
  }
}

const handleSave = async () => {
  if (!formRef.value) return

  try {
    await formRef.value.validate()
  } catch {
    return
  }

  saving.value = true
  try {
    const payload = {
      name: t('mcp_global_config'),
      config_id: 'mcp_global_config',
      is_default: true,
      json_data: generateConfig()
    }

    if (configId.value) {
      await api.put(`/admin/mcp-configs/${configId.value}`, payload)
      ElMessage.success(t('mcp_config_updated'))
    } else {
      const response = await api.post('/admin/mcp-configs', payload)
      configId.value = response.data?.data?.id || configId.value
      ElMessage.success(t('mcp_config_saved'))
    }

    await loadConfig()
  } catch (error) {
    ElMessage.error(error.response?.data?.message || t('save_mcp_failed'))
  } finally {
    saving.value = false
  }
}

onMounted(() => {
  loadConfig()
})
</script>

<style scoped>
.mcp-config {
  padding: 0 24px 32px;
}

.config-form {
  display: grid;
  gap: 24px;
}

.config-layout {
  display: grid;
  grid-template-columns: minmax(0, 1.45fr) minmax(340px, 0.9fr);
  gap: 24px;
}

.config-card {
  border: 1px solid rgba(255, 255, 255, 0.88);
  background: rgba(255, 255, 255, 0.88);
  box-shadow: var(--apple-shadow-md);
}

.card-head {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 16px;
}

.card-kicker {
  display: block;
  margin: 0;
  font-size: 12px;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--apple-text-tertiary);
}

.card-head h3 {
  margin: 8px 0 0;
  font-size: 22px;
  line-height: 1.15;
  letter-spacing: -0.03em;
  color: var(--apple-text);
}

.card-description,
.field-help,
.footer-note,
.server-list-header p,
.empty-state p {
  margin: 8px 0 0;
  font-size: 13px;
  line-height: 1.7;
  color: var(--apple-text-secondary);
}

.field-grid {
  display: grid;
  gap: 20px 18px;
}

.field-grid-main {
  grid-template-columns: repeat(3, minmax(0, 1fr));
}

.field-stack {
  display: grid;
  gap: 20px;
}

.field-span-full {
  grid-column: 1 / -1;
}

.switch-field {
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto;
  gap: 8px 18px;
  align-items: center;
}

.switch-title {
  font-size: 15px;
  font-weight: 600;
  color: var(--apple-text);
}

.server-list {
  margin-top: 24px;
  padding-top: 24px;
  border-top: 1px solid rgba(229, 229, 234, 0.72);
}

.server-list-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 16px;
  margin-bottom: 18px;
}

.server-list-header h4,
.empty-state strong {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
  color: var(--apple-text);
}

.empty-state {
  padding: 18px;
  border-radius: 18px;
  border: 1px dashed rgba(229, 229, 234, 0.9);
  background: rgba(248, 250, 252, 0.72);
}

.server-item {
  padding: 18px;
  border-radius: 18px;
  border: 1px solid rgba(229, 229, 234, 0.88);
  background: rgba(248, 250, 252, 0.82);
}

.server-item + .server-item {
  margin-top: 16px;
}

.server-item-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 16px;
  margin-bottom: 18px;
}

.server-title-row,
.server-actions {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 8px;
}

.server-title-row strong {
  font-size: 15px;
  color: var(--apple-text);
}

.server-grid {
  grid-template-columns: repeat(2, minmax(0, 1fr));
}

.tool-form-item {
  margin-top: 16px;
}

.tool-picker {
  width: 100%;
}

.tool-option-row {
  display: flex;
  flex-direction: column;
  gap: 2px;
  line-height: 1.35;
}

.tool-option-name {
  color: var(--apple-text);
}

.tool-option-desc {
  color: var(--apple-text-secondary);
  font-size: 12px;
}

.footer-bar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 16px;
  padding: 0 4px;
}

.footer-note {
  max-width: 680px;
  margin: 0;
}

.footer-actions {
  display: flex;
  justify-content: flex-end;
  flex-wrap: wrap;
  gap: 12px;
}

:deep(.el-card__header) {
  padding: 24px 24px 0;
  border-bottom: none;
  background: transparent;
}

:deep(.el-card__body) {
  padding: 24px;
}

:deep(.el-form-item) {
  margin-bottom: 0;
}

:deep(.el-form-item__label) {
  font-size: 14px;
  font-weight: 600;
  color: var(--apple-text);
}

@media (max-width: 1180px) {
  .config-layout,
  .field-grid-main {
    grid-template-columns: 1fr;
  }
}

@media (max-width: 768px) {
  .mcp-config {
    padding: 0 16px 24px;
  }

  :deep(.el-card__body) {
    padding: 20px;
  }

  :deep(.el-card__header) {
    padding: 20px 20px 0;
  }

  .server-list-header,
  .server-item-header,
  .footer-bar {
    flex-direction: column;
    align-items: stretch;
  }

  .server-grid {
    grid-template-columns: 1fr;
  }

  .footer-actions {
    justify-content: stretch;
  }

  .footer-actions :deep(.el-button) {
    flex: 1;
  }
}
</style>

// manager/frontend/src/routes/_auth/_layout/admin/mcp-config.tsx
import { useEffect, useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { Plus, Trash2, Search } from 'lucide-react'
import { toast } from 'sonner'
import api from '@/utils/api'
import { useLocale } from '@/hooks/use-locale'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Switch } from '@/components/ui/switch'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { PageHeader } from '@/components/ui/page-header'
import { cn } from '@/lib/utils'

interface McpServer {
  name: string; type: string; url: string; enabled: boolean
  allowed_tools: string[]; _tool_options: string[]; _tools_loading: boolean
}

interface McpForm {
  mcp: { global: { enabled: boolean; reconnect_interval: number; max_reconnect_attempts: number; servers: McpServer[] } }
  local_mcp: { exit_conversation: boolean; clear_conversation_history: boolean; play_music: boolean }
}

const newServer = (): McpServer => ({ name: '', type: 'streamablehttp', url: '', enabled: true, allowed_tools: [], _tool_options: [], _tools_loading: false })

const defaults: McpForm = { mcp: { global: { enabled: true, servers: [], reconnect_interval: 300, max_reconnect_attempts: 10 } }, local_mcp: { exit_conversation: true, clear_conversation_history: true, play_music: false } }

function McpConfigPage() {
  const { t } = useLocale()
  const [loading, setLoading] = useState(false)
  const [saving, setSaving] = useState(false)
  const [configId, setConfigId] = useState<number | null>(null)
  const [form, setForm] = useState<McpForm>(defaults)

  const setGlobal = (patch: Partial<typeof defaults.mcp.global>) => setForm((f) => ({ ...f, mcp: { ...f.mcp, global: { ...f.mcp.global, ...patch } } }))
  const setLocal = (patch: Partial<typeof defaults.local_mcp>) => setForm((f) => ({ ...f, local_mcp: { ...f.local_mcp, ...patch } }))
  const setServer = (i: number, patch: Partial<McpServer>) => setForm((f) => { const servers = [...f.mcp.global.servers]; servers[i] = { ...servers[i], ...patch }; return { ...f, mcp: { ...f.mcp, global: { ...f.mcp.global, servers } } } })

  const load = async () => {
    setLoading(true)
    try {
      const res = await api.get('/admin/mcp-configs')
      const configs = res.data?.data || []
      if (configs.length > 0) {
        const c = configs.find((x: { is_default: boolean }) => x.is_default) || configs[0]
        setConfigId(c.id)
        const d = JSON.parse(c.json_data || '{}')
        const globalData = d.mcp?.global || d.global || {}
        setForm({
          mcp: { global: { enabled: globalData.enabled !== false, reconnect_interval: Number(globalData.reconnect_interval) || 300, max_reconnect_attempts: Number(globalData.max_reconnect_attempts) || 10, servers: (globalData.servers || []).map((s: McpServer) => ({ ...s, allowed_tools: s.allowed_tools || [], _tool_options: [], _tools_loading: false })) } },
          local_mcp: { exit_conversation: d.local_mcp?.exit_conversation !== false, clear_conversation_history: d.local_mcp?.clear_conversation_history !== false, play_music: !!d.local_mcp?.play_music }
        })
      } else { setConfigId(null); setForm(defaults) }
    } catch { toast.error(t('load_mcp_config_failed')) }
    finally { setLoading(false) }
  }

  useEffect(() => { load() }, []) // eslint-disable-line react-hooks/exhaustive-deps

  const handleSave = async () => {
    setSaving(true)
    try {
      const cleanServers = form.mcp.global.servers.map(({ _tool_options: _to, _tools_loading: _tl, ...s }) => s)
      const json_data = JSON.stringify({ mcp: { global: { ...form.mcp.global, servers: cleanServers } }, local_mcp: form.local_mcp })
      const payload = { name: t('mcp_global_config'), config_id: 'mcp_global_config', is_default: true, json_data }
      if (configId) { await api.put(`/admin/mcp-configs/${configId}`, payload); toast.success(t('mcp_config_updated')) }
      else { const r = await api.post('/admin/mcp-configs', payload); setConfigId(r.data?.data?.id || null); toast.success(t('mcp_config_saved')) }
      await load()
    } catch (e) { toast.error((e as Error).message || t('save_mcp_failed')) }
    finally { setSaving(false) }
  }

  const discoverTools = async (i: number) => {
    const s = form.mcp.global.servers[i]
    if (!s.url) { toast.warning(t('fill_server_url')); return }
    setServer(i, { _tools_loading: true })
    try {
      const res = await api.post('/admin/mcp-configs/discover-tools', { transport: s.type, url: s.url })
      const tools = (res.data?.data?.tools || []).map((t: { name: string }) => t.name)
      setServer(i, { _tool_options: tools, _tools_loading: false })
      toast.success(t('probing_tools_count', { count: tools.length }))
    } catch (e) { setServer(i, { _tools_loading: false }); toast.error((e as Error).message || t('probe_tools_failed')) }
  }

  const toggleTool = (i: number, tool: string) => {
    const s = form.mcp.global.servers[i]
    const tools = s.allowed_tools.includes(tool) ? s.allowed_tools.filter((t) => t !== tool) : [...s.allowed_tools, tool]
    setServer(i, { allowed_tools: tools })
  }

  const addServer = () => setForm((f) => ({ ...f, mcp: { ...f.mcp, global: { ...f.mcp.global, servers: [...f.mcp.global.servers, newServer()] } } }))
  const removeServer = (i: number) => setForm((f) => { const servers = f.mcp.global.servers.filter((_, idx) => idx !== i); return { ...f, mcp: { ...f.mcp, global: { ...f.mcp.global, servers } } } })

  if (loading) return <div className="p-6 text-center text-sm text-[var(--color-text-secondary)]">{t('loading')}</div>

  return (
    <div className="grid gap-6 px-6 pb-8">
      <PageHeader title="MCP Config" />

      {/* Global settings */}
      <div className="rounded-xl border border-[var(--color-line)] bg-[var(--color-surface-1)] p-6 grid gap-5 max-w-[640px]">
        <p className="text-xs font-bold tracking-widest uppercase text-[var(--color-text-tertiary)]">{t('mcp_global_config')}</p>
        <div className="flex items-center justify-between gap-4">
          <p className="text-sm font-semibold text-[var(--color-text)]">{t('enabled_status')}</p>
          <Switch checked={form.mcp.global.enabled} onCheckedChange={(v) => setGlobal({ enabled: v })} />
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="grid gap-1.5">
            <label className="text-sm font-semibold text-[var(--color-text)]">{t('reconnect_interval_s')}</label>
            <Input type="number" value={form.mcp.global.reconnect_interval} onChange={(e) => setGlobal({ reconnect_interval: Number(e.target.value) })} min={1} max={3600} />
          </div>
          <div className="grid gap-1.5">
            <label className="text-sm font-semibold text-[var(--color-text)]">{t('max_reconnect_attempts')}</label>
            <Input type="number" value={form.mcp.global.max_reconnect_attempts} onChange={(e) => setGlobal({ max_reconnect_attempts: Number(e.target.value) })} min={1} max={100} />
          </div>
        </div>
      </div>

      {/* Server list */}
      <div className="grid gap-3">
        <div className="flex items-center justify-between">
          <p className="text-sm font-semibold text-[var(--color-text)]">{t('mcp_servers')} ({form.mcp.global.servers.length})</p>
          <Button size="sm" onClick={addServer}><Plus className="w-4 h-4 mr-1.5" />{t('add_server')}</Button>
        </div>
        {form.mcp.global.servers.map((server, i) => (
          <div key={i} className="rounded-xl border border-[var(--color-line)] bg-[var(--color-surface-1)] p-5 grid gap-4">
            <div className="flex items-center gap-3 flex-wrap">
              <Input className="flex-1 min-w-[160px]" placeholder={t('server_name')} value={server.name} onChange={(e) => setServer(i, { name: e.target.value })} />
              <Select value={server.type} onValueChange={(v) => setServer(i, { type: v })}>
                <SelectTrigger className="w-40"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="streamablehttp">Streamable HTTP</SelectItem>
                  <SelectItem value="sse">SSE</SelectItem>
                  <SelectItem value="stdio">Stdio</SelectItem>
                </SelectContent>
              </Select>
              <div className="flex items-center gap-1.5">
                <Switch checked={server.enabled} onCheckedChange={(v) => setServer(i, { enabled: v })} />
                <span className="text-xs text-[var(--color-text-secondary)]">{t('enabled_status')}</span>
              </div>
              <Button variant="ghost" size="icon" className="text-destructive h-8 w-8" onClick={() => removeServer(i)}><Trash2 className="w-4 h-4" /></Button>
            </div>
            <div className="flex gap-2">
              <Input className="flex-1" placeholder="URL" value={server.url} onChange={(e) => setServer(i, { url: e.target.value })} />
              <Button size="sm" variant="outline" disabled={server._tools_loading} onClick={() => discoverTools(i)}>
                <Search className="w-4 h-4 mr-1.5" />{server._tools_loading ? '...' : t('discover_tools')}
              </Button>
            </div>
            {server._tool_options.length > 0 && (
              <div className="flex flex-wrap gap-1.5">
                {server._tool_options.map((tool) => (
                  <button key={tool} type="button" onClick={() => toggleTool(i, tool)} className={cn('text-xs px-2 py-1 rounded-full border transition-colors', server.allowed_tools.includes(tool) ? 'bg-[var(--color-primary)] text-white border-[var(--color-primary)]' : 'border-[var(--color-line)] text-[var(--color-text-secondary)] hover:border-[var(--color-primary)]')}>
                    {tool}
                  </button>
                ))}
              </div>
            )}
            {server.allowed_tools.length > 0 && (
              <p className="text-xs text-[var(--color-text-secondary)]">{t('allowed_tools')}: {server.allowed_tools.join(', ')}</p>
            )}
          </div>
        ))}
      </div>

      {/* Local MCP */}
      <div className="rounded-xl border border-[var(--color-line)] bg-[var(--color-surface-1)] p-6 grid gap-4 max-w-[640px]">
        <p className="text-xs font-bold tracking-widest uppercase text-[var(--color-text-tertiary)]">{t('local_mcp')}</p>
        {[
          { key: 'exit_conversation' as const, label: t('mcp_exit_conversation') },
          { key: 'clear_conversation_history' as const, label: t('mcp_clear_history') },
          { key: 'play_music' as const, label: t('mcp_play_music') },
        ].map(({ key, label }) => (
          <div key={key} className="flex items-center justify-between gap-4">
            <p className="text-sm font-semibold text-[var(--color-text)]">{label}</p>
            <Switch checked={form.local_mcp[key]} onCheckedChange={(v) => setLocal({ [key]: v })} />
          </div>
        ))}
      </div>

      <div className="flex items-center justify-end gap-3">
        <Button variant="outline" disabled={loading} onClick={load}>{t('reset_to_current')}</Button>
        <Button disabled={saving} onClick={handleSave}>{t('save_config')}</Button>
      </div>
    </div>
  )
}

export const Route = createFileRoute('/_auth/_layout/admin/mcp-config')({
  component: McpConfigPage,
})
