// manager/frontend/src/views/admin/PoolStats.vue
<template>
  <div class="pool-stats">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>{{ t('resource_pool_stats') }}</span>
          <div class="header-actions">
            <el-button type="primary" size="small" @click="refreshStats">
              <el-icon><Refresh /></el-icon>
              {{ t('refresh') }}
            </el-button>
            <el-select v-model="viewType" size="small" style="width: 120px; margin-left: 10px;" disabled>
              <el-option :label="t('latest_data')" value="latest" />
            </el-select>
          </div>
        </div>
      </template>

      <!-- 统计摘要 -->
      <el-row :gutter="20" style="margin-bottom: 20px;">
        <el-col :span="6">
          <el-statistic :title="t('total_records')" :value="summary.total_records || 0" />
        </el-col>
        <el-col :span="6">
          <div class="stat-item">
            <div class="stat-title">{{ t('storage_mode') }}</div>
            <div class="stat-value">{{ t('latest_only') }}</div>
          </div>
        </el-col>
        <el-col :span="6">
          <div class="stat-item">
            <div class="stat-title">{{ t('earliest_time') }}</div>
            <div class="stat-value">{{ formatTime(summary.oldest_timestamp) }}</div>
          </div>
        </el-col>
        <el-col :span="6">
          <div class="stat-item">
            <div class="stat-title">{{ t('latest_time') }}</div>
            <div class="stat-value">{{ formatTime(summary.newest_timestamp) }}</div>
          </div>
        </el-col>
      </el-row>

      <!-- 最新统计数据 -->
      <div v-if="viewType === 'latest' && latestStats">
        <el-divider>{{ t('latest_stats_title', { time: formatTime(latestStats.timestamp) }) }}</el-divider>
        <el-table :data="formatStatsData(latestStats.stats)" border stripe style="width: 100%" v-if="latestStats.stats">
          <el-table-column prop="poolKey" :label="t('pool_key_col')" width="200" />
          <el-table-column prop="total" :label="t('total_resources')" width="120" />
          <el-table-column prop="available" :label="t('available_resources')" width="120" />
          <el-table-column prop="inUse" :label="t('in_use')" width="120" />
          <el-table-column prop="maxSize" :label="t('max_capacity')" width="120" />
          <el-table-column prop="minSize" :label="t('min_capacity')" width="120" />
          <el-table-column prop="maxIdle" :label="t('max_idle')" width="120" />
          <el-table-column prop="isClosed" :label="t('status')" width="100">
            <template #default="{ row }">
              <el-tag :type="row.isClosed ? 'danger' : 'success'">
                {{ row.isClosed ? t('closed') : t('running') }}
              </el-tag>
            </template>
          </el-table-column>
        </el-table>
      </div>

      <!-- 空状态 -->
      <el-empty v-if="!latestStats" :description="t('no_statistics')" />
    </el-card>
  </div>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'
import api from '@/utils/api'
import { ElMessage } from 'element-plus'
import { Refresh } from '@element-plus/icons-vue'
import { useLocale } from '../../composables/useLocale'
const { t } = useLocale()

const viewType = ref('latest')
const latestStats = ref(null)
const summary = ref({
  total_records: 0,
  storage_duration: t('save_latest_only'),
  oldest_timestamp: null,
  newest_timestamp: null
})

let refreshTimer = null

onMounted(() => {
  loadSummary()
  loadStats()
  // 每30秒自动刷新
  refreshTimer = setInterval(() => {
    loadStats()
  }, 30000)
})

onUnmounted(() => {
  if (refreshTimer) {
    clearInterval(refreshTimer)
  }
})

// 加载统计摘要
const loadSummary = async () => {
  try {
    const response = await api.get('/admin/pool/stats/summary')
    // 后端返回格式: { data: { data: {...} } }
    summary.value = response.data?.data || {}
  } catch (error) {
    console.error(t('load_stats_summary_failed'), error)
  }
}

// 加载统计数据
const loadStats = async () => {
  try {
    const response = await api.get('/admin/pool/stats?type=latest')
    console.log(t('latest_stats_response'), response)
    // 后端返回格式: { data: { timestamp: "...", stats: {...} } }
    // axios 会自动解析，所以 response.data 就是后端返回的 { data: {...} }
    // 需要再取一层 data
    latestStats.value = response.data?.data || response.data || null
    console.log(t('parsed_latest_data'), latestStats.value)
  } catch (error) {
    console.error(t('load_stats_failed_v2'), error)
    ElMessage.error(t('load_stats_failed'))
  }
}

// 刷新统计数据
const refreshStats = () => {
  loadSummary()
  loadStats()
  ElMessage.success(t('refresh_success'))
}

// 格式化统计数据
const formatStatsData = (stats) => {
  if (!stats || typeof stats !== 'object') {
    return []
  }

  const result = []
  for (const [poolKey, poolStats] of Object.entries(stats)) {
    if (poolStats && typeof poolStats === 'object') {
      result.push({
        poolKey,
        total: poolStats.total_resources || 0,
        available: poolStats.available_resources || 0,
        inUse: poolStats.in_use_resources || 0,
        maxSize: poolStats.max_size || 0,
        minSize: poolStats.min_size || 0,
        maxIdle: poolStats.max_idle || 0,
        isClosed: poolStats.is_closed || false
      })
    }
  }
  return result
}

// 格式化时间
const formatTime = (timestamp) => {
  if (!timestamp) {
    return '-'
  }
  const date = new Date(timestamp)
  return date.toLocaleString('zh-CN', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit'
  })
}

</script>

<style scoped>
.pool-stats {
  padding: 20px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.header-actions {
  display: flex;
  align-items: center;
}

.el-statistic {
  text-align: center;
}

.el-timeline {
  padding-left: 20px;
}

.stat-item {
  text-align: center;
  padding: 10px;
}

.stat-title {
  font-size: 14px;
  color: #909399;
  margin-bottom: 8px;
}

.stat-value {
  font-size: 24px;
  font-weight: bold;
  color: #303133;
}
</style>

// manager/frontend/src/routes/_auth/_layout/admin/pool-stats.tsx
import { Suspense, useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { useSuspenseQuery, useQueryClient } from '@tanstack/react-query'
import { RefreshCw } from 'lucide-react'
import { toast } from 'sonner'
import type { ColumnDef } from '@tanstack/react-table'
import { dashboardApi } from '@/features/dashboard/api/dashboard-api'
import type { PoolStatEntry, PoolStatsData, PoolSummary } from '@/features/dashboard/types'
import { useLocale } from '@/hooks/use-locale'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { DataTable } from '@/components/ui/data-table'
import { PageHeader } from '@/components/ui/page-header'
import { Skeleton } from '@/components/ui/skeleton'

function formatTime(ts: string | null): string {
  if (!ts) return '—'
  return new Date(ts).toLocaleString()
}

function PoolSummaryCards({ summary }: { summary: PoolSummary }) {
  const { t } = useLocale()
  return (
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
      {[
        { value: summary.total_records || 0, label: t('total_records'), large: true },
        { value: t('latest_only'), label: t('storage_mode'), large: true },
        { value: formatTime(summary.oldest_timestamp), label: t('earliest_time'), large: false },
        { value: formatTime(summary.newest_timestamp), label: t('latest_time'), large: false },
      ].map((item) => (
        <div key={item.label} className="text-center p-4 rounded-xl bg-[var(--color-surface-1)] border border-[var(--color-line)]">
          <div className={item.large ? 'text-2xl font-bold text-[var(--color-text)]' : 'text-sm font-semibold text-[var(--color-text)] break-all'}>
            {String(item.value)}
          </div>
          <div className="text-sm text-[var(--color-text-secondary)] mt-1">{item.label}</div>
        </div>
      ))}
    </div>
  )
}

function PoolStatsContent() {
  const { t } = useLocale()
  const queryClient = useQueryClient()
  const [refreshing, setRefreshing] = useState(false)

  const { data: stats } = useSuspenseQuery<PoolStatsData | null>({
    queryKey: ['pool-stats'],
    queryFn: dashboardApi.getPoolStats,
    staleTime: 25_000,
    refetchInterval: 30_000,
  })

  const { data: summary } = useSuspenseQuery<PoolSummary>({
    queryKey: ['pool-summary'],
    queryFn: dashboardApi.getPoolSummary,
    staleTime: 25_000,
  })

  const tableData: PoolStatEntry[] = stats?.stats
    ? Object.entries(stats.stats)
        .filter(([, v]) => v && typeof v === 'object')
        .map(([poolKey, s]) => ({
          poolKey,
          total: s.total_resources || 0,
          available: s.available_resources || 0,
          inUse: s.in_use_resources || 0,
          maxSize: s.max_size || 0,
          minSize: s.min_size || 0,
          maxIdle: s.max_idle || 0,
          isClosed: s.is_closed || false,
        }))
    : []

  const columns: ColumnDef<PoolStatEntry>[] = [
    { accessorKey: 'poolKey', header: t('pool_key_col') },
    { accessorKey: 'total', header: t('total_resources') },
    { accessorKey: 'available', header: t('available_resources') },
    { accessorKey: 'inUse', header: t('in_use') },
    { accessorKey: 'maxSize', header: t('max_capacity') },
    { accessorKey: 'minSize', header: t('min_capacity') },
    { accessorKey: 'maxIdle', header: t('max_idle') },
    {
      accessorKey: 'isClosed',
      header: t('status'),
      cell: ({ row }) => (
        <Badge variant={row.original.isClosed ? 'destructive' : 'secondary'}>
          {row.original.isClosed ? t('closed') : t('running')}
        </Badge>
      ),
    },
  ]

  const handleRefresh = async () => {
    setRefreshing(true)
    await Promise.all([
      queryClient.invalidateQueries({ queryKey: ['pool-stats'] }),
      queryClient.invalidateQueries({ queryKey: ['pool-summary'] }),
    ])
    setRefreshing(false)
    toast.success(t('refresh_success'))
  }

  return (
    <Card>
      <CardHeader className="flex-row items-center justify-between pb-4">
        <h3 className="text-lg font-semibold text-[var(--color-text)]">{t('resource_pool_stats')}</h3>
        <Button variant="outline" size="sm" disabled={refreshing} onClick={handleRefresh}>
          <RefreshCw className={`w-4 h-4 mr-1.5 ${refreshing ? 'animate-spin' : ''}`} />
          {t('refresh')}
        </Button>
      </CardHeader>
      <CardContent className="space-y-6">
        <PoolSummaryCards summary={summary} />
        {stats ? (
          <div className="border-t border-[var(--color-line)] pt-4">
            <p className="text-xs text-[var(--color-text-secondary)] mb-4">
              {t('latest_stats_title', { time: formatTime(stats.timestamp) })}
            </p>
            <DataTable data={tableData} columns={columns} emptyMessage={t('no_statistics')} />
          </div>
        ) : (
          <div className="py-12 text-center text-[var(--color-text-secondary)]">{t('no_statistics')}</div>
        )}
      </CardContent>
    </Card>
  )
}

function PoolStatsSkeleton() {
  return (
    <Card>
      <CardHeader className="flex-row items-center justify-between pb-4">
        <Skeleton className="h-6 w-48" />
        <Skeleton className="h-8 w-24" />
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {Array.from({ length: 4 }).map((_, i) => <Skeleton key={i} className="h-20 rounded-xl" />)}
        </div>
        <Skeleton className="h-48 w-full" />
      </CardContent>
    </Card>
  )
}

function PoolStatsPage() {
  const { t } = useLocale()
  return (
    <div className="p-6 grid gap-5">
      <PageHeader eyebrow="ADMIN" title={t('resource_pool_stats')} />
      <Suspense fallback={<PoolStatsSkeleton />}>
        <PoolStatsContent />
      </Suspense>
    </div>
  )
}

export const Route = createFileRoute('/_auth/_layout/admin/pool-stats')({
  component: PoolStatsPage,
})
