// manager/frontend/src/routes/_auth/_layout/dashboard.tsx
import { Suspense, useRef, useState } from 'react'
import { createFileRoute, useRouter } from '@tanstack/react-router'
import { useSuspenseQuery } from '@tanstack/react-query'
import { User, Monitor, Cpu, Wifi, Wand2, Download, Upload, Settings } from 'lucide-react'
import { SectionLabel } from '@/components/ui/section-label'
import { toast } from 'sonner'
import { dashboardApi } from '@/features/dashboard/api/dashboard-api'
import type { DashboardStats } from '@/features/dashboard/types'
import { DashboardServiceCard } from '@/components/dashboard/dashboard-service-card'
import { useAuthStore } from '@/stores/auth'
import { useLocale } from '@/hooks/use-locale'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import { cn } from '@/lib/utils'

// ---- sub-components ----

function StatCard({ icon: Icon, iconClass, trend, value, label }: {
  icon: React.ElementType; iconClass: string; trend: string; value: number; label: string
}) {
  return (
    <div
      className="relative p-5 rounded-2xl border border-[var(--color-line)] overflow-hidden group transition-all duration-200 hover:-translate-y-0.5 hover:shadow-[var(--shadow-card-hover)]"
      style={{
        background: 'linear-gradient(145deg, var(--color-surface-1) 0%, var(--color-bg) 100%)',
        boxShadow: 'var(--shadow-card)',
      }}
    >
      {/* Ambient glow blob */}
      <div
        className="absolute -right-4 -top-4 w-24 h-24 rounded-full blur-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300"
        style={{ background: 'var(--color-primary-soft)' }}
      />
      <div className="relative">
        <div className="flex items-center justify-between mb-4">
          <span className={cn('w-10 h-10 rounded-lg inline-flex items-center justify-center', iconClass)}>
            <Icon className="w-5 h-5" />
          </span>
          <span className="text-[10px] font-bold tracking-widest uppercase text-[var(--color-text-tertiary)] font-mono">{trend}</span>
        </div>
        <strong className="block text-4xl font-bold font-display tracking-tight leading-none text-[var(--color-text)]">{value}</strong>
        <p className="mt-2.5 text-sm text-[var(--color-text-secondary)]">{label}</p>
      </div>
    </div>
  )
}

function ConfigActionRow({ icon: Icon, title, desc, highlighted, onClick }: {
  icon: React.ElementType; title: string; desc: string; highlighted?: boolean; onClick: () => void
}) {
  return (
    <button type="button" onClick={onClick}
      className={cn('flex items-center gap-3.5 w-full p-4 rounded-xl border cursor-pointer hover:-translate-y-px hover:shadow-[var(--shadow-card-hover)] active:scale-[0.98] transition-all duration-150 text-left',
        highlighted
          ? 'border-[var(--color-primary)]/20 bg-[var(--color-primary-soft)]'
          : 'border-[var(--color-line)] bg-[var(--color-surface-1)] shadow-[var(--shadow-card)]')}>
      <span className="w-10 h-10 rounded-xl inline-flex items-center justify-center bg-[var(--color-primary-soft)] text-[var(--color-primary)] shrink-0">
        <Icon className="w-5 h-5" />
      </span>
      <span className="flex flex-col gap-0.5">
        <strong className="text-[15px] text-[var(--color-text)]">{title}</strong>
        <small className="text-sm text-[var(--color-text-secondary)]">{desc}</small>
      </span>
    </button>
  )
}

// ---- data section (Suspense boundary) ----

function DashboardInner() {
  const { t } = useLocale()
  const router = useRouter()
  const { user, isAdmin, token } = useAuthStore()
  const fileInputRef = useRef<HTMLInputElement>(null)
  const [importing, setImporting] = useState(false)

  const { data: stats } = useSuspenseQuery<DashboardStats>({
    queryKey: ['dashboard-stats'],
    queryFn: dashboardApi.getStats,
    staleTime: 30_000,
  })

  const programStartedAt = stats.programStartedAt
    ? new Date(stats.programStartedAt).toLocaleString()
    : '—'

  const metricCards = [
    { icon: User, iconClass: 'text-[var(--color-primary)] bg-[var(--color-primary-soft)]', trend: isAdmin ? t('global_user') : t('linked_account'), value: isAdmin ? stats.totalUsers : 1, label: isAdmin ? t('total_users') : t('current_logged_account') },
    { icon: Monitor, iconClass: 'text-[var(--color-success)] bg-[color-mix(in_srgb,var(--color-success)_12%,transparent)]', trend: t('online_devices'), value: stats.totalDevices, label: isAdmin ? t('total_devices') : t('my_devices') },
    { icon: Cpu, iconClass: 'text-[var(--color-warning)] bg-[color-mix(in_srgb,var(--color-warning)_12%,transparent)]', trend: t('active'), value: stats.totalAgents, label: isAdmin ? t('agent_count') : t('my_agents') },
    { icon: Wifi, iconClass: 'text-[var(--color-danger)] bg-[color-mix(in_srgb,var(--color-danger)_12%,transparent)]', trend: t('realtime_monitoring'), value: stats.onlineDevices, label: t('online_devices') },
  ]

  const adminQuickActions = [
    { icon: User, label: t('user_management'), desc: t('view_account_desc'), route: '/admin/users' },
    { icon: Settings, label: t('llm_config'), desc: t('llm_config_desc'), route: '/admin/llm-config' },
    { icon: Cpu, label: t('vad_config'), desc: t('vad_config_desc'), route: '/admin/vad-config' },
  ]

  const handleExport = async () => {
    try { await dashboardApi.exportConfig(token ?? ''); toast.success(t('config_export_success')) }
    catch { toast.error(t('config_export_failed')) }
  }

  const handleImport = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]; if (!file) return
    const ext = file.name.toLowerCase().slice(file.name.lastIndexOf('.'))
    if (!['.yaml', '.yml', '.json'].includes(ext)) { toast.error(t('select_yaml_or_json')); return }
    setImporting(true)
    try { await dashboardApi.importConfig(token ?? '', file); toast.success(t('config_import_success')) }
    catch (err) { toast.error((err as Error).message || t('config_import_failed')) }
    finally { setImporting(false); e.target.value = '' }
  }

  return (
    <div className="grid gap-4 px-6 py-4">
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {metricCards.map((m) => <StatCard key={m.label} {...m} />)}
      </div>

      <div className="flex flex-col xl:flex-row gap-4 items-start">
        <div className="flex-1 min-w-0 grid gap-4">
          {isAdmin && <DashboardServiceCard />}
          {isAdmin && (
            <Card className="border-[var(--color-line)]">
              <CardHeader className="pb-3">
                <SectionLabel className="mb-1">CONFIGURATION</SectionLabel>
                <h3 className="text-lg font-semibold text-[var(--color-text)]">{t('config_management')}</h3>
              </CardHeader>
              <CardContent className="grid gap-3">
                <ConfigActionRow icon={Wand2} title={t('config_wizard')} desc={t('from_wizard_desc')} highlighted onClick={() => router.navigate({ to: '/admin/config-wizard' })} />
                <ConfigActionRow icon={Download} title={t('export_config_title')} desc={t('export_config_desc')} onClick={handleExport} />
                <ConfigActionRow icon={Upload} title={t('import_config_title')} desc={t('import_config_desc')} onClick={() => fileInputRef.current?.click()} />
                <input ref={fileInputRef} type="file" accept=".yaml,.yml,.json" className="hidden" onChange={handleImport} disabled={importing} />
              </CardContent>
            </Card>
          )}
        </div>

        <div className="w-full xl:w-[360px] xl:shrink-0 grid gap-3 min-w-0">
          <Card>
            <CardHeader className="p-4 pb-2">
              <SectionLabel>SYSTEM</SectionLabel>
              <h3 className="text-base font-semibold text-[var(--color-text)]">{t('system_info')}</h3>
            </CardHeader>
            <CardContent className="px-4 pb-4 pt-0">
              <dl className="divide-y divide-[var(--color-line)]">
                {[
                  { label: t('system_version'), value: 'v1.0.0' },
                  { label: t('program_start_time'), value: programStartedAt },
                  { label: t('current_user_label'), value: user?.username || '—' },
                ].map((row) => (
                  <div key={row.label} className="flex items-center justify-between gap-3 py-2">
                    <dt className="text-sm text-[var(--color-text-secondary)]">{row.label}</dt>
                    <dd className="text-sm font-semibold text-[var(--color-text)]">{row.value}</dd>
                  </div>
                ))}
                <div className="flex items-center justify-between gap-3 py-2">
                  <dt className="text-sm text-[var(--color-text-secondary)]">{t('user_role_label')}</dt>
                  <dd><Badge variant={isAdmin ? 'destructive' : 'secondary'}>{isAdmin ? t('admin') : t('normal_user')}</Badge></dd>
                </div>
              </dl>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="p-4 pb-2">
              <SectionLabel>SHORTCUTS</SectionLabel>
              <h3 className="text-base font-semibold text-[var(--color-text)]">{t('quick_actions')}</h3>
            </CardHeader>
            <CardContent className="px-4 pb-4 pt-0 grid gap-2">
              {isAdmin ? adminQuickActions.map((qa) => (
                <button key={qa.route} type="button" onClick={() => router.navigate({ to: qa.route as never })}
                  className="flex items-center gap-3 w-full p-2.5 rounded-xl border border-[var(--color-line)] bg-[var(--color-surface-1)] shadow-[var(--shadow-card)] cursor-pointer hover:-translate-y-px hover:shadow-[var(--shadow-card-hover)] active:scale-[0.98] transition-all duration-150 text-left">
                  <span className="w-9 h-9 rounded-xl inline-flex items-center justify-center bg-[var(--color-primary-soft)] text-[var(--color-primary)] shrink-0"><qa.icon className="w-4 h-4" /></span>
                  <span className="flex flex-col gap-0.5 min-w-0">
                    <strong className="text-sm text-[var(--color-text)]">{qa.label}</strong>
                    <small className="text-xs text-[var(--color-text-secondary)] truncate">{qa.desc}</small>
                  </span>
                </button>
              )) : (
                <>
                  <button type="button" onClick={() => router.navigate({ to: '/agents' })}
                    className="flex items-center gap-3 w-full p-2.5 rounded-xl border border-[var(--color-line)] bg-[var(--color-surface-1)] shadow-[var(--shadow-card)] cursor-pointer hover:-translate-y-px hover:shadow-[var(--shadow-card-hover)] active:scale-[0.98] transition-all duration-150 text-left">
                    <span className="w-9 h-9 rounded-xl inline-flex items-center justify-center bg-[var(--color-primary-soft)] text-[var(--color-primary)] shrink-0"><Monitor className="w-4 h-4" /></span>
                    <span className="flex flex-col gap-0.5"><strong className="text-sm text-[var(--color-text)]">{t('agent_management')}</strong><small className="text-xs text-[var(--color-text-secondary)]">{t('agent_mgmt_desc')}</small></span>
                  </button>
                  <p className="text-sm text-[var(--color-text-secondary)]">{t('normal_user_quick_hint')}</p>
                </>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

function DashboardSkeleton() {
  return (
    <div className="grid gap-5 p-6">
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{Array.from({ length: 4 }).map((_, i) => <Skeleton key={i} className="h-32 rounded-xl" />)}</div>
    </div>
  )
}

function DashboardPage() {
  return (
    <Suspense fallback={<DashboardSkeleton />}>
      <DashboardInner />
    </Suspense>
  )
}

export const Route = createFileRoute('/_auth/_layout/dashboard')({
  component: DashboardPage,
})

// manager/frontend/src/views/Dashboard.vue
<template>
  <div class="dashboard-page">
    <section class="stats-grid">
      <article class="metric-card">
        <div class="metric-top">
          <span class="metric-icon users">
            <el-icon><User /></el-icon>
          </span>
          <span class="metric-trend">{{ authStore.isAdmin ? t('global_user') : t('linked_account') }}</span>
        </div>
        <strong>{{ authStore.isAdmin ? stats.totalUsers : 1 }}</strong>
        <p>{{ authStore.isAdmin ? t('total_users') : t('current_logged_account') }}</p>
      </article>

      <article class="metric-card">
        <div class="metric-top">
          <span class="metric-icon devices">
            <el-icon><Monitor /></el-icon>
          </span>
          <span class="metric-trend">{{ t('online_count', { count: stats.onlineDevices }) }}</span>
        </div>
        <strong>{{ stats.totalDevices }}</strong>
        <p>{{ authStore.isAdmin ? t('total_devices') : t('my_devices') }}</p>
      </article>

      <article class="metric-card">
        <div class="metric-top">
          <span class="metric-icon agents">
            <el-icon><Cpu /></el-icon>
          </span>
          <span class="metric-trend">{{ t('active') }}</span>
        </div>
        <strong>{{ stats.totalAgents }}</strong>
        <p>{{ authStore.isAdmin ? t('agent_count') : t('my_agents') }}</p>
      </article>

      <article class="metric-card">
        <div class="metric-top">
          <span class="metric-icon status">
            <el-icon><Connection /></el-icon>
          </span>
          <span class="metric-trend">{{ t('realtime_monitoring') }}</span>
        </div>
        <strong>{{ stats.onlineDevices }}</strong>
        <p>{{ t('online_devices') }}</p>
      </article>
    </section>

    <section class="dashboard-grid" :class="{ compact: !authStore.isAdmin }">
      <div class="dashboard-main">
        <el-card v-if="authStore.isAdmin" class="dashboard-card service-card">
          <template #header>
            <div class="card-header">
              <div>
                <p class="card-eyebrow">SERVICE ADDRESS</p>
                <h3>{{ t('service_address') }}</h3>
              </div>
              <el-button type="warning" size="small" :loading="otaTestLoading" @click="runOtaTest">
                {{ t('ota_test') }}</el-button>
            </div>
          </template>

          <div v-loading="addressLoading" class="address-card-content">
            <template v-if="!addressLoading && (serviceAddress.otaUrl || serviceAddress.wsUrl)">
              <div class="address-list">
                <div class="address-row">
                  <span class="address-label">OTA</span>
                  <span class="address-value" :title="serviceAddress.otaUrl">{{ serviceAddress.otaUrl || '—' }}</span>
                  <el-button v-if="serviceAddress.otaUrl" link type="primary" :icon="CopyDocument" @click="copyAddress(serviceAddress.otaUrl)" />
                </div>
                <div class="address-row">
                  <span class="address-label">WS</span>
                  <span class="address-value" :title="serviceAddress.wsUrl">{{ serviceAddress.wsUrl || '—' }}</span>
                  <el-button v-if="serviceAddress.wsUrl" link type="primary" :icon="CopyDocument" @click="copyAddress(serviceAddress.wsUrl)" />
                </div>
                <div v-if="serviceAddress.mqttEndpoint" class="address-row">
                  <span class="address-label">MQTT</span>
                  <span class="address-value" :title="serviceAddress.mqttEndpoint">{{ serviceAddress.mqttEndpoint }}</span>
                  <el-button link type="primary" :icon="CopyDocument" @click="copyAddress(serviceAddress.mqttEndpoint)" />
                </div>
                <div v-if="serviceAddress.udpAddress" class="address-row">
                  <span class="address-label">UDP</span>
                  <span class="address-value" :title="serviceAddress.udpAddress">{{ serviceAddress.udpAddress }}</span>
                  <el-button link type="primary" :icon="CopyDocument" @click="copyAddress(serviceAddress.udpAddress)" />
                </div>
              </div>

              <div v-if="otaTestResult !== null" class="ota-test-block">
                <span class="apple-chip is-primary">{{ t('ota_return_chip') }}</span>
                <pre class="ota-test-pre">{{ otaTestResult }}</pre>
              </div>
            </template>

            <div v-else-if="!addressLoading" class="empty-inline">{{ t('no_ota_config') }}</div>
          </div>
        </el-card>

        <el-card v-if="authStore.isAdmin" class="dashboard-card">
          <template #header>
            <div class="card-header">
              <div>
                <p class="card-eyebrow">CONFIGURATION</p>
                <h3>{{ t('config_management') }}</h3>
              </div>
            </div>
          </template>

          <div class="config-actions">
            <button class="action-card action-primary" type="button" @click="$router.push('/admin/config-wizard')">
              <span class="action-icon"><el-icon><Guide /></el-icon></span>
              <span class="action-copy">
                <strong>{{ t('config_wizard') }}</strong>
                <small>{{ t('from_wizard_desc') }}</small>
              </span>
            </button>

            <button class="action-card" type="button" @click="exportConfig">
              <span class="action-icon"><el-icon><Download /></el-icon></span>
              <span class="action-copy">
                <strong>{{ t('export_config_title') }}</strong>
                <small>{{ t('export_config_desc') }}</small>
              </span>
            </button>

            <button class="action-card" type="button" @click="importConfig">
              <span class="action-icon"><el-icon><Upload /></el-icon></span>
              <span class="action-copy">
                <strong>{{ t('import_config_title') }}</strong>
                <small>{{ t('import_config_desc') }}</small>
              </span>
            </button>
          </div>

          <input
            ref="fileInput"
            type="file"
            accept=".yaml,.yml,.json"
            style="display: none"
            @change="handleFileChange"
          />
        </el-card>
      </div>

      <div class="dashboard-side">
        <el-card class="dashboard-card info-card">
          <template #header>
            <div class="card-header">
              <div>
                <p class="card-eyebrow">SYSTEM</p>
                <h3>{{ t('system_info') }}</h3>
              </div>
            </div>
          </template>

          <div class="info-list">
            <div class="info-row">
              <span>{{ t('system_version') }}</span>
              <strong>v1.0.0</strong>
            </div>
            <div class="info-row">
              <span>{{ t('program_start_time') }}</span>
              <strong>{{ programStartedAt }}</strong>
            </div>
            <div class="info-row">
              <span>{{ t('current_user_label') }}</span>
              <strong>{{ authStore.user?.username || '—' }}</strong>
            </div>
            <div class="info-row">
              <span>{{ t('user_role_label') }}</span>
              <el-tag :type="authStore.isAdmin ? 'danger' : 'primary'" effect="light">
                {{ authStore.isAdmin ? t('admin') : t('normal_user') }}
              </el-tag>
            </div>
          </div>
        </el-card>

        <el-card class="dashboard-card quick-card">
          <template #header>
            <div class="card-header">
              <div>
                <p class="card-eyebrow">SHORTCUTS</p>
                <h3>{{ t('quick_actions') }}</h3>
              </div>
            </div>
          </template>

          <div class="quick-actions">
            <template v-if="authStore.isAdmin">
              <button class="quick-action" type="button" @click="$router.push('/admin/users')">
                <span class="quick-action-icon"><el-icon><User /></el-icon></span>
                <span>
                  <strong>{{ t('user_management') }}</strong>
                  <small>{{ t('view_account_desc') }}</small>
                </span>
              </button>
              <button class="quick-action" type="button" @click="$router.push('/admin/llm-config')">
                <span class="quick-action-icon"><el-icon><Setting /></el-icon></span>
                <span>
                  <strong>{{ t('llm_config') }}</strong>
                  <small>{{ t('llm_config_desc') }}</small>
                </span>
              </button>
              <button class="quick-action" type="button" @click="$router.push('/admin/vad-config')">
                <span class="quick-action-icon"><el-icon><Cpu /></el-icon></span>
                <span>
                  <strong>{{ t('vad_config') }}</strong>
                  <small>{{ t('vad_config_desc') }}</small>
                </span>
              </button>
            </template>

            <template v-else>
              <button class="quick-action" type="button" @click="$router.push('/agents')">
                <span class="quick-action-icon"><el-icon><Monitor /></el-icon></span>
                <span>
                  <strong>{{ t('agent_management') }}</strong>
                  <small>{{ t('agent_mgmt_desc') }}</small>
                </span>
              </button>
              <div class="empty-inline">{{ t('normal_user_quick_hint') }}</div>
            </template>
          </div>
        </el-card>
      </div>
    </section>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useAuthStore } from '@/stores/auth'
import api from '@/utils/api'
import { ElMessage } from 'element-plus'
import {
  User,
  Monitor,
  Connection,
  Setting,
  Download,
  Upload,
  Cpu,
  Guide,
  CopyDocument
} from '@element-plus/icons-vue'
import { useLocale } from '../composables/useLocale'
const { t } = useLocale()

const authStore = useAuthStore()

const addressLoading = ref(false)
const serviceAddress = ref({
  otaUrl: '',
  wsUrl: '',
  mqttEndpoint: '',
  udpAddress: ''
})

async function loadServiceAddress() {
  addressLoading.value = true
  serviceAddress.value = { otaUrl: '', wsUrl: '', mqttEndpoint: '', udpAddress: '' }
  try {
    const [otaRes, udpRes] = await Promise.all([
      api.get('/admin/ota-configs'),
      api.get('/admin/udp-configs')
    ])
    const otaList = otaRes.data?.data || []
    const config = otaList.find(c => c.is_default) || otaList[0]
    if (config?.json_data) {
      const data = JSON.parse(config.json_data || '{}')

      let envData = data.external || {}
      const hasExternalWs = envData.websocket?.url
      const hasExternalOta = envData.ota_url
      if (!hasExternalWs && !hasExternalOta) {
        envData = data.test || {}
      }

      let otaUrl = envData.ota_url || ''
      if (!otaUrl) {
        const wsUrl = envData.websocket?.url || ''
        if (wsUrl) {
          const matched = wsUrl.match(/^(wss?):\/\/([^:/]+)(?::(\d+))?/)
          if (matched) {
            const protocol = matched[1] === 'wss' ? 'https' : 'http'
            const port = matched[3] || (matched[1] === 'wss' ? '443' : '80')
            otaUrl = `${protocol}://${matched[2]}:${port}/xiaozhi/ota/`
          }
        }
      }
      serviceAddress.value.otaUrl = otaUrl
      serviceAddress.value.wsUrl = envData.websocket?.url || ''

      const mqttEnabled = envData.mqtt?.enable
      const endpoint = envData.mqtt?.endpoint || ''
      if (mqttEnabled && endpoint) {
        serviceAddress.value.mqttEndpoint = endpoint
      }
    }

    const udpList = udpRes.data?.data || []
    const udpConfig = udpList.find(c => c.is_default) || udpList[0]
    if (udpConfig?.json_data) {
      const udpData = JSON.parse(udpConfig.json_data || '{}')
      const host = udpData.external_host || ''
      const port = udpData.external_port
      if (host && port != null) {
        serviceAddress.value.udpAddress = `${host}:${port}`
      }
    }
  } catch (err) {
    console.error(t('load_service_addr_failed'), err)
  } finally {
    addressLoading.value = false
  }
}

function copyAddress(text) {
  if (!text) return
  navigator.clipboard.writeText(text).then(() => {
    ElMessage.success(t('copied_to_clipboard'))
  }).catch(() => {
    ElMessage.error(t('copy_failed'))
  })
}

const otaTestLoading = ref(false)
const otaTestResult = ref(null)

function formatOtaResponseDisplay(str) {
  if (str == null || str === '') return ''
  const content = String(str).trim()
  if (!content) return ''
  try {
    return JSON.stringify(JSON.parse(content), null, 2)
  } catch {
    return content
  }
}

async function runOtaTest() {
  otaTestLoading.value = true
  otaTestResult.value = null
  try {
    const res = await api.post('/admin/configs/test', { types: ['ota'] }, { timeout: 30000 })
    const data = res.data?.data ?? res.data
    const ota = data?.ota
    if (ota && typeof ota === 'object') {
      const entry = Object.entries(ota).find(([key]) => !key.startsWith('_'))
      if (entry) {
        const [, value] = entry
        let displayText = ''

        if (value.websocket) {
          const ws = value.websocket
          displayText += `WebSocket: ${ws.ok ? '✓' : '✗'} ${ws.message}`
          displayText += ws.first_packet_ms != null ? ` (${ws.first_packet_ms}ms)\n` : '\n'
        }

        if (value.mqtt_udp) {
          const mqtt = value.mqtt_udp
          displayText += `MQTT UDP: ${mqtt.ok ? '✓' : '✗'} ${mqtt.message}`
          displayText += mqtt.first_packet_ms != null ? ` (${mqtt.first_packet_ms}ms)\n` : '\n'
        }

        if (value.ota_response !== undefined && value.ota_response !== '') {
          displayText += `\n--- ${t('ota_return_label')} ---\n${formatOtaResponseDisplay(value.ota_response)}`
        }

        otaTestResult.value = displayText.trim() || t('detail_not_available')
        ElMessage[value.ok ? 'success' : 'warning'](value.message || (value.ok ? t('ota_test_passed') : t('ota_test_failed')))
      } else {
        otaTestResult.value = t('ota_test_no_result')
      }
    } else {
      otaTestResult.value = typeof data === 'string' ? data : JSON.stringify(data || {}, null, 2)
    }
  } catch (error) {
    const errorMsg = (error.response?.data && typeof error.response.data === 'object')
      ? JSON.stringify(error.response.data, null, 2)
      : (error.response?.data?.message || error.message || t('request_failed'))
    otaTestResult.value = errorMsg
    ElMessage.error(t('ota_test_request_failed'))
  } finally {
    otaTestLoading.value = false
  }
}

const stats = ref({
  totalUsers: 0,
  totalDevices: 0,
  totalAgents: 0,
  onlineDevices: 0
})

const programStartedAt = ref('—')
const fileInput = ref(null)

onMounted(async () => {
  await loadStats()
  if (authStore.isAdmin) {
    loadServiceAddress()
  }
})

const loadStats = async () => {
  try {
    const response = await api.get('/dashboard/stats')
    stats.value = {
      totalUsers: response.data.totalUsers || 0,
      totalDevices: response.data.totalDevices || 0,
      totalAgents: response.data.totalAgents || 0,
      onlineDevices: response.data.onlineDevices || 0
    }
    programStartedAt.value = response.data?.programStartedAt
      ? new Date(response.data.programStartedAt).toLocaleString('zh-CN')
      : '—'
  } catch (error) {
    console.error(t('load_stats_failed_v2'), error)
    stats.value = {
      totalUsers: 0,
      totalDevices: 0,
      totalAgents: 0,
      onlineDevices: 0
    }
    programStartedAt.value = '—'
  }
}

const exportConfig = async () => {
  try {
    const response = await fetch('/api/admin/configs/export', {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${authStore.token}`
      }
    })

    if (response.ok) {
      const blob = await response.blob()
      const url = window.URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = 'config.yaml'
      document.body.appendChild(link)
      link.click()
      window.URL.revokeObjectURL(url)
      document.body.removeChild(link)
      ElMessage.success(t('config_export_success'))
    } else {
      ElMessage.error(t('config_export_failed'))
    }
  } catch (error) {
    console.error(t('export_config_failed'), error)
    ElMessage.error(t('config_export_failed'))
  }
}

const importConfig = () => {
  fileInput.value.click()
}

const handleFileChange = async (event) => {
  const file = event.target.files[0]
  if (!file) return

  const validExtensions = ['.yaml', '.yml', '.json']
  const fileExtension = file.name.toLowerCase().substring(file.name.lastIndexOf('.'))

  if (!validExtensions.includes(fileExtension)) {
    ElMessage.error(t('select_yaml_or_json'))
    return
  }

  const formData = new FormData()
  formData.append('file', file)

  try {
    const response = await fetch('/api/admin/configs/import', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${authStore.token}`
      },
      body: formData
    })

    if (response.ok) {
      ElMessage.success(t('config_import_success'))
    } else {
      const error = await response.json()
      ElMessage.error(error.error || t('config_import_failed'))
    }
  } catch (error) {
    console.error(t('import_config_failed'), error)
    ElMessage.error(t('config_import_failed'))
  }

  event.target.value = ''
}
</script>

<style scoped>
.dashboard-page {
  display: grid;
  gap: 20px;
}
.card-eyebrow {
  margin: 0;
  color: var(--apple-text-tertiary);
  font-size: 11px;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 16px;
}

.metric-card {
  padding: 22px;
  border-radius: 24px;
  background: rgba(255, 255, 255, 0.88);
  border: 1px solid rgba(255, 255, 255, 0.88);
  box-shadow: var(--apple-shadow-md);
}

.metric-top {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 12px;
  margin-bottom: 18px;
}

.metric-icon {
  width: 42px;
  height: 42px;
  border-radius: 16px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  font-size: 18px;
}

.metric-icon.users {
  color: var(--apple-primary);
  background: var(--apple-primary-soft);
}

.metric-icon.devices {
  color: #176a31;
  background: var(--apple-success-soft);
}

.metric-icon.agents {
  color: #875f00;
  background: var(--apple-warning-soft);
}

.metric-icon.status {
  color: #8a1f19;
  background: var(--apple-danger-soft);
}

.metric-trend {
  color: var(--apple-text-secondary);
  font-size: 12px;
  font-weight: 600;
}

.metric-card strong {
  display: block;
  font-size: 34px;
  line-height: 1;
  letter-spacing: -0.05em;
}

.metric-card p {
  margin: 10px 0 0;
  color: var(--apple-text-secondary);
  font-size: 14px;
}

.dashboard-grid {
  display: grid;
  grid-template-columns: minmax(0, 1.3fr) minmax(320px, 0.9fr);
  gap: 18px;
}

.dashboard-grid.compact {
  grid-template-columns: 1fr 360px;
}

.dashboard-main,
.dashboard-side {
  display: grid;
  gap: 18px;
}

.dashboard-card :deep(.el-card__header) {
  padding-bottom: 18px;
}

.card-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 16px;
}

.card-header h3 {
  margin: 4px 0 0;
  font-size: 18px;
}

.address-card-content {
  display: grid;
  gap: 16px;
}

.address-list {
  display: grid;
  gap: 12px;
}

.address-row {
  display: grid;
  grid-template-columns: 64px minmax(0, 1fr) auto;
  align-items: center;
  gap: 10px;
  padding: 14px 16px;
  border-radius: 18px;
  background: rgba(248, 250, 252, 0.86);
  border: 1px solid rgba(229, 229, 234, 0.76);
}

.address-label {
  color: var(--apple-text-tertiary);
  font-size: 12px;
  font-weight: 700;
  letter-spacing: 0.08em;
}

.address-value {
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  color: var(--apple-text);
  font-weight: 500;
}

.ota-test-block {
  display: grid;
  gap: 10px;
}

.ota-test-pre {
  margin: 0;
  padding: 16px;
  border-radius: 18px;
  background: #f7f9fc;
  border: 1px solid rgba(229, 229, 234, 0.72);
  color: #445064;
  font-size: 12px;
  line-height: 1.6;
  white-space: pre-wrap;
  word-break: break-word;
  max-height: 180px;
  overflow: auto;
}

.config-actions,
.quick-actions {
  display: grid;
  gap: 12px;
}

.action-card,
.quick-action {
  width: 100%;
  padding: 16px;
  border: 1px solid rgba(229, 229, 234, 0.76);
  border-radius: 20px;
  background: rgba(255, 255, 255, 0.9);
  display: flex;
  align-items: center;
  gap: 14px;
  text-align: left;
  cursor: pointer;
  color: inherit;
}

.action-card:hover,
.quick-action:hover {
  transform: translateY(-1px);
  box-shadow: var(--apple-shadow-sm);
  border-color: rgba(0, 122, 255, 0.18);
}

.action-primary {
  background: linear-gradient(180deg, rgba(0, 122, 255, 0.12) 0%, rgba(0, 122, 255, 0.06) 100%);
}

.action-icon,
.quick-action-icon {
  width: 42px;
  height: 42px;
  border-radius: 16px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  background: rgba(0, 122, 255, 0.1);
  color: var(--apple-primary);
  font-size: 18px;
  flex: none;
}

.action-copy,
.quick-action span:last-child {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.action-copy strong,
.quick-action strong {
  font-size: 15px;
}

.action-copy small,
.quick-action small {
  color: var(--apple-text-secondary);
  font-size: 13px;
  line-height: 1.6;
}

.info-list {
  display: grid;
  gap: 12px;
}

.info-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 14px 0;
  border-bottom: 1px solid rgba(229, 229, 234, 0.72);
}

.info-row:last-child {
  border-bottom: 0;
  padding-bottom: 0;
}

.info-row span {
  color: var(--apple-text-secondary);
  font-size: 14px;
}

.info-row strong {
  color: var(--apple-text);
  font-size: 14px;
}

.empty-inline {
  color: var(--apple-text-secondary);
  font-size: 13px;
  line-height: 1.7;
}

@media (max-width: 1280px) {
  .dashboard-grid,
  .dashboard-grid.compact {
    grid-template-columns: 1fr;
  }

  .stats-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}

@media (max-width: 768px) {
  .stats-grid {
    grid-template-columns: 1fr;
  }

  .address-row {
    grid-template-columns: 1fr;
    align-items: flex-start;
  }
}
</style>
