// manager/frontend/src/routes/login.tsx
import { useState, useEffect } from 'react'
import { createFileRoute, useRouter } from '@tanstack/react-router'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { Loader2 } from 'lucide-react'
import { toast } from 'sonner'
import appLogo from '@/assets/brand/app-logo.webp'
import { useAuthStore } from '@/stores/auth'
import { useLocale } from '@/hooks/use-locale'
import { useCaptcha } from '@/hooks/use-captcha'
import { getPostLoginRedirectPath } from '@/utils/auth-redirect'
import api from '@/utils/api'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form'

function CaptchaBlock({ captcha, onRefresh }: { captcha: ReturnType<typeof useCaptcha>; onRefresh: () => void }) {
  const { t } = useLocale()
  return (
    <>
      <div className="flex items-center justify-between gap-4 p-3 rounded-lg border border-[var(--color-line)] bg-[var(--color-surface-2)]">
        <div className="min-w-0">
          <span className="text-[11px] font-semibold text-[var(--color-text-secondary)] block mb-1">{t('captcha')}</span>
          <strong className="text-lg tracking-tight text-[var(--color-text)] block">{captcha.prompt || t('generating_questions')}</strong>
          <p className="text-[13px] text-[var(--color-text-secondary)] mt-1 leading-relaxed">{t('arithmetic_captcha_hint')}</p>
        </div>
        <Button type="button" variant="ghost" size="sm" disabled={captcha.loading} onClick={onRefresh}>{t('refresh_captcha')}</Button>
      </div>
      <div>
        <label className="text-sm font-medium text-[var(--color-text)] block mb-1.5">{t('calc_result')}</label>
        <Input inputMode="numeric" value={captcha.answer} onChange={(e) => captcha.setAnswer(e.target.value)} placeholder={t('enter_calc_result')} />
      </div>
    </>
  )
}

function LoginPage() {
  const { t } = useLocale()
  const router = useRouter()
  const { login, register, user, isAdmin } = useAuthStore()
  const [loading, setLoading] = useState(false)
  const [captchaEnabled, setCaptchaEnabled] = useState(true)
  const loginCaptcha = useCaptcha()
  const registerCaptcha = useCaptcha()

  const loginSchema = z.object({
    username: z.string().min(1, t('enter_username')),
    password: z.string().min(1, t('enter_password')),
  })
  const registerSchema = z.object({
    username: z.string().min(1, t('enter_username')),
    email: z.string().min(1, t('enter_email')).email(t('enter_valid_email')),
    password: z.string().min(6, t('password_min_length')),
    confirmPassword: z.string().min(1, t('confirm_password_prompt')),
  }).refine((d) => d.password === d.confirmPassword, { message: t('password_mismatch'), path: ['confirmPassword'] })

  const loginForm = useForm<z.infer<typeof loginSchema>>({ resolver: zodResolver(loginSchema) })
  const registerForm = useForm<z.infer<typeof registerSchema>>({ resolver: zodResolver(registerSchema) })

  useEffect(() => {
    if (user) { router.navigate({ to: getPostLoginRedirectPath(isAdmin ? 'admin' : 'user') as '/' }); return }
    const init = async () => {
      try {
        const { data } = await api.get<{ enabled: boolean }>('/captcha/status')
        setCaptchaEnabled(data?.enabled !== false)
      } catch { /* default true */ }
    }
    init().then(() => {
      if (captchaEnabled) loginCaptcha.fetch()
      else loginCaptcha.clear()
      registerCaptcha.fetch()
    })
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  const handleLogin = loginForm.handleSubmit(async (values) => {
    if (captchaEnabled && !loginCaptcha.id) { toast.error(t('captcha_load_failed')); await loginCaptcha.fetch(); return }
    setLoading(true)
    const result = await login({
      username: values.username, password: values.password,
      ...(captchaEnabled && { captchaId: loginCaptcha.id, captchaAnswer: loginCaptcha.answer.trim() }),
    })
    setLoading(false)
    if (result.success) {
      toast.success(t('login_success'))
      localStorage.setItem('admin_first_login_done', '1')
      router.navigate({ to: getPostLoginRedirectPath(result.user?.role ?? '') as '/' })
    } else {
      toast.error(result.message)
      if (captchaEnabled) await loginCaptcha.fetch()
    }
  })

  const handleRegister = registerForm.handleSubmit(async (values) => {
    if (!registerCaptcha.id) { toast.error(t('captcha_load_failed')); await registerCaptcha.fetch(); return }
    setLoading(true)
    const result = await register({
      username: values.username, email: values.email, password: values.password,
      captchaId: registerCaptcha.id, captchaAnswer: registerCaptcha.answer.trim(),
    })
    setLoading(false)
    if (result.success) {
      toast.success(t('register_success_login'))
      registerForm.reset()
      await registerCaptcha.fetch()
      if (captchaEnabled) await loginCaptcha.fetch()
    } else {
      toast.error(result.message)
      await registerCaptcha.fetch()
    }
  })

  return (
    <div className="min-h-screen flex items-center justify-center bg-[var(--color-bg)] p-6">
      <div className="w-full max-w-5xl grid lg:grid-cols-[1fr_420px] gap-6 items-center">
        <section className="hidden lg:block px-4 py-6">
          <div className="inline-flex items-center gap-3 mb-6 px-3 py-2 rounded-2xl bg-[var(--color-surface-1)] border border-[var(--color-line)]">
            <img src={appLogo} alt={t('xiaozhi_management_system')} className="w-14 h-14 rounded-xl object-cover" />
            <div>
              <strong className="block text-[var(--color-text)] text-lg leading-snug">{t('xiaozhi_management_system')}</strong>
              <span className="block text-[var(--color-text-secondary)] text-[13px] mt-0.5">{t('ai_platform_title')}</span>
            </div>
          </div>
          <p className="text-[11px] font-bold tracking-widest text-[var(--color-primary)] uppercase mb-2">XIAOZHI CONTROL CENTER</p>
          <h1 className="text-5xl font-bold font-display tracking-tight leading-tight text-[var(--color-text)] mb-4">{t('xiaozhi_tagline')}</h1>
          <p className="text-[var(--color-text-secondary)] leading-relaxed max-w-lg">{t('platform_desc')}</p>
          <div className="flex flex-wrap gap-2 mt-5">
            <Badge>{t('agent_orchestration')}</Badge>
            {[t('device_access'), t('voiceprint_knowledge'), 'MCP / OpenClaw', t('mcp_remote_call'), t('proactive_voice_push')].map((b) => (
              <Badge key={b} variant="outline">{b}</Badge>
            ))}
          </div>
        </section>

        <Card className="w-full">
          <CardHeader className="pb-2">
            <p className="text-[11px] font-bold tracking-widest text-[var(--color-primary)] uppercase mb-1">WELCOME BACK</p>
            <h2 className="text-2xl font-bold font-display tracking-tight text-[var(--color-text)]">{t('login_or_create')}</h2>
          </CardHeader>
          <CardContent>
            <Tabs defaultValue="login" className="mt-2">
              <TabsList className="w-full">
                <TabsTrigger value="login" className="flex-1">{t('login')}</TabsTrigger>
                <TabsTrigger value="register" className="flex-1">{t('register')}</TabsTrigger>
              </TabsList>
              <TabsContent value="login">
                <Form {...loginForm}>
                  <form onSubmit={handleLogin} className="space-y-4 mt-4">
                    <FormField control={loginForm.control} name="username" render={({ field }) => (
                      <FormItem><FormLabel>{t('username')}</FormLabel><FormControl><Input {...field} placeholder={t('enter_username')} /></FormControl><FormMessage /></FormItem>
                    )} />
                    <FormField control={loginForm.control} name="password" render={({ field }) => (
                      <FormItem><FormLabel>{t('password')}</FormLabel><FormControl><Input {...field} type="password" autoComplete="current-password" placeholder={t('enter_password')} /></FormControl><FormMessage /></FormItem>
                    )} />
                    {captchaEnabled && <CaptchaBlock captcha={loginCaptcha} onRefresh={loginCaptcha.fetch} />}
                    <Button type="submit" className="w-full" disabled={loading || (captchaEnabled && (loginCaptcha.loading || !loginCaptcha.id))}>
                      {loading && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}{t('login')}
                    </Button>
                  </form>
                </Form>
              </TabsContent>
              <TabsContent value="register">
                <Form {...registerForm}>
                  <form onSubmit={handleRegister} className="space-y-4 mt-4">
                    <FormField control={registerForm.control} name="username" render={({ field }) => (
                      <FormItem><FormLabel>{t('username')}</FormLabel><FormControl><Input {...field} placeholder={t('enter_username')} /></FormControl><FormMessage /></FormItem>
                    )} />
                    <FormField control={registerForm.control} name="email" render={({ field }) => (
                      <FormItem><FormLabel>{t('email')}</FormLabel><FormControl><Input {...field} type="email" autoComplete="email" placeholder={t('enter_email')} /></FormControl><FormMessage /></FormItem>
                    )} />
                    <FormField control={registerForm.control} name="password" render={({ field }) => (
                      <FormItem><FormLabel>{t('password')}</FormLabel><FormControl><Input {...field} type="password" autoComplete="new-password" placeholder={t('enter_password_min6')} /></FormControl><FormMessage /></FormItem>
                    )} />
                    <FormField control={registerForm.control} name="confirmPassword" render={({ field }) => (
                      <FormItem><FormLabel>{t('confirm_password')}</FormLabel><FormControl><Input {...field} type="password" autoComplete="new-password" placeholder={t('confirm_password_prompt')} /></FormControl><FormMessage /></FormItem>
                    )} />
                    <CaptchaBlock captcha={registerCaptcha} onRefresh={registerCaptcha.fetch} />
                    <Button type="submit" className="w-full" disabled={loading || registerCaptcha.loading || !registerCaptcha.id}>
                      {loading && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}{t('register')}
                    </Button>
                  </form>
                </Form>
              </TabsContent>
            </Tabs>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

export const Route = createFileRoute('/login')({
  component: LoginPage,
})

// manager/frontend/src/views/Login.vue
<template>
  <div class="login-container">
    <div class="login-shell">
      <section class="login-hero">
        <div class="login-brand">
          <img class="login-brand-logo" :src="appLogo" :alt="t('xiaozhi_management_system')" />
          <div>
            <strong>{{ t('xiaozhi_management_system') }}</strong>
            <span>{{ t('ai_platform_title') }}</span>
          </div>
        </div>
        <p class="login-eyebrow">XIAOZHI CONTROL CENTER</p>
        <h1>{{ t('xiaozhi_tagline') }}</h1>
        <p>
          {{ t('platform_desc') }}</p>
        <div class="login-meta">
          <span class="apple-chip is-primary">{{ t('agent_orchestration') }}</span>
          <span class="apple-chip">{{ t('device_access') }}</span>
          <span class="apple-chip">{{ t('voiceprint_knowledge') }}</span>
          <span class="apple-chip">MCP / OpenClaw</span>
          <span class="apple-chip">{{ t('mcp_remote_call') }}</span>
          <span class="apple-chip">{{ t('proactive_voice_push') }}</span>
        </div>
      </section>

      <el-card class="login-card">
        <template #header>
          <div class="card-header">
            <div>
              <p class="card-eyebrow">WELCOME BACK</p>
              <h2>{{ t('login_or_create') }}</h2>
            </div>
          </div>
        </template>

        <el-tabs v-model="activeTab" class="login-tabs">
          <el-tab-pane :label="t('login')" name="login">
            <el-form
              ref="loginFormRef"
              :model="loginForm"
              :rules="loginRules"
              label-position="top"
            >
              <el-form-item :label="t('username')" prop="username">
                <el-input v-model="loginForm.username" :placeholder="t('enter_username')" />
              </el-form-item>
              <el-form-item :label="t('password')" prop="password">
                <el-input
                  v-model="loginForm.password"
                  type="password"
                  :placeholder="t('enter_password')"
                  @keyup.enter="handleLogin"
                />
              </el-form-item>
              <div v-if="loginCaptchaEnabled" class="captcha-strip">
                <div class="captcha-copy">
                  <span class="captcha-label">{{ t('captcha') }}</span>
                  <strong>{{ loginCaptchaPrompt || t('generating_questions') }}</strong>
                  <p>{{ t('arithmetic_captcha_hint') }}</p>
                </div>
                <el-button
                  link
                  type="primary"
                  :loading="loginCaptchaLoading"
                  @click="refreshLoginCaptcha"
                >
                  {{ t('refresh_captcha') }}
                </el-button>
              </div>
              <el-form-item v-if="loginCaptchaEnabled" :label="t('calc_result')" prop="captchaAnswer">
                <el-input
                  v-model="loginForm.captchaAnswer"
                  inputmode="numeric"
                  :placeholder="t('enter_calc_result')"
                  @keyup.enter="handleLogin"
                />
              </el-form-item>
              <el-form-item>
                <el-button
                  type="primary"
                  :loading="loading"
                  :disabled="loginCaptchaEnabled && (loginCaptchaLoading || !loginForm.captchaId)"
                  @click="handleLogin"
                  style="width: 100%"
                >
                  {{ t('login') }}
                </el-button>
              </el-form-item>
            </el-form>
          </el-tab-pane>

          <el-tab-pane :label="t('register')" name="register">
            <el-form
              ref="registerFormRef"
              :model="registerForm"
              :rules="registerRules"
              label-position="top"
            >
              <el-form-item :label="t('username')" prop="username">
                <el-input v-model="registerForm.username" :placeholder="t('enter_username')" />
              </el-form-item>
              <el-form-item :label="t('email')" prop="email">
                <el-input v-model="registerForm.email" :placeholder="t('enter_email')" />
              </el-form-item>
              <el-form-item :label="t('password')" prop="password">
                <el-input
                  v-model="registerForm.password"
                  type="password"
                  :placeholder="t('enter_password')"
                />
              </el-form-item>
              <el-form-item :label="t('confirm_password')" prop="confirmPassword">
                <el-input
                  v-model="registerForm.confirmPassword"
                  type="password"
                  :placeholder="t('confirm_password_prompt')"
                  @keyup.enter="handleRegister"
                />
              </el-form-item>
              <div class="captcha-strip">
                <div class="captcha-copy">
                  <span class="captcha-label">{{ t('captcha') }}</span>
                  <strong>{{ registerCaptchaPrompt || t('generating_questions') }}</strong>
                  <p>{{ t('captcha_math_hint') }}</p>
                </div>
                <el-button
                  link
                  type="primary"
                  :loading="registerCaptchaLoading"
                  @click="refreshRegisterCaptcha"
                >
                  {{ t('refresh_captcha') }}
                </el-button>
              </div>
              <el-form-item :label="t('calc_result')" prop="captchaAnswer">
                <el-input
                  v-model="registerForm.captchaAnswer"
                  inputmode="numeric"
                  :placeholder="t('enter_calc_result')"
                  @keyup.enter="handleRegister"
                />
              </el-form-item>
              <el-form-item>
                <el-button
                  type="primary"
                  :loading="loading"
                  :disabled="registerCaptchaLoading || !registerForm.captchaId"
                  @click="handleRegister"
                  style="width: 100%"
                >
                  {{ t('register') }}
                </el-button>
              </el-form-item>
            </el-form>
          </el-tab-pane>
        </el-tabs>
      </el-card>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { useAuthStore } from '../stores/auth'
import api from '../utils/api'
import { getPostLoginRedirectPath } from '../utils/authRedirect'
import { checkNeedsSetup } from '../utils/setupStatus'
import appLogo from '@/assets/brand/app-logo.webp'
import { useLocale } from '../composables/useLocale'
const { t } = useLocale()

const router = useRouter()
const authStore = useAuthStore()

const activeTab = ref('login')
const loading = ref(false)
const loginFormRef = ref()
const registerFormRef = ref()
const loginCaptchaPrompt = ref('')
const registerCaptchaPrompt = ref('')
const loginCaptchaLoading = ref(false)
const registerCaptchaLoading = ref(false)
const loginCaptchaEnabled = ref(true)

const loginForm = reactive({
  username: '',
  password: '',
  captchaId: '',
  captchaAnswer: ''
})

const registerForm = reactive({
  username: '',
  email: '',
  password: '',
  confirmPassword: '',
  captchaId: '',
  captchaAnswer: ''
})

const loginRules = {
  username: [{ required: true, message: t('enter_username'), trigger: 'blur' }],
  password: [{ required: true, message: t('enter_password'), trigger: 'blur' }],
  captchaAnswer: [
    {
      validator: (rule, value, callback) => {
        if (!loginCaptchaEnabled.value || String(value || '').trim()) {
          callback()
          return
        }
        callback(new Error(t('enter_calc_result')))
      },
      trigger: 'blur'
    }
  ]
}

const registerRules = {
  username: [{ required: true, message: t('enter_username'), trigger: 'blur' }],
  email: [
    { required: true, message: t('enter_email'), trigger: 'blur' },
    { type: 'email', message: t('enter_valid_email'), trigger: 'blur' }
  ],
  password: [
    { required: true, message: t('enter_password'), trigger: 'blur' },
    { min: 6, message: t('password_min_length'), trigger: 'blur' }
  ],
  confirmPassword: [
    { required: true, message: t('confirm_password_prompt'), trigger: 'blur' },
    {
      validator: (rule, value, callback) => {
        if (value !== registerForm.password) {
          callback(new Error(t('password_mismatch')))
        } else {
          callback()
        }
      },
      trigger: 'blur'
    }
  ],
  captchaAnswer: [
    { required: true, message: t('enter_calc_result'), trigger: 'blur' }
  ]
}

const fetchCaptcha = async (form, promptRef, loadingRef, formRef) => {
  loadingRef.value = true
  try {
    const { data } = await api.get('/captcha/challenge', { silentError: true })
    form.captchaId = data.captchaId
    form.captchaAnswer = ''
    promptRef.value = data.prompt
    formRef?.value?.clearValidate?.(['captchaAnswer'])
  } catch (error) {
    form.captchaId = ''
    form.captchaAnswer = ''
    promptRef.value = t('question_load_failed')
  } finally {
    loadingRef.value = false
  }
}

const clearLoginCaptcha = () => {
  loginForm.captchaId = ''
  loginForm.captchaAnswer = ''
  loginCaptchaPrompt.value = ''
  loginFormRef.value?.clearValidate?.(['captchaAnswer'])
}

const loadLoginCaptchaStatus = async () => {
  try {
    const { data } = await api.get('/captcha/status', { silentError: true })
    loginCaptchaEnabled.value = data?.enabled !== false
  } catch (error) {
    loginCaptchaEnabled.value = true
  }

  if (!loginCaptchaEnabled.value) {
    clearLoginCaptcha()
  }
}

const refreshLoginCaptcha = async () => {
  if (!loginCaptchaEnabled.value) {
    clearLoginCaptcha()
    return
  }
  await fetchCaptcha(loginForm, loginCaptchaPrompt, loginCaptchaLoading, loginFormRef)
}

const refreshRegisterCaptcha = async () => {
  await fetchCaptcha(registerForm, registerCaptchaPrompt, registerCaptchaLoading, registerFormRef)
}

const handleLogin = async () => {
  if (!loginFormRef.value) return

  try {
    await loginFormRef.value.validate()
  } catch {
    return
  }

  if (loginCaptchaEnabled.value && !loginForm.captchaId) {
    ElMessage.error(t('captcha_load_failed'))
    await refreshLoginCaptcha()
    return
  }

  loading.value = true
  const credentials = {
    username: loginForm.username,
    password: loginForm.password
  }
  if (loginCaptchaEnabled.value) {
    credentials.captchaId = loginForm.captchaId
    credentials.captchaAnswer = loginForm.captchaAnswer.trim()
  }
  const result = await authStore.login(credentials)
  loading.value = false

  if (result.success) {
    ElMessage.success(t('login_success'))
    router.push(getPostLoginRedirectPath(authStore.user))
  } else {
    ElMessage.error(result.message)
    if (loginCaptchaEnabled.value) {
      await refreshLoginCaptcha()
    }
  }
}

const handleRegister = async () => {
  if (!registerFormRef.value) return

  try {
    await registerFormRef.value.validate()
  } catch {
    return
  }

  if (!registerForm.captchaId) {
    ElMessage.error(t('captcha_load_failed'))
    await refreshRegisterCaptcha()
    return
  }

  loading.value = true
  const result = await authStore.register({
    username: registerForm.username,
    email: registerForm.email,
    password: registerForm.password,
    captchaId: registerForm.captchaId,
    captchaAnswer: registerForm.captchaAnswer.trim()
  })
  loading.value = false

  if (result.success) {
    ElMessage.success(t('register_success_login'))
    activeTab.value = 'login'
    Object.assign(registerForm, {
      username: '',
      email: '',
      password: '',
      confirmPassword: '',
      captchaId: '',
      captchaAnswer: ''
    })
    await Promise.all([
      loginCaptchaEnabled.value ? refreshLoginCaptcha() : Promise.resolve(),
      refreshRegisterCaptcha()
    ])
  } else {
    ElMessage.error(result.message)
    await refreshRegisterCaptcha()
  }
}

// 检查系统状态，如果未初始化则跳转到引导页面
const checkSystemStatus = async () => {
  try {
    if (await checkNeedsSetup()) {
      router.push('/setup')
    }
  } catch (error) {
    console.error(t('check_system_failed'), error)
  }
}

onMounted(async () => {
  checkSystemStatus()
  await loadLoginCaptchaStatus()
  Promise.allSettled([
    loginCaptchaEnabled.value ? refreshLoginCaptcha() : Promise.resolve(),
    refreshRegisterCaptcha()
  ])
})
</script>

<style scoped>
.login-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 24px;
}

.login-shell {
  width: min(1120px, 100%);
  display: grid;
  grid-template-columns: minmax(0, 1fr) 420px;
  gap: 24px;
  align-items: center;
}

.login-hero {
  padding: 28px;
}

.login-brand {
  display: inline-flex;
  align-items: center;
  gap: 14px;
  margin-bottom: 24px;
  padding: 10px 14px 10px 10px;
  border-radius: 24px;
  background: rgba(255, 255, 255, 0.74);
  border: 1px solid rgba(255, 255, 255, 0.86);
  box-shadow: 0 18px 40px rgba(15, 23, 42, 0.08);
}

.login-brand-logo {
  width: 58px;
  height: 58px;
  border-radius: 20px;
  object-fit: cover;
  box-shadow: 0 12px 24px rgba(0, 122, 255, 0.18);
}

.login-brand strong,
.login-brand span {
  display: block;
}

.login-brand strong {
  color: var(--apple-text);
  font-size: 18px;
  line-height: 1.25;
}

.login-brand span {
  margin-top: 3px;
  color: var(--apple-text-secondary);
  font-size: 13px;
}

.login-eyebrow,
.card-eyebrow {
  margin: 0 0 8px;
  color: var(--apple-primary);
  font-size: 11px;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.login-hero h1 {
  margin: 0;
  font-size: 48px;
  line-height: 1.02;
  letter-spacing: -0.05em;
}

.login-hero p {
  margin: 16px 0 0;
  max-width: 520px;
  color: var(--apple-text-secondary);
  line-height: 1.8;
}

.login-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  margin-top: 22px;
}

.login-card {
  border-radius: 30px;
  background: rgba(255, 255, 255, 0.88);
  border: 1px solid rgba(255, 255, 255, 0.9);
  box-shadow: var(--apple-shadow-lg);
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.card-header h2 {
  margin: 0;
  color: var(--apple-text);
  font-size: 28px;
  letter-spacing: -0.03em;
}

.login-tabs {
  margin-top: 8px;
}

.captcha-strip {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  margin-bottom: 18px;
  padding: 14px 16px;
  border-radius: 18px;
  border: 1px solid var(--apple-border);
  background: rgba(247, 248, 250, 0.92);
}

.captcha-copy {
  min-width: 0;
}

.captcha-copy strong {
  display: block;
  color: var(--apple-text);
  font-size: 18px;
  letter-spacing: -0.02em;
}

.captcha-copy p {
  margin: 6px 0 0;
  color: var(--apple-text-secondary);
  font-size: 13px;
  line-height: 1.6;
}

.captcha-label {
  display: inline-block;
  margin-bottom: 6px;
  color: var(--apple-text-secondary);
  font-size: 12px;
  font-weight: 600;
}

@media (max-width: 960px) {
  .login-shell {
    grid-template-columns: 1fr;
  }

  .login-hero {
    padding: 8px 0;
  }

  .login-hero h1 {
    font-size: 38px;
  }

  .captcha-strip {
    align-items: flex-start;
    flex-direction: column;
  }
}
</style>
