// manager/frontend/src/components/agents/agent-form.tsx
import { forwardRef, useEffect, useImperativeHandle, useRef } from 'react'
import { toast } from 'sonner'
import { useAgentFormOptions } from '@/hooks/use-agent-form-options'
import type { AgentFormData, LLMConfig, TTSConfig } from '@/features/agents/types'
import { buildAgentPayload } from '@/features/agents/types'
import { useLocale } from '@/hooks/use-locale'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Switch } from '@/components/ui/switch'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'

export interface AgentFormHandle {
  validate: () => Promise<boolean>
  buildPayload: () => Record<string, unknown>
  reloadOptions: () => Promise<void>
}

interface Props {
  value: AgentFormData
  onChange: (data: AgentFormData) => void
  isAdmin?: boolean
  mode?: 'create' | 'edit'
}

const Field = ({ label, children }: { label: string; children: React.ReactNode }) => (
  <div className="grid gap-1.5">
    <label className="text-sm font-medium text-[var(--color-text)]">{label}</label>
    {children}
  </div>
)

export const AgentForm = forwardRef<AgentFormHandle, Props>(({ value, onChange, isAdmin = false, mode = 'create' }, ref) => {
  const { t } = useLocale()
  const opts = useAgentFormOptions()
  const ttsRef = useRef<string | null>(value.tts_config_id)

  const set = (patch: Partial<AgentFormData>) => onChange({ ...value, ...patch })

  const getProvider = (cfgs: TTSConfig[], id: string | null) => cfgs.find((c) => c.config_id === id)?.provider ?? ''

  const handleTtsChange = async (newId: string | null) => {
    const prev = ttsRef.current
    ttsRef.current = newId
    set({ tts_config_id: newId, voice: null })
    const provider = getProvider(opts.ttsConfigs, newId)
    if (newId && provider) {
      const voices = await opts.refreshVoices({ ttsConfigId: newId, provider, clearInvalid: true, previousConfigId: prev })
      if (mode === 'create' && !value.voice && voices.length) set({ tts_config_id: newId, voice: null })
    } else {
      await opts.refreshVoices({ ttsConfigId: null })
    }
  }

  const applyClone = async (clone: { tts_config_id: string; provider_voice_id: string }) => {
    if (clone.tts_config_id !== value.tts_config_id) await handleTtsChange(clone.tts_config_id)
    set({ voice: clone.provider_voice_id })
  }

  const toggleMcp = (svc: string) => {
    const curr = value.mcp_service_names.split(',').map((s) => s.trim()).filter(Boolean)
    const next = curr.includes(svc) ? curr.filter((s) => s !== svc) : [...curr, svc]
    set({ mcp_service_names: next.join(',') })
  }

  const addKeyword = (field: 'openclaw_enter_keywords' | 'openclaw_exit_keywords', kw: string) => {
    const trimmed = kw.trim()
    if (!trimmed || value[field].includes(trimmed)) return
    set({ [field]: [...value[field], trimmed] })
  }
  const removeKeyword = (field: 'openclaw_enter_keywords' | 'openclaw_exit_keywords', kw: string) => {
    set({ [field]: value[field].filter((k) => k !== kw) })
  }

  useEffect(() => {
    opts.load({ isAdmin, userId: isAdmin ? value.user_id : null, ttsConfigId: value.tts_config_id }).then(async () => {
      if (value.tts_config_id) {
        const provider = getProvider(opts.ttsConfigs, value.tts_config_id)
        if (provider) await opts.refreshVoices({ ttsConfigId: value.tts_config_id, provider, clearInvalid: false })
      }
      if (mode === 'create') {
        const patch: Partial<AgentFormData> = {}
        if (!value.llm_config_id) { const d = opts.llmConfigs.find((c: LLMConfig) => c.is_default); if (d) patch.llm_config_id = d.config_id }
        if (!value.tts_config_id) { const d = opts.ttsConfigs.find((c: TTSConfig) => c.is_default); if (d) patch.tts_config_id = d.config_id }
        if (Object.keys(patch).length) set(patch)
      }
    })
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  useImperativeHandle(ref, () => ({
    validate: async () => {
      if (isAdmin && !value.user_id) { toast.error(t('select_owner_user')); return false }
      if (!value.name.trim()) { toast.error(t('enter_agent_name')); return false }
      if (!value.nickname.trim()) { toast.error(t('enter_agent_nickname')); return false }
      return true
    },
    buildPayload: () => buildAgentPayload(value, { isAdmin }),
    reloadOptions: async () => opts.load({ isAdmin, userId: isAdmin ? value.user_id : null, ttsConfigId: value.tts_config_id }),
  }))

  const selectedMcpSet = new Set(value.mcp_service_names.split(',').map((s) => s.trim()).filter(Boolean))

  return (
    <div className="grid gap-4">
      {isAdmin && (
        <Field label={t('owner_user')}>
          <Select value={value.user_id ? String(value.user_id) : ''} onValueChange={(v) => set({ user_id: Number(v) || null })}>
            <SelectTrigger><SelectValue placeholder={t('select_owner_user')} /></SelectTrigger>
            <SelectContent>{opts.users.map((u) => <SelectItem key={u.id} value={String(u.id)}>{u.username || u.name} (ID: {u.id})</SelectItem>)}</SelectContent>
          </Select>
        </Field>
      )}
      <div className="grid grid-cols-2 gap-4">
        <Field label={t('agent_name')}><Input value={value.name} onChange={(e) => set({ name: e.target.value })} maxLength={50} placeholder={t('enter_admin_display_name')} /></Field>
        <Field label={t('agent_nickname')}><Input value={value.nickname} onChange={(e) => set({ nickname: e.target.value })} maxLength={50} placeholder={t('model_display_name_hint')} /></Field>
      </div>
      <Field label={t('role_description')}>
        <Textarea value={value.custom_prompt} onChange={(e) => set({ custom_prompt: e.target.value })} rows={4} maxLength={10000} placeholder={t('enter_role_prompt')} />
      </Field>
      <Field label={t('link_knowledge_base')}>
        <div className="border border-[var(--color-line)] rounded-lg max-h-32 overflow-y-auto p-1.5">
          {opts.knowledgeBases.length === 0 ? (
            <p className="text-xs text-[var(--color-text-tertiary)] p-2 text-center">{t('select_linked_knowledge_base')}</p>
          ) : opts.knowledgeBases.map((kb) => (
            <label key={kb.id} className="flex items-center gap-2 p-1.5 rounded hover:bg-[var(--color-surface-muted)] cursor-pointer text-sm">
              <input type="checkbox" checked={value.knowledge_base_ids.includes(kb.id)} onChange={(e) => set({ knowledge_base_ids: e.target.checked ? [...value.knowledge_base_ids, kb.id] : value.knowledge_base_ids.filter((id) => id !== kb.id) })} className="accent-[var(--color-primary)]" />
              <span>{kb.name}</span>
            </label>
          ))}
        </div>
      </Field>
      <div className="grid grid-cols-2 gap-4">
        <Field label={t('language_model')}>
          <Select value={value.llm_config_id ?? ''} onValueChange={(v) => set({ llm_config_id: v || null })}>
            <SelectTrigger><SelectValue placeholder={t('select_language_model')} /></SelectTrigger>
            <SelectContent>{opts.llmConfigs.map((c) => <SelectItem key={c.config_id} value={c.config_id}>{c.is_default ? t('tts_default_label', { name: c.name }) : c.name}</SelectItem>)}</SelectContent>
          </Select>
        </Field>
        <Field label={t('tts_config_label')}>
          <Select value={value.tts_config_id ?? ''} onValueChange={(v) => handleTtsChange(v || null)}>
            <SelectTrigger><SelectValue placeholder={t('select_tts_config')} /></SelectTrigger>
            <SelectContent>{opts.ttsConfigs.map((c) => <SelectItem key={c.config_id} value={c.config_id}>{c.is_default ? t('tts_default_label', { name: c.name }) : c.name}</SelectItem>)}</SelectContent>
          </Select>
        </Field>
      </div>
      {value.tts_config_id && (
        <Field label={t('tts_voice')}>
          <Input value={value.voice ?? ''} onChange={(e) => set({ voice: e.target.value || null })} list="agent-voice-list" placeholder={t('select_or_enter_timbre')} />
          <datalist id="agent-voice-list">{opts.filteredVoiceOptions.map((v) => <option key={v.value} value={v.value}>{v.label || v.value}</option>)}</datalist>
        </Field>
      )}
      {opts.cloneVoices.length > 0 && (
        <div className="flex flex-wrap gap-1.5 -mt-2">
          {opts.cloneVoices.map((clone) => (
            <button key={clone.id} type="button" onClick={() => applyClone(clone)}
              className={`inline-flex items-center px-2.5 py-1 rounded-lg text-xs border transition-colors cursor-pointer ${value.tts_config_id === clone.tts_config_id && value.voice === clone.provider_voice_id ? 'status-primary' : 'border-[var(--color-line)] text-[var(--color-text-secondary)] hover:border-[var(--color-primary)]'}`}>
              {clone.name || clone.provider_voice_id}
            </button>
          ))}
        </div>
      )}
      <div className="grid grid-cols-3 gap-4">
        {([['asr_speed', [['normal', t('normal')], ['patient', t('patience')], ['fast', t('fast')]], t('asr_speed')],
          ['memory_mode', [['none', t('no_memory')], ['short', t('short_memory')], ['long', t('long_memory')]], t('memory_mode')],
          ['speaker_chat_mode', [['off', t('close')], ['identified_only', t('voiceprint_only_chat')]], t('voiceprint_chat_limit')],
        ] as [keyof AgentFormData, [string, string][], string][]).map(([field, opts2, label]) => (
          <Field key={field} label={label}>
            <Select value={String(value[field])} onValueChange={(v) => set({ [field]: v } as Partial<AgentFormData>)}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>{opts2.map(([val, lbl]) => <SelectItem key={val} value={val}>{lbl}</SelectItem>)}</SelectContent>
            </Select>
          </Field>
        ))}
      </div>
      <Field label={t('mcp_service')}>
        <div className="border border-[var(--color-line)] rounded-lg max-h-32 overflow-y-auto p-1.5">
          {opts.mcpServiceOptions.length === 0 ? (
            <p className="text-xs text-[var(--color-text-tertiary)] p-2 text-center">{t('leave_blank_all_enabled')}</p>
          ) : opts.mcpServiceOptions.map((svc) => (
            <label key={svc} className="flex items-center gap-2 p-1.5 rounded hover:bg-[var(--color-surface-muted)] cursor-pointer text-sm">
              <input type="checkbox" checked={selectedMcpSet.has(svc)} onChange={() => toggleMcp(svc)} className="accent-[var(--color-primary)]" />
              <span>{svc}</span>
            </label>
          ))}
        </div>
      </Field>
      <div className="border border-[var(--color-line)] rounded-xl p-4 bg-[var(--color-surface-2)] grid gap-3">
        <div className="flex items-center justify-between gap-3">
          <span className="text-sm font-semibold text-[var(--color-text)]">{t('allow_openclaw_mode')}</span>
          <Switch checked={!!value.openclaw_allowed} onCheckedChange={(v) => set({ openclaw_allowed: v })} />
        </div>
        <div className="grid grid-cols-2 gap-4">
          {(['openclaw_enter_keywords', 'openclaw_exit_keywords'] as const).map((field) => (
            <div key={field} className="grid gap-1.5">
              <label className="text-xs font-medium text-[var(--color-text-secondary)]">{field === 'openclaw_enter_keywords' ? t('openclaw_enter_keyword') : t('openclaw_exit_keyword')}</label>
              <div className="flex flex-wrap gap-1 min-h-[28px]">
                {value[field].map((kw) => (
                  <span key={kw} className="inline-flex items-center gap-0.5 px-2 py-0.5 rounded-full border text-xs status-primary">
                    {kw}<button type="button" className="hover:opacity-70 ml-0.5" onClick={() => removeKeyword(field, kw)}>×</button>
                  </span>
                ))}
              </div>
              <Input className="h-7 text-xs" placeholder={t('enter_press_add_keywords')}
                onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); addKeyword(field, (e.target as HTMLInputElement).value); (e.target as HTMLInputElement).value = '' } }} />
            </div>
          ))}
        </div>
      </div>
    </div>
  )
})

AgentForm.displayName = 'AgentForm'

// manager/frontend/src/components/common/AgentForm.vue
<template>
  <el-form
    ref="formRef"
    :model="form"
    :rules="rules"
    :label-position="labelPosition"
    :label-width="labelWidth"
    class="shared-agent-form"
  >
    <el-form-item v-if="isAdmin" :label="t('owner_user')" prop="user_id">
      <el-select
        v-model="form.user_id"
        :placeholder="t('select_owner_user')"
        filterable
        style="width: 100%"
        :loading="loading.users"
      >
        <el-option
          v-for="user in users"
          :key="user.id"
          :label="userLabel(user)"
          :value="user.id"
        />
      </el-select>
    </el-form-item>

    <div class="agent-form-grid">
      <el-form-item :label="t('agent_name')" prop="name">
        <el-input v-model="form.name" :placeholder="t('enter_admin_display_name')" maxlength="50" show-word-limit />
      </el-form-item>
      <el-form-item :label="t('agent_nickname')" prop="nickname">
        <el-input v-model="form.nickname" :placeholder="t('model_display_name_hint')" maxlength="50" show-word-limit />
      </el-form-item>
    </div>

    <el-form-item :label="t('role_description')" prop="custom_prompt">
      <el-input
        v-model="form.custom_prompt"
        type="textarea"
        :rows="4"
        :placeholder="t('enter_role_prompt')"
        maxlength="10000"
        show-word-limit
      />
    </el-form-item>

    <el-form-item :label="t('link_knowledge_base')" prop="knowledge_base_ids">
      <el-select
        v-model="form.knowledge_base_ids"
        multiple
        filterable
        collapse-tags
        collapse-tags-tooltip
        clearable
        :placeholder="t('select_linked_knowledge_base')"
        style="width: 100%"
        :loading="loading.knowledgeBases"
        :disabled="isAdmin && !form.user_id"
      >
        <el-option
          v-for="kb in knowledgeBases"
          :key="kb.id"
          :label="kb.name || t('kb_default_label', { id: kb.id })"
          :value="kb.id"
        />
      </el-select>
    </el-form-item>

    <div class="agent-form-grid">
      <el-form-item :label="t('language_model')" prop="llm_config_id">
        <el-select
          v-model="form.llm_config_id"
          :placeholder="t('select_language_model')"
          style="width: 100%"
          clearable
          filterable
          :loading="loading.configs"
        >
          <el-option
            v-for="config in llmConfigs"
            :key="config.config_id"
            :label="config.is_default ? t('tts_default_label', { name: config.name }) : config.name"
            :value="config.config_id"
          >
            <div class="config-option">
              <span>{{ config.name }}</span>
              <span>{{ config.provider || config.config_id }}</span>
            </div>
          </el-option>
        </el-select>
      </el-form-item>

      <el-form-item :label="t('tts_config_label')" prop="tts_config_id">
        <el-select
          v-model="form.tts_config_id"
          :placeholder="t('select_tts_config')"
          style="width: 100%"
          clearable
          filterable
          :loading="loading.configs"
        >
          <el-option
            v-for="config in ttsConfigs"
            :key="config.config_id"
            :label="config.is_default ? t('tts_default_label', { name: config.name }) : config.name"
            :value="config.config_id"
          >
            <div class="config-option">
              <span>{{ config.name }}</span>
              <span>{{ config.provider || config.config_id }}</span>
            </div>
          </el-option>
        </el-select>
      </el-form-item>
    </div>

    <el-form-item v-if="form.tts_config_id" :label="t('tts_voice')" prop="voice">
      <el-select
        v-model="form.voice"
        :placeholder="t('select_or_enter_timbre')"
        style="width: 100%"
        filterable
        allow-create
        default-first-option
        reserve-keyword
        clearable
        :loading="loading.voices"
        :filter-method="filterVoice"
      >
        <el-option
          v-for="voice in visibleVoiceOptions"
          :key="voice.value"
          :label="voice.label || voice.value"
          :value="voice.value"
        >
          <div class="voice-option">
            <span>{{ voice.label || voice.value }}</span>
            <span>{{ voice.value }}</span>
          </div>
        </el-option>
      </el-select>
    </el-form-item>

    <div v-if="cloneVoices.length" class="clone-voice-row" v-loading="loading.cloneVoices">
      <button
        v-for="clone in cloneVoices"
        :key="clone.id"
        type="button"
        class="clone-voice-button"
        :class="{ active: form.tts_config_id === clone.tts_config_id && form.voice === clone.provider_voice_id }"
        :title="`${clone.tts_config_name || clone.tts_config_id} · ${clone.provider_voice_id}`"
        @click="applyCloneVoice(clone)"
      >
        {{ clone.name || clone.provider_voice_id }}
      </button>
    </div>

    <div class="agent-form-grid agent-form-grid-three">
      <el-form-item :label="t('asr_speed')" prop="asr_speed">
        <el-select v-model="form.asr_speed" style="width: 100%">
          <el-option :label="t('normal')" value="normal" />
          <el-option :label="t('patience')" value="patient" />
          <el-option :label="t('fast')" value="fast" />
        </el-select>
      </el-form-item>
      <el-form-item :label="t('memory_mode')" prop="memory_mode">
        <el-select v-model="form.memory_mode" style="width: 100%">
          <el-option :label="t('no_memory')" value="none" />
          <el-option :label="t('short_memory')" value="short" />
          <el-option :label="t('long_memory')" value="long" />
        </el-select>
      </el-form-item>
      <el-form-item :label="t('voiceprint_chat_limit')" prop="speaker_chat_mode">
        <el-select v-model="form.speaker_chat_mode" style="width: 100%">
          <el-option :label="t('close')" value="off" />
          <el-option :label="t('voiceprint_only_chat')" value="identified_only" />
        </el-select>
      </el-form-item>
    </div>

    <el-form-item :label="t('mcp_service')">
      <el-select
        v-model="selectedMcpServices"
        multiple
        filterable
        collapse-tags
        collapse-tags-tooltip
        clearable
        style="width: 100%"
        :placeholder="t('leave_blank_all_enabled')"
        :loading="loading.mcpServices"
      >
        <el-option
          v-for="serviceName in mcpServiceOptions"
          :key="serviceName"
          :label="serviceName"
          :value="serviceName"
        />
      </el-select>
    </el-form-item>

    <div class="openclaw-panel">
      <div class="openclaw-switch-row">
        <span>{{ t('allow_openclaw_mode') }}</span>
        <el-switch v-model="form.openclaw_allowed" />
      </div>
      <div class="agent-form-grid">
        <el-form-item :label="t('openclaw_enter_keyword')">
          <el-select
            v-model="form.openclaw_enter_keywords"
            multiple
            filterable
            allow-create
            default-first-option
            clearable
            style="width: 100%"
            :placeholder="t('enter_press_add_keywords')"
          />
        </el-form-item>
        <el-form-item :label="t('openclaw_exit_keyword')">
          <el-select
            v-model="form.openclaw_exit_keywords"
            multiple
            filterable
            allow-create
            default-first-option
            clearable
            style="width: 100%"
            :placeholder="t('enter_press_add_keywords')"
          />
        </el-form-item>
      </div>
    </div>

  </el-form>
</template>

<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { useLocale } from '../../composables/useLocale'
import {
  buildAgentPayload,
  useAgentFormOptions
} from '../../composables/useAgentFormOptions'

const { t } = useLocale()

const props = defineProps({
  modelValue: {
    type: Object,
    required: true
  },
  isAdmin: {
    type: Boolean,
    default: false
  },
  mode: {
    type: String,
    default: 'create'
  },
  labelPosition: {
    type: String,
    default: 'top'
  },
  labelWidth: {
    type: String,
    default: '120px'
  }
})

const emit = defineEmits(['update:modelValue'])

const form = computed({
  get: () => props.modelValue,
  set: (value) => emit('update:modelValue', value)
})

const targetUserId = computed(() => props.isAdmin ? Number(form.value.user_id || 0) : 0)

const {
  users,
  llmConfigs,
  ttsConfigs,
  knowledgeBases,
  mcpServiceOptions,
  voiceOptions,
  cloneVoices,
  loading,
  loadUsers,
  loadConfigs,
  loadKnowledgeBases,
  loadMcpServiceOptions,
  loadVoiceOptions,
  loadCloneVoices
} = useAgentFormOptions({
  isAdmin: computed(() => props.isAdmin),
  targetUserId
})

const rules = computed(() => ({
  user_id: props.isAdmin ? [{ required: true, message: t('select_owner_user'), trigger: 'change' }] : [],
  name: [
    { required: true, message: t('enter_agent_name'), trigger: 'blur' },
    { min: 1, max: 50, message: t('max_length_50'), trigger: 'blur' }
  ],
  nickname: [
    { required: true, message: t('enter_agent_nickname'), trigger: 'blur' },
    { min: 1, max: 50, message: t('max_length_50'), trigger: 'blur' }
  ],
  asr_speed: [{ required: true, message: t('select_asr_speed'), trigger: 'change' }],
  memory_mode: [{ required: true, message: t('select_memory_mode'), trigger: 'change' }],
  speaker_chat_mode: [{ required: true, message: t('select_voiceprint_limit'), trigger: 'change' }]
}))

const formRef = ref(null)
const MAX_VISIBLE_VOICE_OPTIONS = 300
const voiceSearchKeyword = ref('')
const filteredVoiceOptions = ref([])
const previousTtsConfigId = ref(null)
const suppressTtsConfigWatch = ref(false)

const selectedTtsConfig = computed(() => {
  return ttsConfigs.value.find((config) => config.config_id === form.value.tts_config_id) || null
})

const visibleVoiceOptions = computed(() => {
  const selected = String(form.value.voice || '').trim()
  const options = Array.isArray(filteredVoiceOptions.value) ? [...filteredVoiceOptions.value] : []
  if (selected && !options.some((item) => item.value === selected)) {
    options.unshift({ label: selected, value: selected })
  }
  return options.slice(0, MAX_VISIBLE_VOICE_OPTIONS)
})

const selectedMcpServices = computed({
  get: () => String(form.value.mcp_service_names || '')
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean),
  set: (items) => {
    form.value.mcp_service_names = Array.isArray(items) ? items.join(',') : ''
  }
})

const userLabel = (user) => {
  const name = user?.username || user?.name || t('user_id_fallback', { id: user?.id })
  return `${name} (ID: ${user?.id})`
}

const loadTargetUserOptions = async () => {
  await Promise.all([
    loadKnowledgeBases().catch(() => []),
    loadCloneVoices(form.value.tts_config_id || '').catch(() => [])
  ])
  const validKnowledgeBaseIds = new Set(knowledgeBases.value.map((item) => Number(item.id)))
  if (validKnowledgeBaseIds.size) {
    form.value.knowledge_base_ids = (form.value.knowledge_base_ids || []).filter((id) => validKnowledgeBaseIds.has(Number(id)))
  } else if (props.isAdmin && targetUserId.value) {
    form.value.knowledge_base_ids = []
  }
}

const applyDefaultConfigs = () => {
  if (props.mode !== 'create') return
  if (!form.value.llm_config_id) {
    const defaultLlm = llmConfigs.value.find((config) => config.is_default)
    if (defaultLlm) form.value.llm_config_id = defaultLlm.config_id
  }
  if (!form.value.tts_config_id) {
    const defaultTts = ttsConfigs.value.find((config) => config.is_default)
    if (defaultTts) form.value.tts_config_id = defaultTts.config_id
  }
}

const limitVoiceOptions = (voices) => {
  const list = Array.isArray(voices) ? voices : []
  const visible = list.slice(0, MAX_VISIBLE_VOICE_OPTIONS)
  const selected = String(form.value.voice || '').trim()
  if (selected && !visible.some((voice) => voice.value === selected)) {
    const selectedOption = list.find((voice) => voice.value === selected)
    if (selectedOption) visible.unshift(selectedOption)
  }
  return visible
}

const filterVoice = (value = '') => {
  voiceSearchKeyword.value = value
  const keyword = String(value || '').trim().toLowerCase()
  if (!keyword) {
    filteredVoiceOptions.value = limitVoiceOptions(voiceOptions.value)
    return
  }

  const matchedVoices = voiceOptions.value.filter((voice) => {
    const label = String(voice.label || '').toLowerCase()
    const voiceValue = String(voice.value || '').toLowerCase()
    return label.includes(keyword) || voiceValue.includes(keyword)
  })
  filteredVoiceOptions.value = limitVoiceOptions(matchedVoices)
}

const syncFilteredVoiceOptions = () => {
  filterVoice(voiceSearchKeyword.value)
}

const refreshVoiceOptions = async ({ clearInvalid = true, previousConfigId = previousTtsConfigId.value } = {}) => {
  const provider = selectedTtsConfig.value?.provider
  if (!form.value.tts_config_id || !provider) {
    voiceOptions.value = []
    filteredVoiceOptions.value = []
    form.value.voice = null
    previousTtsConfigId.value = null
    return
  }

  const previousConfig = ttsConfigs.value.find((config) => config.config_id === previousConfigId)
  if (clearInvalid && previousConfig?.provider && previousConfig.provider !== provider) {
    form.value.voice = null
  }

  const voices = await loadVoiceOptions({ provider, configId: form.value.tts_config_id }).catch(() => [])
  await loadCloneVoices(form.value.tts_config_id).catch(() => [])
  if (clearInvalid && form.value.voice && voices.length) {
    const exists = voices.some((voice) => voice.value === form.value.voice)
    if (!exists) form.value.voice = null
  }
  syncFilteredVoiceOptions()
  previousTtsConfigId.value = form.value.tts_config_id
}

const applyCloneVoice = async (clone) => {
  if (!clone?.tts_config_id || !clone?.provider_voice_id) return
  await setTtsConfig(clone.tts_config_id, { clearInvalid: false })
  form.value.voice = clone.provider_voice_id
}

const setTtsConfig = async (configId, options = {}) => {
  const previousConfigId = form.value.tts_config_id
  suppressTtsConfigWatch.value = true
  form.value.tts_config_id = configId || null
  try {
    await refreshVoiceOptions({
      clearInvalid: true,
      previousConfigId,
      ...options
    })
  } finally {
    Promise.resolve().then(() => {
      suppressTtsConfigWatch.value = false
    })
  }
}

const reloadOptions = async () => {
  await Promise.all([
    props.isAdmin ? loadUsers().catch(() => []) : Promise.resolve([]),
    loadConfigs(),
    loadMcpServiceOptions().catch(() => [])
  ])
  applyDefaultConfigs()
  await loadTargetUserOptions()
  await refreshVoiceOptions({ clearInvalid: false })
}

watch(
  () => form.value.user_id,
  async (next, prev) => {
    if (!props.isAdmin || next === prev) return
    form.value.knowledge_base_ids = []
    form.value.voice = null
    previousTtsConfigId.value = null
    await loadTargetUserOptions()
    await refreshVoiceOptions({ clearInvalid: true })
  }
)

watch(
  () => form.value.tts_config_id,
  async (next, prev) => {
    if (next === prev) return
    if (suppressTtsConfigWatch.value) return
    await refreshVoiceOptions({ clearInvalid: true, previousConfigId: prev })
  }
)

onMounted(() => {
  reloadOptions()
})

const validate = () => formRef.value?.validate?.()
const resetFields = () => formRef.value?.resetFields?.()
const clearValidate = () => formRef.value?.clearValidate?.()
const buildPayload = () => buildAgentPayload(form.value, { isAdmin: props.isAdmin })
const hasLlmConfig = (configId) => !configId || llmConfigs.value.some((config) => config.config_id === configId)
const hasTtsConfig = (configId) => !configId || ttsConfigs.value.some((config) => config.config_id === configId)

defineExpose({
  validate,
  resetFields,
  clearValidate,
  reloadOptions,
  refreshVoiceOptions,
  setTtsConfig,
  buildPayload,
  hasLlmConfig,
  hasTtsConfig
})
</script>

<style scoped>
.shared-agent-form {
  display: grid;
  gap: 2px;
}

.agent-form-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 14px;
}

.agent-form-grid-three {
  grid-template-columns: repeat(3, minmax(0, 1fr));
}

.config-option,
.voice-option {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}

.config-option span:last-child,
.voice-option span:last-child {
  color: #909399;
  font-size: 12px;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
}

.clone-voice-row {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin: -4px 0 18px;
}

.clone-voice-button {
  border: 1px solid #dcdfe6;
  border-radius: 8px;
  background: #fff;
  color: #606266;
  cursor: pointer;
  font-size: 12px;
  line-height: 1;
  padding: 8px 10px;
}

.clone-voice-button.active {
  border-color: #409eff;
  background: #ecf5ff;
  color: #1677d2;
}

.openclaw-panel {
  margin-bottom: 18px;
  padding: 14px;
  border: 1px solid #ebeef5;
  border-radius: 8px;
  background: #fafafa;
}

.openclaw-switch-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: 12px;
  color: #303133;
  font-size: 14px;
  font-weight: 600;
}

@media (max-width: 900px) {
  .agent-form-grid,
  .agent-form-grid-three {
    grid-template-columns: 1fr;
  }
}
</style>
