// manager/frontend/src/components/speakers/speaker-group-list.tsx
import { Search, Plus, Play, Eye, Edit, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Skeleton } from '@/components/ui/skeleton'
import { Badge } from '@/components/ui/badge'
import { useLocale } from '@/hooks/use-locale'

interface Agent { id: number; name: string }
interface SpeakerGroup {
  id: number
  name: string
  agent_name?: string
  prompt?: string
  sample_count: number
  created_at: string
}

interface Props {
  agents: Agent[]
  groups: SpeakerGroup[]
  loading: boolean
  filterAgentId: string
  searchKeyword: string
  onFilterAgentChange: (v: string) => void
  onSearchChange: (v: string) => void
  onAdd: () => void
  onEdit: (row: SpeakerGroup) => void
  onDelete: (row: SpeakerGroup) => void
  onViewSamples: (row: SpeakerGroup) => void
  onVerify: (row: SpeakerGroup) => void
  formatDate: (v: string) => string
  truncateText: (v: string, n: number) => string
}

export function SpeakerGroupList({
  agents, groups, loading,
  filterAgentId, searchKeyword,
  onFilterAgentChange, onSearchChange,
  onAdd, onEdit, onDelete, onViewSamples, onVerify,
  formatDate, truncateText,
}: Props) {
  const { t } = useLocale()

  return (
    <div className="grid gap-4 px-6 pb-8">
      {/* Filter bar */}
      <div className="flex items-center gap-2 flex-wrap">
        <Select value={filterAgentId} onValueChange={onFilterAgentChange}>
          <SelectTrigger className="w-[200px]"><SelectValue placeholder={t('filter_by_agent')} /></SelectTrigger>
          <SelectContent>
            <SelectItem value="">{t('all_agents')}</SelectItem>
            {agents.map((a) => <SelectItem key={a.id} value={String(a.id)}>{a.name}</SelectItem>)}
          </SelectContent>
        </Select>
        <div className="relative">
          <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-4 w-4 text-[var(--color-text-tertiary)]" />
          <Input value={searchKeyword} onChange={(e) => onSearchChange(e.target.value)}
            placeholder={t('search_voiceprint_group')} className="pl-8 w-[250px]" />
        </div>
        <Button className="ml-auto" onClick={onAdd}>
          <Plus className="w-4 h-4 mr-1.5" />{t('create_voiceprint_group')}
        </Button>
      </div>

      {/* Table */}
      <div className="rounded-xl border border-[var(--color-line)] bg-[var(--color-surface-1)] overflow-hidden">
        <div className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>{t('voiceprint_group_name')}</TableHead>
                <TableHead>{t('link_agent')}</TableHead>
                <TableHead>Prompt</TableHead>
                <TableHead className="w-24 text-center">{t('sample_count')}</TableHead>
                <TableHead>{t('created_at')}</TableHead>
                <TableHead className="text-center">{t('actions')}</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {loading ? (
                Array.from({ length: 4 }).map((_, i) => (
                  <TableRow key={i}>
                    {Array.from({ length: 6 }).map((_, j) => (
                      <TableCell key={j}><Skeleton className="h-4 w-full" /></TableCell>
                    ))}
                  </TableRow>
                ))
              ) : groups.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={6} className="py-12 text-center text-sm text-[var(--color-text-tertiary)]">
                    {t('no_data')}
                  </TableCell>
                </TableRow>
              ) : (
                groups.map((row) => (
                  <TableRow key={row.id}>
                    <TableCell className="font-semibold">{row.name}</TableCell>
                    <TableCell className="text-[var(--color-text-secondary)]">{row.agent_name}</TableCell>
                    <TableCell className="text-[var(--color-text-secondary)] text-sm">
                      {row.prompt
                        ? <span title={row.prompt} className="cursor-help">{truncateText(row.prompt, 30)}</span>
                        : <span className="text-[var(--color-text-tertiary)]">-</span>}
                    </TableCell>
                    <TableCell className="text-center">
                      <Badge variant="secondary">{row.sample_count}</Badge>
                    </TableCell>
                    <TableCell className="text-sm text-[var(--color-text-secondary)]">{formatDate(row.created_at)}</TableCell>
                    <TableCell>
                      <div className="flex items-center justify-center gap-1 flex-wrap">
                        <Button variant="outline" size="sm" onClick={() => onVerify(row)}>
                          <Play className="w-3.5 h-3.5 mr-1" />{t('verify')}
                        </Button>
                        <Button variant="outline" size="sm" onClick={() => onViewSamples(row)}>
                          <Eye className="w-3.5 h-3.5 mr-1" />{t('manage_voiceprints')}
                        </Button>
                        <Button variant="outline" size="sm" onClick={() => onEdit(row)}>
                          <Edit className="w-3.5 h-3.5 mr-1" />{t('edit')}
                        </Button>
                        <Button variant="ghost" size="sm" className="text-destructive hover:text-destructive"
                          onClick={() => onDelete(row)}>
                          <Trash2 className="w-3.5 h-3.5 mr-1" />{t('delete')}
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </div>
      </div>
    </div>
  )
}

// manager/frontend/src/components/user/SpeakerGroupList.vue
<template>
  <div>
    <!-- Filter bar -->
    <div class="filter-bar">
      <el-select
        v-model="filterAgentId"
        :placeholder="t('filter_by_agent')"
        clearable
        style="width: 200px; margin-right: 10px;"
        @change="emit('filter-change')"
      >
        <el-option :label="t('all_agents')" value="" />
        <el-option
          v-for="agent in agents"
          :key="agent.id"
          :label="agent.name"
          :value="agent.id"
        />
      </el-select>
      <el-input
        v-model="searchKeyword"
        :placeholder="t('search_voiceprint_group')"
        clearable
        style="width: 250px;"
      >
        <template #prefix>
          <el-icon><Search /></el-icon>
        </template>
      </el-input>
      <el-button class="create-group-button" type="primary" @click="emit('add-group')">
        <el-icon><Plus /></el-icon>
        {{ t('create_voiceprint_group') }}
      </el-button>
    </div>

    <!-- Voiceprint group table -->
    <div v-loading="loading" class="speakers-content">
      <el-table :data="filteredGroups" stripe style="width: 100%">
        <el-table-column prop="name" :label="t('voiceprint_group_name')" min-width="150" />
        <el-table-column prop="agent_name" :label="t('link_agent')" min-width="120" />
        <el-table-column label="Prompt" min-width="200">
          <template #default="{ row }">
            <el-popover placement="top" :width="300" trigger="hover" v-if="row.prompt">
              <template #reference>
                <span class="prompt-text">{{ truncateText(row.prompt, 30) }}</span>
              </template>
              <div class="prompt-popover">{{ row.prompt }}</div>
            </el-popover>
            <span v-else class="text-muted">-</span>
          </template>
        </el-table-column>
        <el-table-column prop="sample_count" :label="t('sample_count')" width="100" align="center">
          <template #default="{ row }">
            <el-tag type="info">{{ row.sample_count }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="created_at" :label="t('created_at')" width="180">
          <template #default="{ row }">{{ formatDate(row.created_at) }}</template>
        </el-table-column>
        <el-table-column :label="t('actions')" width="360" fixed="right">
          <template #default="{ row }">
            <div class="action-buttons">
              <el-button type="success" size="small" @click="emit('verify-group', row)">
                <el-icon><VideoPlay /></el-icon>{{ t('verify') }}
              </el-button>
              <el-button type="primary" size="small" @click="emit('view-samples', row)">
                <el-icon><View /></el-icon>{{ t('manage_voiceprints') }}
              </el-button>
              <el-button type="primary" size="small" plain @click="emit('edit-group', row)">
                <el-icon><Edit /></el-icon>{{ t('edit') }}
              </el-button>
              <el-button type="danger" size="small" @click="emit('delete-group', row)">
                <el-icon><Delete /></el-icon>{{ t('delete') }}
              </el-button>
            </div>
          </template>
        </el-table-column>
      </el-table>
      <div v-if="filteredGroups.length === 0 && !loading" class="empty-state">
        <el-empty :description="t('no_voiceprint_groups')" />
      </div>
    </div>
  </div>
</template>

<script setup>
import { Search, Plus, VideoPlay, View, Edit, Delete } from '@element-plus/icons-vue'
import { useLocale } from '../../composables/useLocale'

const { t } = useLocale()

const props = defineProps({
  agents: { type: Array, default: () => [] },
  filteredGroups: { type: Array, default: () => [] },
  loading: { type: Boolean, default: false },
  formatDate: { type: Function, required: true },
  truncateText: { type: Function, required: true }
})

const filterAgentId = defineModel('filterAgentId', { default: '' })
const searchKeyword = defineModel('searchKeyword', { default: '' })

const emit = defineEmits(['filter-change', 'add-group', 'edit-group', 'delete-group', 'view-samples', 'verify-group'])
</script>

<style scoped>
.filter-bar {
  padding: 15px 20px;
  background: rgba(255, 255, 255, 0.88);
  border-radius: 8px;
  margin-bottom: 20px;
  display: flex;
  align-items: center;
  gap: 10px;
  flex-wrap: wrap;
}
.create-group-button { margin-left: auto; }
.speakers-content { background: rgba(255, 255, 255, 0.88); border-radius: 8px; padding: 20px; }
.prompt-text { color: #606266; cursor: pointer; }
.prompt-popover { max-height: 200px; overflow-y: auto; white-space: pre-wrap; word-break: break-word; }
.text-muted { color: #909399; }
.empty-state { padding: 40px 0; }
.action-buttons { display: flex; gap: 8px; flex-wrap: wrap; align-items: center; }
.action-buttons .el-button { margin: 0; white-space: nowrap; }
</style>
