// manager/frontend/src/views/Setup.vue
<template>
  <div class="setup-container">
    <div class="setup-shell">
      <section class="setup-intro">
        <p class="setup-eyebrow">FIRST RUN EXPERIENCE</p>
        <h1>{{ t('lighter_system_init') }}</h1>
        <p>{{ t('setup_admin_hint') }}</p>
      </section>

      <div class="setup-card">
        <div class="setup-header">
          <p class="setup-card-eyebrow">SYSTEM SETUP</p>
          <h1>{{ t('system_init') }}</h1>
          <p>{{ t('welcome_initial_setup') }}</p>
        </div>

        <div v-if="!initialized" class="setup-status">
          <div class="loading-spinner" v-if="checking">
            <div class="spinner"></div>
            <p>{{ t('checking_system_status') }}</p>
          </div>

          <div v-else-if="needsSetup" class="setup-form">
            <h2>{{ t('create_admin_account') }}</h2>
            <p>{{ t('set_admin_account_info') }}</p>

            <form @submit.prevent="initializeSystem">
              <div class="form-group">
                <label for="username">{{ t('admin_username') }}</label>
                <input
                  id="username"
                  v-model="form.admin_username"
                  type="text"
                  required
                  minlength="3"
                  maxlength="50"
                  :placeholder="t('enter_admin_username')"
                />
              </div>

              <div class="form-group">
                <label for="email">{{ t('admin_email') }}</label>
                <input
                  id="email"
                  v-model="form.admin_email"
                  type="email"
                  required
                  :placeholder="t('enter_admin_email')"
                />
              </div>

              <div class="form-group">
                <label for="password">{{ t('admin_password') }}</label>
                <input
                  id="password"
                  v-model="form.admin_password"
                  type="password"
                  required
                  minlength="6"
                  maxlength="100"
                  :placeholder="t('enter_admin_password_min6')"
                />
              </div>

              <div class="form-group">
                <label for="confirmPassword">{{ t('confirm_password') }}</label>
                <input
                  id="confirmPassword"
                  v-model="confirmPassword"
                  type="password"
                  required
                  :placeholder="t('enter_password_again')"
                />
              </div>

              <div class="error-message" v-if="errorMessage">
                {{ errorMessage }}
              </div>

              <button type="submit" :disabled="initializing" class="setup-btn">
                <span v-if="initializing">{{ t('initializing') }}</span>
                <span v-else>{{ t('start_init') }}</span>
              </button>
            </form>
          </div>

          <div v-else class="setup-complete">
            <div class="success-icon">
              <span class="success-badge">OK</span>
            </div>
            <h2>{{ t('system_initialized') }}</h2>
            <p>{{ t('system_init_login_prompt') }}</p>
            <router-link to="/login" class="login-btn">{{ t('go_to_login') }}</router-link>
          </div>
        </div>

        <div v-else class="setup-success">
          <div class="success-icon">
            <span class="success-badge">OK</span>
          </div>
          <h2>{{ t('init_success') }}</h2>
          <p>{{ t('system_init_admin_created') }}</p>
          <div class="admin-info">
            <p><strong>{{ t('username_label') }}</strong>{{ adminInfo.username }}</p>
            <p><strong>{{ t('email_label') }}</strong>{{ adminInfo.email }}</p>
          </div>
          <router-link to="/login" class="login-btn">{{ t('go_to_login') }}</router-link>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import api from '@/utils/api'
import { useLocale } from '@/composables/useLocale'

export default {
  name: 'Setup',
  setup() {
    const router = useRouter()
    const { t } = useLocale()
    const checking = ref(true)
    const needsSetup = ref(false)
    const initialized = ref(false)
    const initializing = ref(false)
    const errorMessage = ref('')
    
    const form = ref({
      admin_username: '',
      admin_email: '',
      admin_password: ''
    })
    
    const confirmPassword = ref('')
    const adminInfo = ref({})

    const checkSetupStatus = async () => {
      try {
        checking.value = true
        const response = await api.get('/setup/status')
        
        if (response.data.needs_setup) {
          needsSetup.value = true
        } else {
          // System already initialized — go to login
          router.push('/login')
        }
      } catch (error) {
        console.error(t('check_system_failed'), error)
        errorMessage.value = t('check_system_refresh')
      } finally {
        checking.value = false
      }
    }

    const initializeSystem = async () => {
      // Validate password confirmation
      if (form.value.admin_password !== confirmPassword.value) {
        errorMessage.value = t('passwords_inconsistent')
        return
      }

      try {
        initializing.value = true
        errorMessage.value = ''
        
        const response = await api.post('/setup/initialize', form.value)
        
        adminInfo.value = response.data.admin
        initialized.value = true
      } catch (error) {
        console.error(t('system_init_failed'), error)
        if (error.response?.data?.error) {
          errorMessage.value = error.response.data.error
        } else {
          errorMessage.value = t('system_init_retry')
        }
      } finally {
        initializing.value = false
      }
    }

    onMounted(() => {
      checkSetupStatus()
    })

    return {
      t,
      checking,
      needsSetup,
      initialized,
      initializing,
      errorMessage,
      form,
      confirmPassword,
      adminInfo,
      initializeSystem
    }
  }
}
</script>

<style scoped>
.setup-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 24px;
}

.setup-shell {
  width: min(1100px, 100%);
  display: grid;
  grid-template-columns: minmax(0, 1fr) 460px;
  gap: 24px;
  align-items: center;
}

.setup-intro {
  padding: 20px 8px;
}

.setup-eyebrow,
.setup-card-eyebrow {
  margin: 0 0 8px;
  color: var(--apple-primary);
  font-size: 11px;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.setup-intro h1 {
  margin: 0;
  font-size: 48px;
  line-height: 1.04;
  letter-spacing: -0.05em;
}

.setup-intro p {
  max-width: 560px;
  margin: 16px 0 0;
  color: var(--apple-text-secondary);
  font-size: 15px;
  line-height: 1.8;
}

.setup-card {
  background: rgba(255, 255, 255, 0.88);
  border-radius: 30px;
  border: 1px solid rgba(255, 255, 255, 0.9);
  box-shadow: var(--apple-shadow-lg);
  padding: 36px;
  width: 100%;
}

.setup-header {
  margin-bottom: 30px;
}

.setup-header h1 {
  color: var(--apple-text);
  margin-bottom: 10px;
  font-size: 30px;
  letter-spacing: -0.03em;
}

.setup-header p {
  color: var(--apple-text-secondary);
  font-size: 15px;
  line-height: 1.8;
}

.loading-spinner {
  text-align: center;
  padding: 40px 0;
}

.spinner {
  width: 40px;
  height: 40px;
  border: 4px solid rgba(0, 122, 255, 0.12);
  border-top: 4px solid var(--apple-primary);
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin: 0 auto 20px;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.setup-form h2 {
  color: var(--apple-text);
  margin-bottom: 10px;
  text-align: left;
}

.setup-form p {
  color: var(--apple-text-secondary);
  text-align: left;
  margin-bottom: 30px;
}

.form-group {
  margin-bottom: 20px;
}

.form-group label {
  display: block;
  margin-bottom: 8px;
  color: var(--apple-text);
  font-weight: 600;
}

.form-group input {
  width: 100%;
  padding: 14px 16px;
  border: 1px solid rgba(229, 229, 234, 0.9);
  border-radius: 16px;
  font-size: 16px;
  background: rgba(255, 255, 255, 0.96);
  transition: border-color var(--apple-transition-fast), box-shadow var(--apple-transition-fast);
  box-sizing: border-box;
}

.form-group input:focus {
  outline: none;
  border-color: rgba(0, 122, 255, 0.34);
  box-shadow: 0 0 0 4px rgba(0, 122, 255, 0.08);
}

.error-message {
  color: #8a1f19;
  background: rgba(255, 59, 48, 0.08);
  border: 1px solid rgba(255, 59, 48, 0.16);
  padding: 12px;
  border-radius: 16px;
  margin-bottom: 20px;
  font-size: 14px;
}

.setup-btn {
  width: 100%;
  padding: 14px;
  background: linear-gradient(180deg, #2e90ff 0%, #007aff 100%);
  color: white;
  border: none;
  border-radius: 16px;
  font-size: 16px;
  font-weight: 600;
  cursor: pointer;
  box-shadow: 0 14px 28px rgba(0, 122, 255, 0.2);
}

.setup-btn:hover:not(:disabled) {
  transform: translateY(-1px);
}

.setup-btn:disabled {
  background: #ccc;
  cursor: not-allowed;
}

.setup-complete,
.setup-success {
  text-align: center;
  padding: 40px 0;
}

.success-icon {
  display: flex;
  justify-content: center;
  margin-bottom: 20px;
}

.success-badge {
  width: 72px;
  height: 72px;
  border-radius: 24px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  color: var(--apple-primary);
  font-size: 20px;
  font-weight: 700;
  background: linear-gradient(180deg, #eff6ff 0%, #dcebff 100%);
}

.setup-complete h2,
.setup-success h2 {
  color: var(--apple-text);
  margin-bottom: 10px;
}

.setup-complete p,
.setup-success p {
  color: var(--apple-text-secondary);
  margin-bottom: 30px;
  line-height: 1.7;
}

.admin-info {
  background: rgba(248, 250, 252, 0.9);
  padding: 20px;
  border-radius: 20px;
  border: 1px solid rgba(229, 229, 234, 0.72);
  margin-bottom: 30px;
  text-align: left;
}

.admin-info p {
  margin: 8px 0;
  color: var(--apple-text);
}

.login-btn {
  display: inline-block;
  padding: 12px 24px;
  background: linear-gradient(180deg, #2e90ff 0%, #007aff 100%);
  color: white;
  text-decoration: none;
  border-radius: 16px;
  font-weight: 600;
  box-shadow: 0 14px 28px rgba(0, 122, 255, 0.2);
}

.login-btn:hover {
  transform: translateY(-1px);
}

@media (max-width: 960px) {
  .setup-shell {
    grid-template-columns: 1fr;
  }

  .setup-intro {
    padding: 0 0 8px;
  }

  .setup-intro h1 {
    font-size: 38px;
  }
}
</style>

// manager/frontend/src/routes/setup.tsx
import { useState, useEffect } from 'react'
import { createFileRoute, Link, useRouter } from '@tanstack/react-router'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { CheckCircle, Loader2 } from 'lucide-react'
import api from '@/utils/api'
import { useLocale } from '@/hooks/use-locale'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form'

interface AdminInfo { username: string; email: string }

function SetupPage() {
  const { t } = useLocale()
  const router = useRouter()
  const [checking, setChecking] = useState(true)
  const [needsSetup, setNeedsSetup] = useState(false)
  const [initialized, setInitialized] = useState(false)
  const [adminInfo, setAdminInfo] = useState<AdminInfo | null>(null)
  const [errorMessage, setErrorMessage] = useState('')

  const schema = z.object({
    admin_username: z.string().min(3, t('enter_admin_username')).max(50),
    admin_email: z.string().min(1, t('enter_admin_email')).email(t('enter_valid_email')),
    admin_password: z.string().min(6, t('enter_admin_password_min6')).max(100),
    confirmPassword: z.string().min(1, t('enter_password_again')),
  }).refine((d) => d.admin_password === d.confirmPassword, {
    message: t('passwords_inconsistent'), path: ['confirmPassword'],
  })

  const form = useForm<z.infer<typeof schema>>({ resolver: zodResolver(schema) })

  useEffect(() => {
    api.get<{ needs_setup: boolean }>('/setup/status')
      .then(({ data }) => {
        if (data.needs_setup) setNeedsSetup(true)
        else router.navigate({ to: '/login' })
      })
      .catch(() => setErrorMessage(t('check_system_refresh')))
      .finally(() => setChecking(false))
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  const onSubmit = form.handleSubmit(async (values) => {
    setErrorMessage('')
    try {
      const { data } = await api.post<{ admin: AdminInfo }>('/setup/initialize', {
        admin_username: values.admin_username,
        admin_email: values.admin_email,
        admin_password: values.admin_password,
      })
      setAdminInfo(data.admin)
      setInitialized(true)
    } catch (err: unknown) {
      const e = err as { response?: { data?: { error?: string } } }
      setErrorMessage(e.response?.data?.error || t('system_init_retry'))
    }
  })

  return (
    <div className="min-h-screen flex items-center justify-center bg-[var(--color-bg)] p-6">
      <div className="w-full max-w-5xl grid lg:grid-cols-[1fr_460px] gap-6 items-center">
        <section className="hidden lg:block px-4 py-6">
          <p className="text-[11px] font-bold tracking-widest text-[var(--color-primary)] uppercase mb-2">FIRST RUN EXPERIENCE</p>
          <h1 className="text-5xl font-bold font-display tracking-tight leading-tight text-[var(--color-text)] mb-4">{t('lighter_system_init')}</h1>
          <p className="text-[var(--color-text-secondary)] leading-relaxed max-w-lg text-[15px]">{t('setup_admin_hint')}</p>
        </section>

        <Card className="w-full">
          <CardHeader className="pb-2">
            <p className="text-[11px] font-bold tracking-widest text-[var(--color-primary)] uppercase mb-1">SYSTEM SETUP</p>
            <h2 className="text-2xl font-bold font-display tracking-tight text-[var(--color-text)]">{t('system_init')}</h2>
            <p className="text-[var(--color-text-secondary)] text-[15px] leading-relaxed">{t('welcome_initial_setup')}</p>
          </CardHeader>
          <CardContent>
            {checking ? (
              <div className="flex flex-col items-center py-12 gap-4">
                <Loader2 className="w-8 h-8 animate-spin text-[var(--color-primary)]" />
                <p className="text-[var(--color-text-secondary)]">{t('checking_system_status')}</p>
              </div>
            ) : initialized ? (
              <div className="flex flex-col items-center py-10 text-center gap-4">
                <CheckCircle className="w-16 h-16 text-[var(--color-primary)]" />
                <h3 className="text-xl font-semibold text-[var(--color-text)]">{t('init_success')}</h3>
                <p className="text-[var(--color-text-secondary)] leading-relaxed">{t('system_init_admin_created')}</p>
                <div className="w-full bg-[var(--color-surface-2)] rounded-lg border border-[var(--color-line)] p-4 text-left space-y-1">
                  <p className="text-[var(--color-text)] text-sm"><strong>{t('username_label')}</strong> {adminInfo?.username}</p>
                  <p className="text-[var(--color-text)] text-sm"><strong>{t('email_label')}</strong> {adminInfo?.email}</p>
                </div>
                <Button asChild className="mt-2"><Link to="/login">{t('go_to_login')}</Link></Button>
              </div>
            ) : !needsSetup ? (
              <div className="flex flex-col items-center py-10 text-center gap-4">
                <CheckCircle className="w-16 h-16 text-[var(--color-primary)]" />
                <h3 className="text-xl font-semibold text-[var(--color-text)]">{t('system_initialized')}</h3>
                <p className="text-[var(--color-text-secondary)] leading-relaxed">{t('system_init_login_prompt')}</p>
                <Button asChild><Link to="/login">{t('go_to_login')}</Link></Button>
              </div>
            ) : (
              <div>
                <h3 className="text-lg font-semibold text-[var(--color-text)] mb-1">{t('create_admin_account')}</h3>
                <p className="text-[var(--color-text-secondary)] text-sm mb-6">{t('set_admin_account_info')}</p>
                <Form {...form}>
                  <form onSubmit={onSubmit} className="space-y-4">
                    <FormField control={form.control} name="admin_username" render={({ field }) => (
                      <FormItem><FormLabel>{t('admin_username')}</FormLabel><FormControl><Input {...field} placeholder={t('enter_admin_username')} autoComplete="username" /></FormControl><FormMessage /></FormItem>
                    )} />
                    <FormField control={form.control} name="admin_email" render={({ field }) => (
                      <FormItem><FormLabel>{t('admin_email')}</FormLabel><FormControl><Input {...field} type="email" autoComplete="email" placeholder={t('enter_admin_email')} /></FormControl><FormMessage /></FormItem>
                    )} />
                    <FormField control={form.control} name="admin_password" render={({ field }) => (
                      <FormItem><FormLabel>{t('admin_password')}</FormLabel><FormControl><Input {...field} type="password" autoComplete="new-password" placeholder={t('enter_admin_password_min6')} /></FormControl><FormMessage /></FormItem>
                    )} />
                    <FormField control={form.control} name="confirmPassword" render={({ field }) => (
                      <FormItem><FormLabel>{t('confirm_password')}</FormLabel><FormControl><Input {...field} type="password" autoComplete="new-password" placeholder={t('enter_password_again')} /></FormControl><FormMessage /></FormItem>
                    )} />
                    {errorMessage && (
                      <div className="text-sm text-[var(--color-danger)] bg-[var(--color-danger)]/10 border border-[var(--color-danger)]/20 rounded-lg px-3 py-2">{errorMessage}</div>
                    )}
                    <Button type="submit" className="w-full" disabled={form.formState.isSubmitting}>
                      {form.formState.isSubmitting && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                      {form.formState.isSubmitting ? t('initializing') : t('start_init')}
                    </Button>
                  </form>
                </Form>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

export const Route = createFileRoute('/setup')({
  component: SetupPage,
})
