// manager/frontend/src/components/user/MessageInjectDialog.vue
<template>
  <el-dialog
    v-model="visible"
    :title="t('voice_push')"
    width="620px"
    class="inject-message-dialog"
    :close-on-click-modal="false"
    @closed="resetForm"
  >
    <el-form
      ref="formRef"
      :model="form"
      :rules="rules"
      label-position="top"
    >
      <el-form-item :label="t('select_device_prompt')" prop="device_id">
        <el-select
          v-model="form.device_id"
          :placeholder="t('select_push_voice_device')"
          style="width: 100%"
          filterable
          :disabled="deviceSelectDisabled"
          popper-class="inject-device-select-popper"
        >
          <el-option
            v-for="device in devices"
            :key="device.id || device.device_code"
            :label="getDeviceOptionLabel(device)"
            :value="device.device_name || ''"
          >
            <div class="device-option">
              <div class="device-option-header">
                <span class="device-name">{{ getDeviceNickName(device) }}</span>
                <el-tag :type="isDeviceOnline(device.last_active_at) ? 'success' : 'danger'" size="small">
                  {{ isDeviceOnline(device.last_active_at) ? t('online') : t('offline') }}
                </el-tag>
              </div>
              <div class="device-code">{{ t('device_id_display', { id: getDeviceIdText(device) }) }}</div>
              <div v-if="device.device_code" class="device-code">{{ t('activation_code_display', { code: device.device_code }) }}</div>
              <div class="device-agent">{{ t('agent_name_display', { name: device.agent_name || t('not_bound') }) }}</div>
            </div>
          </el-option>
        </el-select>
      </el-form-item>

      <el-form-item :label="t('push_content')" prop="message">
        <el-input
          v-model="form.message"
          type="textarea"
          :rows="4"
          :placeholder="t('enter_broadcast_content')"
          maxlength="500"
          show-word-limit
        />
      </el-form-item>

      <el-form-item :label="t('direct_broadcast')" prop="skip_llm">
        <div class="switch-field">
          <div class="switch-copy">
            <div class="switch-title">{{ directPlayback ? t('enable') : t('close') }}</div>
            <div class="switch-desc">
              {{ directPlayback ? t('msg_direct_tts') : t('msg_via_llm') }}
            </div>
          </div>
          <el-switch
            v-model="directPlayback"
            inline-prompt
            active-:text="t('enable')"
            :inactive-text="t('close')"
          />
        </div>
      </el-form-item>

      <el-form-item :label="t('switch_to_idle')" prop="auto_listen">
        <div class="switch-field">
          <div class="switch-copy">
            <div class="switch-title">{{ returnToIdleAfterPlayback ? t('enable') : t('close') }}</div>
            <div class="switch-desc">
              {{ returnToIdleAfterPlayback ? t('broadcast_return_idle') : t('broadcast_continue_listen') }}
            </div>
          </div>
          <el-switch
            v-model="returnToIdleAfterPlayback"
            inline-prompt
            active-:text="t('enable')"
            :inactive-text="t('close')"
          />
        </div>
      </el-form-item>
    </el-form>

    <template #footer>
      <div class="dialog-footer">
        <el-button @click="handleClose">{{ t('cancel') }}</el-button>
        <el-button type="primary" :loading="submitting" @click="handleSubmit">
          {{ submitting ? t('pushing') : t('voice_push') }}
        </el-button>
      </div>
    </template>
  </el-dialog>
</template>

<script setup>
import { computed, reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import api from '../../utils/api'
import { useLocale } from '../../composables/useLocale'

const { t } = useLocale()

const props = defineProps({
  modelValue: {
    type: Boolean,
    default: false
  },
  devices: {
    type: Array,
    default: () => []
  },
  defaultDeviceId: {
    type: String,
    default: ''
  },
  lockDevice: {
    type: Boolean,
    default: false
  }
})

const emit = defineEmits(['update:modelValue', 'success'])

const formRef = ref()
const submitting = ref(false)
const visible = computed({
  get: () => props.modelValue,
  set: (value) => emit('update:modelValue', value)
})

const directPlayback = computed({
  get: () => form.skip_llm,
  set: (value) => {
    form.skip_llm = value
  }
})

const returnToIdleAfterPlayback = computed({
  get: () => !form.auto_listen,
  set: (value) => {
    form.auto_listen = !value
  }
})

const deviceSelectDisabled = computed(() => props.lockDevice && !!props.defaultDeviceId)

const form = reactive({
  device_id: '',
  message: '',
  skip_llm: false,
  auto_listen: true
})

const rules = {
  device_id: [
    { required: true, message: t('select_device'), trigger: 'change' }
  ],
  message: [
    { required: true, message: t('enter_push_content'), trigger: 'blur' },
    { min: 1, max: 500, message: t('push_content_length'), trigger: 'blur' }
  ]
}

const isDeviceOnline = (lastActiveAt) => {
  if (!lastActiveAt) return false
  const lastActive = new Date(lastActiveAt)
  return (Date.now() - lastActive.getTime()) < 5 * 60 * 1000
}

const getDeviceNickName = (device) => {
  const nickName = String(device?.nick_name || '').trim()
  if (nickName) return nickName
  return String(device?.device_name || '').trim() || t('unnamed_device')
}

const getDeviceIdText = (device) => String(device?.device_name || '').trim() || '-'

const getDeviceOptionLabel = (device) => {
  const nickName = getDeviceNickName(device)
  const deviceId = getDeviceIdText(device)
  return `${nickName} (${deviceId})`
}

const resetForm = () => {
  form.device_id = props.defaultDeviceId || ''
  form.message = ''
  form.skip_llm = false
  form.auto_listen = true
  formRef.value?.clearValidate?.()
}

watch(
  () => [props.modelValue, props.defaultDeviceId],
  ([visible]) => {
    if (!visible) return
    resetForm()
  }
)

const closeDialog = () => {
  visible.value = false
}

const handleSubmit = async () => {
  if (!formRef.value) return

  try {
    await formRef.value.validate()
  } catch {
    return
  }

  submitting.value = true
  try {
    const response = await api.post('/user/devices/inject-message', {
      device_id: form.device_id,
      message: form.message,
      skip_llm: form.skip_llm,
      auto_listen: form.auto_listen
    })
    if (response.data?.success) {
      ElMessage.success(t('voice_push_success'))
      emit('success', response.data?.data || null)
      closeDialog()
    }
  } catch (error) {
    ElMessage.error(error.response?.data?.error || t('voice_push_failed'))
  } finally {
    submitting.value = false
  }
}

const handleClose = () => {
  resetForm()
  closeDialog()
}
</script>

<style scoped>
.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 10px;
}

.device-option {
  padding: 8px 0;
}

.device-option-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 4px;
  gap: 12px;
}

.device-name {
  font-weight: 600;
  color: var(--apple-text);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.device-code,
.device-agent {
  font-size: 12px;
  color: rgba(107, 114, 128, 0.72);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.switch-field {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  width: 100%;
  padding: 14px 16px;
  border-radius: 18px;
  background: rgba(248, 250, 252, 0.9);
  border: 1px solid rgba(229, 229, 234, 0.72);
}

.switch-copy {
  display: flex;
  flex-direction: column;
  gap: 4px;
  min-width: 0;
}

.switch-title {
  font-size: 14px;
  font-weight: 600;
  color: var(--apple-text);
}

.switch-desc {
  font-size: 12px;
  line-height: 1.5;
  color: var(--apple-text-secondary);
}

:deep(.inject-device-select-popper .el-select-dropdown__item) {
  height: auto;
  line-height: 1.4;
  padding-top: 8px;
  padding-bottom: 8px;
  white-space: normal;
}

@media (max-width: 768px) {
  .dialog-footer {
    flex-wrap: wrap;
  }

  .dialog-footer .el-button {
    flex: 1;
    min-width: 120px;
  }

  .switch-field {
    align-items: flex-start;
  }
}
</style>

// manager/frontend/src/components/devices/message-inject-dialog.tsx
import { useEffect, useState } from 'react'
import { toast } from 'sonner'
import { devicesApi } from '@/features/devices/api/devices-api'
import { getDeviceDisplayName, isDeviceOnline } from '@/features/devices/types'
import type { Device } from '@/features/devices/types'
import { useLocale } from '@/hooks/use-locale'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Switch } from '@/components/ui/switch'
import { Textarea } from '@/components/ui/textarea'
import { cn } from '@/lib/utils'

interface MessageInjectDialogProps {
  open: boolean
  onOpenChange: (v: boolean) => void
  devices: Device[]
  defaultDeviceId?: string
  lockDevice?: boolean
  onSuccess?: () => void
}

export function MessageInjectDialog({ open, onOpenChange, devices, defaultDeviceId, lockDevice, onSuccess }: MessageInjectDialogProps) {
  const { t } = useLocale()

  const [deviceId, setDeviceId] = useState(defaultDeviceId || '')
  const [message, setMessage] = useState('')
  const [skipLlm, setSkipLlm] = useState(false)
  const [autoListen, setAutoListen] = useState(true)
  const [submitting, setSubmitting] = useState(false)

  useEffect(() => {
    if (open) {
      setDeviceId(defaultDeviceId || '')
      setMessage('')
      setSkipLlm(false)
      setAutoListen(true)
    }
  }, [open, defaultDeviceId])

  const handleSubmit = async () => {
    if (!deviceId) { toast.error(t('select_device')); return }
    if (!message.trim()) { toast.error(t('enter_push_content')); return }
    setSubmitting(true)
    try {
      await devicesApi.injectMessage({ device_id: deviceId, message, skip_llm: skipLlm, auto_listen: autoListen })
      toast.success(t('voice_push_success'))
      onSuccess?.()
      onOpenChange(false)
    } catch (e) { toast.error((e as Error).message || t('voice_push_failed')) }
    finally { setSubmitting(false) }
  }

  const deviceSelectDisabled = lockDevice && !!defaultDeviceId

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-[560px]">
        <DialogHeader>
          <DialogTitle>{t('voice_push')}</DialogTitle>
        </DialogHeader>

        <div className="grid gap-4 py-2">
          <div className="grid gap-1.5">
            <label className="text-sm font-medium text-[var(--color-text)]">{t('select_device_prompt')}</label>
            <Select value={deviceId} onValueChange={setDeviceId} disabled={deviceSelectDisabled}>
              <SelectTrigger className="w-full">
                <SelectValue placeholder={t('select_push_voice_device')} />
              </SelectTrigger>
              <SelectContent>
                {devices.map((d) => {
                  const online = isDeviceOnline(d.last_active_at)
                  return (
                    <SelectItem key={d.id} value={d.device_name || ''}>
                      <div className="flex items-center justify-between gap-3 w-full">
                        <span className="font-medium truncate">{getDeviceDisplayName(d)}</span>
                        <span className={cn('text-[10px] px-1.5 py-0.5 rounded-full border font-medium', online ? 'status-success' : 'status-danger')}>
                          {online ? t('online') : t('offline')}
                        </span>
                      </div>
                    </SelectItem>
                  )
                })}
              </SelectContent>
            </Select>
          </div>

          <div className="grid gap-1.5">
            <label className="text-sm font-medium text-[var(--color-text)]">{t('push_content')}</label>
            <Textarea
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              placeholder={t('enter_broadcast_content')}
              maxLength={500}
              rows={4}
            />
            <p className="text-xs text-[var(--color-text-tertiary)] text-right">{message.length}/500</p>
          </div>

          <div className="flex items-center justify-between gap-4 px-4 py-3 rounded-xl bg-[var(--color-surface-2)] border border-[var(--color-line)]">
            <div>
              <p className="text-sm font-semibold text-[var(--color-text)]">{t('direct_broadcast')} — {skipLlm ? t('enable') : t('close')}</p>
              <p className="text-xs text-[var(--color-text-secondary)] mt-0.5">{skipLlm ? t('msg_direct_tts') : t('msg_via_llm')}</p>
            </div>
            <Switch checked={skipLlm} onCheckedChange={setSkipLlm} />
          </div>

          <div className="flex items-center justify-between gap-4 px-4 py-3 rounded-xl bg-[var(--color-surface-2)] border border-[var(--color-line)]">
            <div>
              <p className="text-sm font-semibold text-[var(--color-text)]">{t('switch_to_idle')} — {!autoListen ? t('enable') : t('close')}</p>
              <p className="text-xs text-[var(--color-text-secondary)] mt-0.5">{!autoListen ? t('broadcast_return_idle') : t('broadcast_continue_listen')}</p>
            </div>
            <Switch checked={!autoListen} onCheckedChange={(v) => setAutoListen(!v)} />
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>{t('cancel')}</Button>
          <Button disabled={submitting} onClick={handleSubmit}>
            {submitting ? t('pushing') : t('voice_push')}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
