// manager/frontend/src/components/admin/asr-config-form.tsx
import { useEffect, useState } from 'react'
import { useLocale } from '@/hooks/use-locale'
import { Input } from '@/components/ui/input'
import { Switch } from '@/components/ui/switch'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import type { ConfigRow, ConfigForm } from './config-list-page'

interface AsrFields {
  provider: string; name: string; config_id: string; enabled: boolean; is_default: boolean
  funasr_host: string; funasr_port: number; funasr_mode: string; funasr_sample_rate: number
  funasr_chunk0: number; funasr_chunk1: number; funasr_chunk2: number
  funasr_chunk_interval: number; funasr_max_connections: number; funasr_timeout: number; funasr_auto_end: boolean
  aliyun_api_key: string; aliyun_ws_url: string; aliyun_model: string; aliyun_format: string
  aliyun_sample_rate: number; aliyun_language_hints: string; aliyun_vocabulary_id: string
  aliyun_disfluency: boolean; aliyun_timeout: number
  doubao_appid: string; doubao_token: string; doubao_ws_url: string; doubao_resource_id: string
  doubao_end_window: number; doubao_punc: boolean; doubao_itn: boolean; doubao_ddc: boolean
  doubao_chunk_duration: number; doubao_timeout: number
  qwen3_api_key: string; qwen3_ws_url: string; qwen3_model: string; qwen3_format: string
  qwen3_sample_rate: number; qwen3_language: string; qwen3_auto_end: boolean
  qwen3_vad_threshold: number; qwen3_vad_silence_ms: number; qwen3_timeout: number
  xunfei_appid: string; xunfei_api_key: string; xunfei_api_secret: string
  xunfei_host: string; xunfei_path: string; xunfei_domain: string; xunfei_language: string
  xunfei_accent: string; xunfei_sample_rate: number; xunfei_timeout: number
}

const D: AsrFields = {
  provider:'funasr', name:'', config_id:'', enabled:true, is_default:false,
  funasr_host:'127.0.0.1', funasr_port:10095, funasr_mode:'offline', funasr_sample_rate:16000,
  funasr_chunk0:5, funasr_chunk1:10, funasr_chunk2:5, funasr_chunk_interval:10, funasr_max_connections:100, funasr_timeout:30, funasr_auto_end:false,
  aliyun_api_key:'', aliyun_ws_url:'wss://dashscope.aliyuncs.com/api-ws/v1/inference/', aliyun_model:'fun-asr-realtime', aliyun_format:'pcm', aliyun_sample_rate:16000, aliyun_language_hints:'zh', aliyun_vocabulary_id:'', aliyun_disfluency:false, aliyun_timeout:30,
  doubao_appid:'', doubao_token:'', doubao_ws_url:'wss://openspeech.bytedance.com/api/v3/sauc/bigmodel_async', doubao_resource_id:'volc.bigasr.sauc.duration', doubao_end_window:800, doubao_punc:true, doubao_itn:true, doubao_ddc:false, doubao_chunk_duration:200, doubao_timeout:30,
  qwen3_api_key:'', qwen3_ws_url:'wss://dashscope.aliyuncs.com/api-ws/v1/realtime', qwen3_model:'qwen3-asr-flash-realtime', qwen3_format:'pcm', qwen3_sample_rate:16000, qwen3_language:'zh', qwen3_auto_end:false, qwen3_vad_threshold:0.3, qwen3_vad_silence_ms:500, qwen3_timeout:30,
  xunfei_appid:'', xunfei_api_key:'', xunfei_api_secret:'', xunfei_host:'iat-api.xfyun.cn', xunfei_path:'/v2/iat', xunfei_domain:'iat', xunfei_language:'zh_cn', xunfei_accent:'mandarin', xunfei_sample_rate:16000, xunfei_timeout:30,
}

function parse(row: ConfigRow | null): AsrFields {
  if (!row) return { ...D }
  try {
    const d = JSON.parse(row.json_data || '{}')
    const prov = row.provider || 'funasr'
    const cs = Array.isArray(d.chunk_size) && d.chunk_size.length >= 3 ? d.chunk_size : [5,10,5]
    return {
      ...D, provider:prov, name:row.name, config_id:row.config_id, enabled:row.enabled!==false, is_default:!!row.is_default,
      funasr_host:d.host||'127.0.0.1', funasr_port:d.port||10095, funasr_mode:d.mode||'offline', funasr_sample_rate:d.sample_rate||16000,
      funasr_chunk0:cs[0], funasr_chunk1:cs[1], funasr_chunk2:cs[2], funasr_chunk_interval:d.chunk_interval||10, funasr_max_connections:d.max_connections||100, funasr_timeout:d.timeout||30, funasr_auto_end:!!d.auto_end,
      aliyun_api_key:d.api_key||'', aliyun_ws_url:d.ws_url||D.aliyun_ws_url, aliyun_model:d.model||'fun-asr-realtime', aliyun_format:d.format||'pcm', aliyun_sample_rate:d.sample_rate||16000, aliyun_language_hints:Array.isArray(d.language_hints)?d.language_hints.join(','):(d.language_hints||'zh'), aliyun_vocabulary_id:d.vocabulary_id||'', aliyun_disfluency:!!d.disfluency_removal_enabled, aliyun_timeout:d.timeout||30,
      doubao_appid:d.appid||'', doubao_token:d.access_token||'', doubao_ws_url:d.ws_url||D.doubao_ws_url, doubao_resource_id:d.resource_id||'volc.bigasr.sauc.duration', doubao_end_window:d.end_window_size||800, doubao_punc:d.enable_punc!==false, doubao_itn:d.enable_itn!==false, doubao_ddc:!!d.enable_ddc, doubao_chunk_duration:d.chunk_duration||200, doubao_timeout:d.timeout||30,
      qwen3_api_key:d.api_key||'', qwen3_ws_url:d.ws_url||D.qwen3_ws_url, qwen3_model:d.model||'qwen3-asr-flash-realtime', qwen3_format:d.format||'pcm', qwen3_sample_rate:d.sample_rate||16000, qwen3_language:d.language||'zh', qwen3_auto_end:!!d.auto_end, qwen3_vad_threshold:d.vad_threshold??0.3, qwen3_vad_silence_ms:d.vad_silence_ms||500, qwen3_timeout:d.timeout||30,
      xunfei_appid:d.appid||'', xunfei_api_key:d.api_key||'', xunfei_api_secret:d.api_secret||'', xunfei_host:d.host||'iat-api.xfyun.cn', xunfei_path:d.path||'/v2/iat', xunfei_domain:d.domain||'iat', xunfei_language:d.language||'zh_cn', xunfei_accent:d.accent||'mandarin', xunfei_sample_rate:d.sample_rate||16000, xunfei_timeout:d.timeout||30,
    }
  } catch { return { ...D } }
}

function serialize(f: AsrFields): string {
  const p = f.provider
  if (p==='funasr') return JSON.stringify({host:f.funasr_host,port:f.funasr_port,mode:f.funasr_mode,sample_rate:f.funasr_sample_rate,chunk_size:[f.funasr_chunk0,f.funasr_chunk1,f.funasr_chunk2],chunk_interval:f.funasr_chunk_interval,max_connections:f.funasr_max_connections,timeout:f.funasr_timeout,auto_end:f.funasr_auto_end})
  if (p==='aliyun_funasr') return JSON.stringify({api_key:f.aliyun_api_key,ws_url:f.aliyun_ws_url,model:f.aliyun_model,format:f.aliyun_format,sample_rate:f.aliyun_sample_rate,language_hints:f.aliyun_language_hints.split(',').map(s=>s.trim()).filter(Boolean),vocabulary_id:f.aliyun_vocabulary_id,disfluency_removal_enabled:f.aliyun_disfluency,timeout:f.aliyun_timeout})
  if (p==='doubao') return JSON.stringify({appid:f.doubao_appid,access_token:f.doubao_token,ws_url:f.doubao_ws_url,resource_id:f.doubao_resource_id,end_window_size:f.doubao_end_window,enable_punc:f.doubao_punc,enable_itn:f.doubao_itn,enable_ddc:f.doubao_ddc,chunk_duration:f.doubao_chunk_duration,timeout:f.doubao_timeout})
  if (p==='aliyun_qwen3') return JSON.stringify({api_key:f.qwen3_api_key,ws_url:f.qwen3_ws_url,model:f.qwen3_model,format:f.qwen3_format,sample_rate:f.qwen3_sample_rate,language:f.qwen3_language,auto_end:f.qwen3_auto_end,vad_threshold:f.qwen3_vad_threshold,vad_silence_ms:f.qwen3_vad_silence_ms,timeout:f.qwen3_timeout})
  if (p==='xunfei') return JSON.stringify({appid:f.xunfei_appid,api_key:f.xunfei_api_key,api_secret:f.xunfei_api_secret,host:f.xunfei_host,path:f.xunfei_path,domain:f.xunfei_domain,language:f.xunfei_language,accent:f.xunfei_accent,sample_rate:f.xunfei_sample_rate,timeout:f.xunfei_timeout})
  return '{}'
}

const F = ({ label, children }: { label: string; children: React.ReactNode }) => (
  <div className="grid gap-1.5"><label className="text-sm font-medium text-[var(--color-text)]">{label}</label>{children}</div>
)
const N = ({ v, min, max, step, onChange }: { v: number; min?: number; max?: number; step?: number; onChange: (n: number) => void }) => (
  <Input type="number" value={v} min={min} max={max} step={step} onChange={e => onChange(Number(e.target.value))} />
)

const ASR_PROVIDERS = [
  { label:'FunASR', value:'funasr' },
  { label:'aliyun_funasr_asr', value:'aliyun_funasr', labelKey:true },
  { label:'doubao_asr', value:'doubao', labelKey:true },
  { label:'aliyun_qwen3_asr', value:'aliyun_qwen3', labelKey:true },
  { label:'xunfei', value:'xunfei', labelKey:true },
]

export function AsrConfigForm({ form, setForm, editing }: { form: ConfigForm; setForm: (p: Partial<ConfigForm>) => void; editing: ConfigRow | null }) {
  const { t } = useLocale()
  const [f, setF] = useState<AsrFields>(() => parse(editing))
  useEffect(() => { const parsed = parse(editing); setF(parsed) }, [editing])

  const upd = (patch: Partial<AsrFields>) => {
    const next = { ...f, ...patch }
    setF(next)
    setForm({ name: next.name, config_id: next.config_id, provider: next.provider, enabled: next.enabled, is_default: next.is_default, json_data: serialize(next) })
  }

  const p = f.provider
  return (
    <div className="grid gap-3">
      <F label={t('provider')}>
        <Select value={p} onValueChange={v => upd({ provider: v })}>
          <SelectTrigger><SelectValue /></SelectTrigger>
          <SelectContent>{ASR_PROVIDERS.map(o => <SelectItem key={o.value} value={o.value}>{o.labelKey ? t(o.label) : o.label}</SelectItem>)}</SelectContent>
        </Select>
      </F>
      <div className="grid grid-cols-2 gap-3">
        <F label={t('config_name')}><Input value={f.name} onChange={e => upd({ name: e.target.value })} placeholder={t('enter_config_name')} /></F>
        <F label={t('config_id')}><Input value={f.config_id} onChange={e => upd({ config_id: e.target.value })} placeholder={t('enter_unique_config_id')} /></F>
      </div>
      {p==='funasr' && <>
        <div className="grid grid-cols-2 gap-3">
          <F label={t('host_address')}><Input value={f.funasr_host} onChange={e => upd({ funasr_host: e.target.value })} /></F>
          <F label={t('port')}><N v={f.funasr_port} min={1} max={65535} onChange={v => upd({ funasr_port: v })} /></F>
        </div>
        <div className="grid grid-cols-2 gap-3">
          <F label={t('mode')}>
            <Select value={f.funasr_mode} onValueChange={v => upd({ funasr_mode: v })}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>{['2pass','offline','online'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent>
            </Select>
          </F>
          <F label={t('sample_rate')}>
            <Select value={String(f.funasr_sample_rate)} onValueChange={v => upd({ funasr_sample_rate: Number(v) })}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>{[8000,16000,44100,48000].map(v=><SelectItem key={v} value={String(v)}>{v}</SelectItem>)}</SelectContent>
            </Select>
          </F>
        </div>
        <F label={t('chunk_size')}>
          <div className="flex gap-2">
            <N v={f.funasr_chunk0} min={1} onChange={v => upd({ funasr_chunk0: v })} />
            <N v={f.funasr_chunk1} min={1} onChange={v => upd({ funasr_chunk1: v })} />
            <N v={f.funasr_chunk2} min={1} onChange={v => upd({ funasr_chunk2: v })} />
          </div>
          <p className="text-xs text-[var(--color-text-secondary)]">{t('frame_size_format_hint')}</p>
        </F>
        <div className="grid grid-cols-3 gap-3">
          <F label={t('chunk_interval')}><N v={f.funasr_chunk_interval} min={1} onChange={v => upd({ funasr_chunk_interval: v })} /></F>
          <F label={t('max_connections')}><N v={f.funasr_max_connections} min={1} onChange={v => upd({ funasr_max_connections: v })} /></F>
          <F label={t('timeout_seconds')}><N v={f.funasr_timeout} min={1} onChange={v => upd({ funasr_timeout: v })} /></F>
        </div>
        <label className="flex items-center gap-2 cursor-pointer"><Switch checked={f.funasr_auto_end} onCheckedChange={v => upd({ funasr_auto_end: v })} /><span className="text-sm">{t('auto_end')}</span></label>
      </>}
      {p==='aliyun_funasr' && <>
        <F label="API Key"><Input type="password" value={f.aliyun_api_key} onChange={e => upd({ aliyun_api_key: e.target.value })} placeholder={t('optional_dashscope_key')} /></F>
        <F label="WS URL"><Input value={f.aliyun_ws_url} onChange={e => upd({ aliyun_ws_url: e.target.value })} /></F>
        <div className="grid grid-cols-2 gap-3">
          <F label={t('model')}><Input value={f.aliyun_model} onChange={e => upd({ aliyun_model: e.target.value })} placeholder="fun-asr-realtime" /></F>
          <F label={t('timeout_seconds')}><N v={f.aliyun_timeout} min={1} onChange={v => upd({ aliyun_timeout: v })} /></F>
        </div>
        <F label={t('language_hint')}><Input value={f.aliyun_language_hints} onChange={e => upd({ aliyun_language_hints: e.target.value })} placeholder="zh,en" /></F>
        <div className="grid grid-cols-2 gap-3">
          <F label={t('vocab_id')}><Input value={f.aliyun_vocabulary_id} onChange={e => upd({ aliyun_vocabulary_id: e.target.value })} placeholder={t('optional_empty') ?? ''} /></F>
          <F label={t('sample_rate')}>
            <Select value={String(f.aliyun_sample_rate)} onValueChange={v => upd({ aliyun_sample_rate: Number(v) })}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent><SelectItem value="16000">16000</SelectItem></SelectContent>
            </Select>
          </F>
        </div>
        <label className="flex items-center gap-2 cursor-pointer"><Switch checked={f.aliyun_disfluency} onCheckedChange={v => upd({ aliyun_disfluency: v })} /><span className="text-sm">{t('remove_filler_words')}</span></label>
      </>}
      {p==='doubao' && <>
        <F label={t('app_id')}><Input value={f.doubao_appid} onChange={e => upd({ doubao_appid: e.target.value })} /></F>
        <F label={t('access_token')}><Input type="password" value={f.doubao_token} onChange={e => upd({ doubao_token: e.target.value })} /></F>
        <F label="WebSocket URL"><Input value={f.doubao_ws_url} onChange={e => upd({ doubao_ws_url: e.target.value })} /></F>
        <F label={t('resource_spec')}>
          <Select value={f.doubao_resource_id} onValueChange={v => upd({ doubao_resource_id: v })}>
            <SelectTrigger><SelectValue /></SelectTrigger>
            <SelectContent>{[['volc.bigasr.sauc.duration','doubao_stream_asr_v1_hourly'],['volc.bigasr.sauc.concurrent','doubao_stream_asr_v1_concurrent'],['volc.seedasr.sauc.duration','doubao_stream_asr_v2_hourly'],['volc.seedasr.sauc.concurrent','doubao_stream_asr_v2_concurrent']].map(([v,k])=><SelectItem key={v} value={v}>{t(k)}</SelectItem>)}</SelectContent>
          </Select>
        </F>
        <div className="grid grid-cols-2 gap-3">
          <F label={t('end_window_size')}><N v={f.doubao_end_window} min={1} onChange={v => upd({ doubao_end_window: v })} /></F>
          <F label={t('timeout_seconds')}><N v={f.doubao_timeout} min={1} onChange={v => upd({ doubao_timeout: v })} /></F>
        </div>
        <div className="flex gap-4">
          <label className="flex items-center gap-2 cursor-pointer"><Switch checked={f.doubao_punc} onCheckedChange={v => upd({ doubao_punc: v })} /><span className="text-sm">{t('enable_punctuation')}</span></label>
          <label className="flex items-center gap-2 cursor-pointer"><Switch checked={f.doubao_itn} onCheckedChange={v => upd({ doubao_itn: v })} /><span className="text-sm">{t('enable_inverse_text_normalization')}</span></label>
          <label className="flex items-center gap-2 cursor-pointer"><Switch checked={f.doubao_ddc} onCheckedChange={v => upd({ doubao_ddc: v })} /><span className="text-sm">{t('enable_digit_detection')}</span></label>
        </div>
      </>}
      {p==='aliyun_qwen3' && <>
        <F label="API Key"><Input type="password" value={f.qwen3_api_key} onChange={e => upd({ qwen3_api_key: e.target.value })} placeholder={t('optional_dashscope_key')} /></F>
        <F label="WS URL"><Input value={f.qwen3_ws_url} onChange={e => upd({ qwen3_ws_url: e.target.value })} /></F>
        <div className="grid grid-cols-2 gap-3">
          <F label={t('model')}><Input value={f.qwen3_model} onChange={e => upd({ qwen3_model: e.target.value })} placeholder="qwen3-asr-flash-realtime" /></F>
          <F label={t('language')}><Input value={f.qwen3_language} onChange={e => upd({ qwen3_language: e.target.value })} placeholder="zh" /></F>
        </div>
        <div className="grid grid-cols-2 gap-3">
          <F label={t('sample_rate')}>
            <Select value={String(f.qwen3_sample_rate)} onValueChange={v => upd({ qwen3_sample_rate: Number(v) })}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent><SelectItem value="8000">8000</SelectItem><SelectItem value="16000">16000</SelectItem></SelectContent>
            </Select>
          </F>
          <F label={t('timeout_seconds')}><N v={f.qwen3_timeout} min={1} onChange={v => upd({ qwen3_timeout: v })} /></F>
        </div>
        <label className="flex items-center gap-2 cursor-pointer"><Switch checked={f.qwen3_auto_end} onCheckedChange={v => upd({ qwen3_auto_end: v })} /><span className="text-sm">{t('auto_end')}</span></label>
        {f.qwen3_auto_end && <div className="grid grid-cols-2 gap-3">
          <F label={t('vad_threshold')}><N v={f.qwen3_vad_threshold} min={0} max={1} step={0.1} onChange={v => upd({ qwen3_vad_threshold: v })} /></F>
          <F label={t('vad_silence_duration')}><N v={f.qwen3_vad_silence_ms} min={0} onChange={v => upd({ qwen3_vad_silence_ms: v })} /></F>
        </div>}
      </>}
      {p==='xunfei' && <>
        <F label={t('app_id')}><Input value={f.xunfei_appid} onChange={e => upd({ xunfei_appid: e.target.value })} placeholder={t('enter_xunfei_app_id')} /></F>
        <F label="API Key"><Input type="password" value={f.xunfei_api_key} onChange={e => upd({ xunfei_api_key: e.target.value })} placeholder={t('enter_xunfei_api_key')} /></F>
        <F label="API Secret"><Input type="password" value={f.xunfei_api_secret} onChange={e => upd({ xunfei_api_secret: e.target.value })} /></F>
        <div className="grid grid-cols-2 gap-3">
          <F label="Host"><Input value={f.xunfei_host} onChange={e => upd({ xunfei_host: e.target.value })} placeholder="iat-api.xfyun.cn" /></F>
          <F label="Path"><Input value={f.xunfei_path} onChange={e => upd({ xunfei_path: e.target.value })} placeholder="/v2/iat" /></F>
        </div>
        <div className="grid grid-cols-2 gap-3">
          <F label={t('business_domain')}><Input value={f.xunfei_domain} onChange={e => upd({ xunfei_domain: e.target.value })} placeholder="iat" /></F>
          <F label={t('language')}><Input value={f.xunfei_language} onChange={e => upd({ xunfei_language: e.target.value })} placeholder="zh_cn" /></F>
        </div>
        <div className="grid grid-cols-2 gap-3">
          <F label={t('dialect')}><Input value={f.xunfei_accent} onChange={e => upd({ xunfei_accent: e.target.value })} placeholder="mandarin" /></F>
          <F label={t('timeout_seconds')}><N v={f.xunfei_timeout} min={1} onChange={v => upd({ xunfei_timeout: v })} /></F>
        </div>
      </>}
      <div className="flex items-center gap-6 pt-1">
        <label className="flex items-center gap-2 cursor-pointer"><Switch checked={f.enabled} onCheckedChange={v => upd({ enabled: v })} /><span className="text-sm">{t('enabled_status')}</span></label>
        <label className="flex items-center gap-2 cursor-pointer"><Switch checked={f.is_default} onCheckedChange={v => upd({ is_default: v })} /><span className="text-sm">{t('default_config')}</span></label>
      </div>
    </div>
  )
}

// manager/frontend/src/views/admin/forms/ASRConfigForm.vue
<template>
  <el-form ref="formRef" :model="model" :rules="rules" label-width="140px">
    <el-form-item :label="t('provider')" prop="provider">
      <el-select v-model="model.provider" :placeholder="t('select_provider')" style="width: 100%" @change="onProviderChange">
        <el-option label="FunASR" value="funasr" />
        <el-option label="Aliyun FunASR" value="aliyun_funasr" />
        <el-option :label="t('doubao')" value="doubao" />
        <el-option label="Aliyun Qwen3" value="aliyun_qwen3" />
        <el-option :label="t('xunfei')" value="xunfei" />
      </el-select>
    </el-form-item>
    <el-form-item :label="t('config_name')" prop="name">
      <el-input v-model="model.name" :placeholder="t('enter_config_name')" />
    </el-form-item>
    <el-form-item :label="t('config_id')" prop="config_id">
      <el-input v-model="model.config_id" :placeholder="t('enter_unique_config_id')" />
    </el-form-item>
    <div v-if="model.provider === 'funasr'">
      <el-form-item :label="t('host_address')" prop="funasr.host">
        <el-input v-model="model.funasr.host" :placeholder="t('enter_host_address')" />
      </el-form-item>
      <el-form-item :label="t('port')" prop="funasr.port">
        <el-input-number v-model="model.funasr.port" :min="1" :max="65535" style="width: 100%" />
      </el-form-item>
      <el-form-item :label="t('mode')" prop="funasr.mode">
        <el-select v-model="model.funasr.mode" :placeholder="t('select_mode')" style="width: 100%">
          <el-option label="2pass" value="2pass" />
          <el-option label="offline" value="offline" />
          <el-option label="online" value="online" />
        </el-select>
      </el-form-item>
      <el-form-item :label="t('sample_rate')" prop="funasr.sample_rate">
        <el-select v-model="model.funasr.sample_rate" :placeholder="t('select_sample_rate')" style="width: 100%">
          <el-option label="8000" :value="8000" />
          <el-option label="16000" :value="16000" />
          <el-option label="44100" :value="44100" />
          <el-option label="48000" :value="48000" />
        </el-select>
      </el-form-item>
      <el-form-item :label="t('chunk_size')" prop="funasr.chunk_size">
        <div style="display: flex; gap: 8px; width: 100%">
          <el-input-number v-model="model.funasr.chunk_size[0]" :min="1" :placeholder="t('forward')" style="flex: 1" />
          <el-input-number v-model="model.funasr.chunk_size[1]" :min="1" :placeholder="t('middle')" style="flex: 1" />
          <el-input-number v-model="model.funasr.chunk_size[2]" :min="1" :placeholder="t('backward')" style="flex: 1" />
        </div>
        <div class="form-tip">
          <el-icon><InfoFilled /></el-icon>
          {{ t('frame_size_format_hint') }}</div>
      </el-form-item>
      <el-form-item :label="t('chunk_interval')" prop="funasr.chunk_interval">
        <el-input-number v-model="model.funasr.chunk_interval" :min="1" style="width: 100%" />
      </el-form-item>
      <el-form-item :label="t('max_connections')" prop="funasr.max_connections">
        <el-input-number v-model="model.funasr.max_connections" :min="1" style="width: 100%" />
      </el-form-item>
      <el-form-item :label="t('timeout_seconds')" prop="funasr.timeout">
        <el-input-number v-model="model.funasr.timeout" :min="1" style="width: 100%" />
      </el-form-item>
      <el-form-item :label="t('auto_end')" prop="funasr.auto_end">
        <el-switch v-model="model.funasr.auto_end" />
        <div class="form-tip">
          <el-icon><InfoFilled /></el-icon>
          {{ t('funasr_config_hint') }}</div>
      </el-form-item>
    </div>
    <div v-if="model.provider === 'aliyun_funasr'">
      <el-form-item label="API Key" prop="aliyun_funasr.api_key">
        <el-input v-model="model.aliyun_funasr.api_key" type="password" show-password :placeholder="t('optional_dashscope_key')" />
        <div class="form-tip">
          <el-icon><InfoFilled /></el-icon>
          {{ t('optional_dashscope_fallback') }}</div>
      </el-form-item>
      <el-form-item label="WS URL" prop="aliyun_funasr.ws_url">
        <el-input v-model="model.aliyun_funasr.ws_url" placeholder="wss://dashscope.aliyuncs.com/api-ws/v1/inference/" />
      </el-form-item>
      <el-form-item :label="t('model')" prop="aliyun_funasr.model">
        <el-input v-model="model.aliyun_funasr.model" placeholder="fun-asr-realtime" />
      </el-form-item>
      <el-form-item :label="t('audio_format')" prop="aliyun_funasr.format">
        <el-select v-model="model.aliyun_funasr.format" :placeholder="t('select_format')" style="width: 100%">
          <el-option label="pcm" value="pcm" />
        </el-select>
      </el-form-item>
      <el-form-item :label="t('sample_rate')" prop="aliyun_funasr.sample_rate">
        <el-select v-model="model.aliyun_funasr.sample_rate" :placeholder="t('select_sample_rate')" style="width: 100%">
          <el-option label="16000" :value="16000" />
        </el-select>
      </el-form-item>
      <el-form-item :label="t('language_hint')" prop="aliyun_funasr.language_hints">
        <el-select
          v-model="model.aliyun_funasr.language_hints"
          multiple
          filterable
          allow-create
          default-first-option
          placeholder="zh"
          style="width: 100%"
        >
          <el-option :label="t('chinese_zh')" value="zh" />
          <el-option :label="t('lang_en')" value="en" />
          <el-option :label="t('japanese_ja')" value="ja" />
          <el-option :label="t('lang_ko')" value="ko" />
        </el-select>
      </el-form-item>
      <el-form-item :label="t('vocab_id')" prop="aliyun_funasr.vocabulary_id">
        <el-input v-model="model.aliyun_funasr.vocabulary_id" :placeholder="t('optional_empty')" />
      </el-form-item>
      <el-form-item :label="t('remove_filler_words')" prop="aliyun_funasr.disfluency_removal_enabled">
        <el-switch v-model="model.aliyun_funasr.disfluency_removal_enabled" />
      </el-form-item>
      <el-form-item :label="t('timeout_seconds')" prop="aliyun_funasr.timeout">
        <el-input-number v-model="model.aliyun_funasr.timeout" :min="1" style="width: 100%" />
      </el-form-item>
    </div>
    <div v-if="model.provider === 'doubao'">
      <el-form-item :label="t('app_id')" prop="doubao.appid">
        <el-input v-model="model.doubao.appid" :placeholder="t('enter_app_id')" />
      </el-form-item>
      <el-form-item :label="t('access_token')" prop="doubao.access_token">
        <el-input v-model="model.doubao.access_token" type="password" :placeholder="t('enter_access_token')" show-password />
      </el-form-item>
      <el-form-item label="WebSocket URL" prop="doubao.ws_url">
        <el-input v-model="model.doubao.ws_url" :placeholder="t('enter_websocket_url')" />
      </el-form-item>
      <el-form-item :label="t('resource_spec')" prop="doubao.resource_id">
        <el-select v-model="model.doubao.resource_id" :placeholder="t('select_resource_spec')" style="width: 100%">
          <el-option :label="t('doubao_stream_asr_v1_hourly')" value="volc.bigasr.sauc.duration" />
          <el-option :label="t('doubao_stream_asr_v1_concurrent')" value="volc.bigasr.sauc.concurrent" />
          <el-option :label="t('doubao_stream_asr_v2_hourly')" value="volc.seedasr.sauc.duration" />
          <el-option :label="t('doubao_stream_asr_v2_concurrent')" value="volc.seedasr.sauc.concurrent" />
        </el-select>
      </el-form-item>
      <el-form-item :label="t('end_window_size')" prop="doubao.end_window_size">
        <el-input-number v-model="model.doubao.end_window_size" :min="1" style="width: 100%" />
      </el-form-item>
      <el-form-item :label="t('enable_punctuation')" prop="doubao.enable_punc">
        <el-switch v-model="model.doubao.enable_punc" />
      </el-form-item>
      <el-form-item :label="t('enable_inverse_text_normalization')" prop="doubao.enable_itn">
        <el-switch v-model="model.doubao.enable_itn" />
      </el-form-item>
      <el-form-item :label="t('enable_digit_detection')" prop="doubao.enable_ddc">
        <el-switch v-model="model.doubao.enable_ddc" />
      </el-form-item>
      <el-form-item :label="t('chunk_duration_ms')" prop="doubao.chunk_duration">
        <el-input-number v-model="model.doubao.chunk_duration" :min="1" style="width: 100%" />
      </el-form-item>
      <el-form-item :label="t('timeout_seconds')" prop="doubao.timeout">
        <el-input-number v-model="model.doubao.timeout" :min="1" style="width: 100%" />
      </el-form-item>
    </div>
    <div v-if="model.provider === 'xunfei'">
      <el-form-item :label="t('app_id')" prop="xunfei.appid">
        <el-input v-model="model.xunfei.appid" :placeholder="t('enter_xunfei_app_id')" />
      </el-form-item>
      <el-form-item label="API Key" prop="xunfei.api_key">
        <el-input v-model="model.xunfei.api_key" type="password" show-password :placeholder="t('enter_xunfei_api_key')" />
      </el-form-item>
      <el-form-item label="API Secret" prop="xunfei.api_secret">
        <el-input v-model="model.xunfei.api_secret" type="password" show-password :placeholder="t('enter_xunfei_api_secret')" />
      </el-form-item>
      <el-form-item label="Host" prop="xunfei.host">
        <el-input v-model="model.xunfei.host" placeholder="iat-api.xfyun.cn" />
      </el-form-item>
      <el-form-item label="Path" prop="xunfei.path">
        <el-input v-model="model.xunfei.path" placeholder="/v2/iat" />
      </el-form-item>
      <el-form-item :label="t('business_domain')" prop="xunfei.domain">
        <el-input v-model="model.xunfei.domain" placeholder="iat" />
      </el-form-item>
      <el-form-item :label="t('language')" prop="xunfei.language">
        <el-input v-model="model.xunfei.language" placeholder="zh_cn" />
      </el-form-item>
      <el-form-item :label="t('dialect')" prop="xunfei.accent">
        <el-input v-model="model.xunfei.accent" placeholder="mandarin" />
      </el-form-item>
      <el-form-item :label="t('sample_rate')" prop="xunfei.sample_rate">
        <el-select v-model="model.xunfei.sample_rate" :placeholder="t('select_sample_rate')" style="width: 100%">
          <el-option label="16000" :value="16000" />
        </el-select>
      </el-form-item>
      <el-form-item :label="t('timeout_seconds')" prop="xunfei.timeout">
        <el-input-number v-model="model.xunfei.timeout" :min="1" style="width: 100%" />
      </el-form-item>
    </div>
    <div v-if="model.provider === 'aliyun_qwen3'">
      <el-form-item label="API Key" prop="aliyun_qwen3.api_key">
        <el-input v-model="model.aliyun_qwen3.api_key" type="password" show-password :placeholder="t('optional_dashscope_key')" />
        <div class="form-tip">
          <el-icon><InfoFilled /></el-icon>
          {{ t('optional_dashscope_fallback') }}</div>
      </el-form-item>
      <el-form-item label="WS URL" prop="aliyun_qwen3.ws_url">
        <el-input v-model="model.aliyun_qwen3.ws_url" placeholder="wss://dashscope.aliyuncs.com/api-ws/v1/realtime" />
      </el-form-item>
      <el-form-item :label="t('model')" prop="aliyun_qwen3.model">
        <el-input v-model="model.aliyun_qwen3.model" placeholder="qwen3-asr-flash-realtime" />
      </el-form-item>
      <el-form-item :label="t('audio_format')" prop="aliyun_qwen3.format">
        <el-select v-model="model.aliyun_qwen3.format" :placeholder="t('select_format')" style="width: 100%">
          <el-option label="pcm" value="pcm" />
          <el-option label="opus" value="opus" />
        </el-select>
      </el-form-item>
      <el-form-item :label="t('sample_rate')" prop="aliyun_qwen3.sample_rate">
        <el-select v-model="model.aliyun_qwen3.sample_rate" :placeholder="t('select_sample_rate')" style="width: 100%">
          <el-option label="8000" :value="8000" />
          <el-option label="16000" :value="16000" />
        </el-select>
        <div class="form-tip">
          <el-icon><InfoFilled /></el-icon>
          {{ t('sample_rate_16000_hint') }}</div>
      </el-form-item>
      <el-form-item :label="t('language')" prop="aliyun_qwen3.language">
        <el-input v-model="model.aliyun_qwen3.language" placeholder="zh" />
      </el-form-item>
      <el-form-item :label="t('auto_end')" prop="aliyun_qwen3.auto_end">
        <el-switch v-model="model.aliyun_qwen3.auto_end" />
        <div class="form-tip">
          <el-icon><InfoFilled /></el-icon>
          {{ t('server_vad_hint') }}</div>
      </el-form-item>
      <el-form-item :label="t('vad_threshold')" prop="aliyun_qwen3.vad_threshold" v-if="model.aliyun_qwen3?.auto_end">
        <el-input-number v-model="model.aliyun_qwen3.vad_threshold" :min="0" :max="1" :step="0.1" :precision="2" style="width: 100%" />
      </el-form-item>
      <el-form-item :label="t('vad_silence_duration')" prop="aliyun_qwen3.vad_silence_ms" v-if="model.aliyun_qwen3?.auto_end">
        <el-input-number v-model="model.aliyun_qwen3.vad_silence_ms" :min="0" style="width: 100%" />
      </el-form-item>
      <el-form-item :label="t('timeout_seconds')" prop="aliyun_qwen3.timeout">
        <el-input-number v-model="model.aliyun_qwen3.timeout" :min="1" style="width: 100%" />
      </el-form-item>
    </div>
  </el-form>
</template>

<script setup>
import { ref, watch } from 'vue'
import { InfoFilled } from '@element-plus/icons-vue'
import { useLocale } from '../../../composables/useLocale'
const { t } = useLocale()

const props = defineProps({
  model: { type: Object, required: true },
  rules: { type: Object, default: () => ({}) }
})

const formRef = ref()

const ASR_PROVIDER_DEFAULTS = {
  funasr: {
    name: 'FunASR ASR',
    config_id: 'funasr_default',
    data: {
      host: '127.0.0.1',
      port: 10095,
      mode: 'offline',
      sample_rate: 16000,
      chunk_size: [5, 10, 5],
      chunk_interval: 10,
      max_connections: 100,
      timeout: 30,
      auto_end: false
    }
  },
  aliyun_funasr: {
    name: t('aliyun_funasr_asr'),
    config_id: 'aliyun_funasr_default',
    data: {
      api_key: '',
      ws_url: 'wss://dashscope.aliyuncs.com/api-ws/v1/inference/',
      model: 'fun-asr-realtime',
      format: 'pcm',
      sample_rate: 16000,
      language_hints: ['zh'],
      vocabulary_id: '',
      disfluency_removal_enabled: false,
      timeout: 30
    }
  },
  doubao: {
    name: t('doubao_asr'),
    config_id: 'doubao_default',
    data: {
      appid: '',
      access_token: '',
      ws_url: 'wss://openspeech.bytedance.com/api/v3/sauc/bigmodel_async',
      resource_id: 'volc.bigasr.sauc.duration',
      model_name: 'bigmodel',
      end_window_size: 800,
      enable_punc: true,
      enable_itn: true,
      enable_ddc: false,
      chunk_duration: 200,
      timeout: 30
    }
  },
  aliyun_qwen3: {
    name: t('aliyun_qwen3_asr'),
    config_id: 'aliyun_qwen3_default',
    data: {
      api_key: '',
      ws_url: 'wss://dashscope.aliyuncs.com/api-ws/v1/realtime',
      model: 'qwen3-asr-flash-realtime',
      format: 'pcm',
      sample_rate: 16000,
      language: 'zh',
      auto_end: false,
      vad_threshold: 0.0,
      vad_silence_ms: 400,
      timeout: 30
    }
  },
  xunfei: {
    name: t('xunfei_asr'),
    config_id: 'xunfei_default',
    data: {
      appid: '',
      api_key: '',
      api_secret: '',
      host: 'iat-api.xfyun.cn',
      path: '/v2/iat',
      domain: 'iat',
      language: 'zh_cn',
      accent: 'mandarin',
      sample_rate: 16000,
      timeout: 30
    }
  }
}

const defaultNames = new Set(['默认ASR', ...Object.values(ASR_PROVIDER_DEFAULTS).map(item => item.name)])
const defaultConfigIds = new Set(Object.values(ASR_PROVIDER_DEFAULTS).flatMap(item => [item.config_id, item.config_id.replace(/_default$/, '')]))

function cloneDefaultData(provider) {
  const data = ASR_PROVIDER_DEFAULTS[provider]?.data || {}
  return JSON.parse(JSON.stringify(data))
}

function normalizeLanguageHints(value) {
  if (Array.isArray(value)) {
    return value.map(item => String(item).trim()).filter(Boolean)
  }
  if (typeof value === 'string') {
    return value.split(/[，,;；]/).map(item => item.trim()).filter(Boolean)
  }
  return []
}

function ensureProviderData(provider) {
  if (!provider || !props.model || !ASR_PROVIDER_DEFAULTS[provider]) return
  const current = props.model[provider]
  props.model[provider] = { ...cloneDefaultData(provider), ...(current || {}) }
  if (provider === 'funasr' && !props.model.funasr.mode) {
    props.model.funasr.mode = 'offline'
  }
  if (provider === 'aliyun_funasr') {
    const hasLanguageHints = current && Object.prototype.hasOwnProperty.call(current, 'language_hints')
    const source = hasLanguageHints
      ? props.model.aliyun_funasr.language_hints
      : (props.model.aliyun_funasr.language || props.model.aliyun_funasr.language_hints)
    props.model.aliyun_funasr.language_hints = normalizeLanguageHints(source)
  }
}

function isDefaultish(value, knownValues) {
  const normalized = String(value || '').trim()
  return !normalized || knownValues.has(normalized)
}

function applyProviderIdentity(provider) {
  if (!provider || !props.model || !ASR_PROVIDER_DEFAULTS[provider]) return
  const defaults = ASR_PROVIDER_DEFAULTS[provider]
  if (isDefaultish(props.model.name, defaultNames)) {
    props.model.name = defaults.name
  }
  if (isDefaultish(props.model.config_id, defaultConfigIds)) {
    props.model.config_id = defaults.config_id
  }
}

function onProviderChange(provider) {
  ensureProviderData(provider)
  applyProviderIdentity(provider)
}

watch(() => props.model?.provider, (provider) => {
  ensureProviderData(provider)
}, { immediate: true })

function getJsonData() {
  const m = props.model
  if (m.provider === 'funasr') return JSON.stringify(m.funasr || {})
  if (m.provider === 'aliyun_funasr') return JSON.stringify(m.aliyun_funasr || {})
  if (m.provider === 'doubao') return JSON.stringify(m.doubao || {})
  if (m.provider === 'aliyun_qwen3') return JSON.stringify(m.aliyun_qwen3 || {})
  if (m.provider === 'xunfei') return JSON.stringify(m.xunfei || {})
  return '{}'
}

function validate(callback) {
  return formRef.value?.validate(callback)
}

function resetFields() {
  formRef.value?.resetFields()
}

defineExpose({ validate, getJsonData, resetFields })
</script>

<style scoped>
.form-tip {
  margin-top: 8px;
  font-size: 12px;
  color: var(--apple-text-secondary);
  display: flex;
  align-items: center;
  gap: 4px;
}
.form-tip .el-icon {
  font-size: 14px;
  color: var(--apple-primary);
}
</style>
