// manager/frontend/src/components/admin/llm-config-form.tsx
import { useEffect, useState } from 'react'
import { useLocale } from '@/hooks/use-locale'
import { Input } from '@/components/ui/input'
import { Switch } from '@/components/ui/switch'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { ComboInput } from '@/components/ui/combo-input'
import type { ConfigRow } from './config-list-page'
import type { ConfigForm } from './config-list-page'
import {
  resolveLLMProvider, getProviderFixedType, isProviderBaseURLEditable, getProviderQuickUrl,
  getProviderModelOptions, getProviderModelHint, getProviderModelFieldLabel,
  getProviderModelPlaceholder, getProviderRequestConfig, getProviderThinkingConfig, LLM_PROVIDERS,
} from './llm-catalog'

interface LlmFields {
  provider: string; name: string; config_id: string; enabled: boolean; is_default: boolean
  model_name: string; api_key: string; base_url: string
  max_tokens: number; temperature: number; top_p: number
  thinking_mode: string; thinking_budget: number | null; thinking_effort: string; thinking_clear: string
  bot_id: string; user_prefix: string; connector_id: string
}

const defaults: LlmFields = {
  provider: 'openai', name: '', config_id: '', enabled: true, is_default: false,
  model_name: '', api_key: '', base_url: '',
  max_tokens: 4000, temperature: 0.7, top_p: 0.9,
  thinking_mode: 'default', thinking_budget: null, thinking_effort: 'medium', thinking_clear: 'default',
  bot_id: '', user_prefix: '', connector_id: '1024',
}

function serialize(f: LlmFields): string {
  const type = getProviderFixedType(f.provider)
  const thinking = f.thinking_mode !== 'default' || f.thinking_budget != null
    ? { mode: f.thinking_mode, ...(f.thinking_budget != null ? { budget_tokens: f.thinking_budget } : {}), effort: f.thinking_effort, clear_thinking: f.thinking_clear }
    : undefined
  const data: Record<string, unknown> = { type, model_name: f.model_name, api_key: f.api_key, base_url: f.base_url }
  if (type === 'openai' || type === 'ollama') { data.max_tokens = f.max_tokens; data.temperature = f.temperature; data.top_p = f.top_p }
  if (thinking) data.thinking = thinking
  if (type === 'coze') { data.bot_id = f.bot_id; data.user_prefix = f.user_prefix; data.connector_id = f.connector_id }
  if (type === 'dify') data.user_prefix = f.user_prefix
  return JSON.stringify(data)
}

function parse(row: ConfigRow | null): LlmFields {
  if (!row) return { ...defaults }
  try {
    const d = JSON.parse(row.json_data || '{}')
    const provider = resolveLLMProvider(row.provider || '', d.type)
    return {
      ...defaults, provider, name: row.name, config_id: row.config_id,
      enabled: row.enabled !== false, is_default: !!row.is_default,
      model_name: d.model_name || '', api_key: d.api_key || '', base_url: d.base_url || '',
      max_tokens: d.max_tokens || 4000, temperature: d.temperature ?? 0.7, top_p: d.top_p ?? 0.9,
      thinking_mode: d.thinking?.mode || 'default', thinking_budget: d.thinking?.budget_tokens ?? null,
      thinking_effort: d.thinking?.effort || 'medium', thinking_clear: String(d.thinking?.clear_thinking ?? 'default'),
      bot_id: d.bot_id || '', user_prefix: d.user_prefix || '', connector_id: d.connector_id || '1024',
    }
  } catch { return { ...defaults } }
}

const F = ({ label, children }: { label: string; children: React.ReactNode }) => (
  <div className="grid gap-1.5"><label className="text-sm font-medium text-[var(--color-text)]">{label}</label>{children}</div>
)

export function LlmConfigForm({ form, setForm, editing }: { form: ConfigForm; setForm: (p: Partial<ConfigForm>) => void; editing: ConfigRow | null }) {
  const { t } = useLocale()
  const [f, setF] = useState<LlmFields>(() => parse(editing))

  useEffect(() => { const parsed = parse(editing); setF(parsed) }, [editing])

  const upd = (patch: Partial<LlmFields>) => {
    const next = { ...f, ...patch }
    setF(next)
    setForm({ name: next.name, config_id: next.config_id, provider: next.provider, enabled: next.enabled, is_default: next.is_default, json_data: serialize(next) })
  }

  const onProviderChange = (p: string) => {
    const url = isProviderBaseURLEditable(p) ? getProviderQuickUrl(p) : ''
    upd({ provider: p, base_url: url, model_name: '' })
  }

  const type = getProviderFixedType(f.provider)
  const isOpenAIType = type === 'openai' || type === 'ollama'
  const isDify = type === 'dify'
  const isCoze = type === 'coze'
  const showBaseURL = isProviderBaseURLEditable(f.provider)
  const modelOptions = getProviderModelOptions(f.provider)
  const modelHint = getProviderModelHint(f.provider, f.model_name, t)
  const requestCfg = getProviderRequestConfig(f.provider, f.model_name)
  const thinkingCfg = getProviderThinkingConfig(f.provider, f.model_name, t)
  const showBudget = thinkingCfg.visible && thinkingCfg.showBudgetFor.includes(f.thinking_mode)
  const showEffort = thinkingCfg.visible && thinkingCfg.showEffortFor.includes(f.thinking_mode)
  const showClear = thinkingCfg.visible && thinkingCfg.showClearThinkingFor.includes(f.thinking_mode)

  return (
    <div className="grid gap-3">
      <F label={t('provider')}>
        <Select value={f.provider} onValueChange={onProviderChange}>
          <SelectTrigger><SelectValue /></SelectTrigger>
          <SelectContent>{LLM_PROVIDERS.map(p => <SelectItem key={p.value} value={p.value}>{p.labelKey ? t(p.label) : p.label}</SelectItem>)}</SelectContent>
        </Select>
      </F>
      <div className="grid grid-cols-2 gap-3">
        <F label={t('config_name')}><Input value={f.name} onChange={e => upd({ name: e.target.value })} placeholder={t('enter_config_name')} /></F>
        <F label={t('config_id')}><Input value={f.config_id} onChange={e => upd({ config_id: e.target.value })} placeholder={t('enter_unique_config_id')} /></F>
      </div>
      {isOpenAIType && (
        <F label={getProviderModelFieldLabel(f.provider, t)}>
          <ComboInput value={f.model_name} onChange={v => upd({ model_name: v })} options={modelOptions} placeholder={getProviderModelPlaceholder(f.provider, t)} />
          {modelHint && <p className="text-xs text-[var(--color-text-secondary)]">{modelHint}</p>}
        </F>
      )}
      {type !== 'ollama' && (
        <F label="API Key"><Input type="password" value={f.api_key} onChange={e => upd({ api_key: e.target.value })} placeholder={t('enter_api_password')} /></F>
      )}
      {showBaseURL && (
        <F label={t('base_url')}><Input value={f.base_url} onChange={e => upd({ base_url: e.target.value })} placeholder={t('enter_base_url')} /></F>
      )}
      {isCoze && <>
        <F label="Bot ID"><Input value={f.bot_id} onChange={e => upd({ bot_id: e.target.value })} placeholder={t('enter_coze_bot_id_v2')} /></F>
        <F label="Connector ID"><Input value={f.connector_id} onChange={e => upd({ connector_id: e.target.value })} placeholder="1024" /></F>
      </>}
      {(isDify || isCoze) && <F label={t('user_prefix')}><Input value={f.user_prefix} onChange={e => upd({ user_prefix: e.target.value })} placeholder="xiaozhi" /></F>}
      {isOpenAIType && requestCfg.allowMaxTokens && (
        <div className="grid grid-cols-3 gap-3">
          <F label="max_tokens"><Input type="number" value={f.max_tokens} min={1} max={100000} onChange={e => upd({ max_tokens: Number(e.target.value) })} /></F>
          {requestCfg.allowTemperature && <F label={t('temperature')}><Input type="number" value={f.temperature} min={0} max={requestCfg.temperatureMax} step={0.1} onChange={e => upd({ temperature: Number(e.target.value) })} /></F>}
          {requestCfg.allowTopP && <F label="Top P"><Input type="number" value={f.top_p} min={0} max={1} step={0.1} onChange={e => upd({ top_p: Number(e.target.value) })} /></F>}
        </div>
      )}
      {thinkingCfg.visible && (
        <F label={thinkingCfg.label}>
          <Select value={f.thinking_mode} onValueChange={v => upd({ thinking_mode: v })}>
            <SelectTrigger><SelectValue /></SelectTrigger>
            <SelectContent>{thinkingCfg.options.map(o => <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent>
          </Select>
        </F>
      )}
      {showBudget && <F label={t('thinking_budget')}><Input type="number" value={f.thinking_budget ?? ''} min={thinkingCfg.budgetMin} max={thinkingCfg.budgetMax} step={thinkingCfg.budgetStep} onChange={e => upd({ thinking_budget: e.target.value ? Number(e.target.value) : null })} /></F>}
      {showEffort && (
        <F label={t('thinking_level')}>
          <Select value={f.thinking_effort} onValueChange={v => upd({ thinking_effort: v })}>
            <SelectTrigger><SelectValue /></SelectTrigger>
            <SelectContent>{thinkingCfg.effortOptions.map(o => <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent>
          </Select>
        </F>
      )}
      {showClear && (
        <F label={t('history_thinking_chain')}>
          <Select value={String(f.thinking_clear)} onValueChange={v => upd({ thinking_clear: v })}>
            <SelectTrigger><SelectValue /></SelectTrigger>
            <SelectContent>{thinkingCfg.clearThinkingOptions.map(o => <SelectItem key={String(o.value)} value={String(o.value)}>{o.label}</SelectItem>)}</SelectContent>
          </Select>
        </F>
      )}
      {thinkingCfg.visible && thinkingCfg.hint && (
        <p className="text-xs text-amber-600 bg-amber-50 rounded-md px-3 py-2">{thinkingCfg.hint}</p>
      )}
      <div className="flex items-center gap-6 pt-1">
        <label className="flex items-center gap-2 cursor-pointer">
          <Switch checked={f.enabled} onCheckedChange={v => upd({ enabled: v })} /><span className="text-sm">{t('enabled_status')}</span>
        </label>
        <label className="flex items-center gap-2 cursor-pointer">
          <Switch checked={f.is_default} onCheckedChange={v => upd({ is_default: v })} /><span className="text-sm">{t('default_config')}</span>
        </label>
      </div>
    </div>
  )
}

// manager/frontend/src/views/admin/forms/LLMConfigForm.vue
<template>
  <el-form ref="formRef" :model="model" :rules="rules" label-width="120px">
    <el-form-item :label="t('provider')" prop="provider" required>
      <el-select v-model="model.provider" :placeholder="t('select_provider')" style="width: 100%" @change="onProviderChange">
        <el-option label="OpenAI" value="openai" />
        <el-option label="Ollama" value="ollama" />
        <el-option label="Azure OpenAI" value="azure" />
        <el-option label="Anthropic" value="anthropic" />
        <el-option :label="t('zhipu_ai')" value="zhipu" />
        <el-option :label="t('aliyun')" value="aliyun" />
        <el-option :label="t('doubao')" value="doubao" />
        <el-option :label="t('silicon_flow')" value="siliconflow" />
        <el-option :label="t('deepseek_label')" value="deepseek" />
        <el-option label="Dify" value="dify" />
        <el-option label="Coze" value="coze" />
      </el-select>
    </el-form-item>
    <el-form-item :label="t('config_name')" prop="name">
      <el-input v-model="model.name" :placeholder="t('enter_config_name')" />
    </el-form-item>
    <el-form-item :label="t('config_id')" prop="config_id">
      <el-input v-model="model.config_id" :placeholder="t('enter_unique_config_id')" />
    </el-form-item>

    <el-form-item v-if="isOpenAIOrOllama" :label="modelFieldLabel" prop="model_name" required>
      <el-select
        v-model="model.model_name"
        filterable
        allow-create
        default-first-option
        clearable
        :placeholder="modelPlaceholder"
        style="width: 100%"
      >
        <el-option
          v-for="option in modelOptions"
          :key="option.value"
          :label="option.label"
          :value="option.value"
        />
      </el-select>
    </el-form-item>

    <el-form-item v-if="isOpenAIOrOllama && modelHint">
      <el-alert
        :title="modelHint"
        type="info"
        :closable="false"
        show-icon
      />
    </el-form-item>

    <el-form-item :label="t('api_key')" prop="api_key" :required="apiKeyRequired">
      <el-input v-model="model.api_key" type="password" :placeholder="t('enter_api_password')" show-password />
    </el-form-item>

    <el-form-item v-if="showBaseURL" :label="t('base_url')" prop="base_url" required>
      <el-input v-model="model.base_url" :placeholder="t('enter_base_url')" style="width: 100%" />
    </el-form-item>

    <el-form-item v-if="isCoze" label="Bot ID" prop="bot_id" required>
      <el-input v-model="model.bot_id" :placeholder="t('enter_coze_bot_id')" />
    </el-form-item>

    <el-form-item v-if="isDify || isCoze" :label="t('user_prefix')" prop="user_prefix">
      <el-input v-model="model.user_prefix" :placeholder="t('optional_default_xiaozhi')" />
    </el-form-item>

    <el-form-item v-if="isCoze" label="Connector ID" prop="connector_id">
      <el-input v-model="model.connector_id" :placeholder="t('optional_default_1024')" />
    </el-form-item>

    <el-form-item v-if="isOpenAIOrOllama && requestConfig.allowMaxTokens" label="max_tokens" prop="max_tokens" required>
      <el-input-number v-model="model.max_tokens" :min="1" :max="100000" placeholder="max_tokens" style="width: 100%" />
    </el-form-item>

    <el-form-item v-if="isOpenAIOrOllama && requestConfig.allowTemperature" :label="t('temperature')" prop="temperature">
      <el-input-number v-model="model.temperature" :min="0" :max="requestConfig.temperatureMax" :step="0.1" :placeholder="t('temperature')" style="width: 100%" />
    </el-form-item>

    <el-form-item v-if="isOpenAIOrOllama && requestConfig.allowTopP" label="Top P" prop="top_p">
      <el-input-number v-model="model.top_p" :min="0" :max="1" :step="0.1" placeholder="Top P" style="width: 100%" />
    </el-form-item>

    <el-form-item v-if="isOpenAIOrOllama && requestCapabilityHint" :label="t('params_hint')">
      <el-alert
        :title="requestCapabilityHint"
        type="info"
        :closable="false"
        show-icon
      />
    </el-form-item>

    <template v-if="thinkingConfig.visible">
      <el-form-item :label="thinkingConfig.label" prop="thinking_mode">
        <el-select v-model="model.thinking_mode" :placeholder="t('select_deep_thinking_mode')" style="width: 100%">
          <el-option
            v-for="option in thinkingConfig.options"
            :key="option.value"
            :label="option.label"
            :value="option.value"
          />
        </el-select>
      </el-form-item>

      <el-form-item v-if="thinkingConfig.showEffort" :label="t('thinking_level')" prop="thinking_effort">
        <el-select v-model="model.thinking_effort" :placeholder="t('select_thinking_depth')" style="width: 100%">
          <el-option
            v-for="option in thinkingConfig.effortOptions"
            :key="option.value"
            :label="option.label"
            :value="option.value"
          />
        </el-select>
      </el-form-item>

      <el-form-item v-if="thinkingConfig.showBudget" :label="t('thinking_budget')" prop="thinking_budget_tokens">
        <el-input-number
          v-model="model.thinking_budget_tokens"
          :min="thinkingConfig.budgetMin"
          :max="thinkingConfig.budgetMax"
          :step="thinkingConfig.budgetStep"
          :placeholder="t('budget_token')"
          style="width: 100%"
        />
      </el-form-item>

      <el-form-item v-if="thinkingConfig.showClearThinking" :label="t('history_thinking_chain')">
        <el-select v-model="model.thinking_clear_thinking" :placeholder="t('select_thinking_chain_mode')" style="width: 100%">
          <el-option
            v-for="option in thinkingConfig.clearThinkingOptions"
            :key="String(option.value)"
            :label="option.label"
            :value="option.value"
          />
        </el-select>
      </el-form-item>

      <el-form-item>
        <el-alert
          :title="thinkingConfig.hint"
          type="warning"
          :closable="false"
          show-icon
        />
      </el-form-item>
    </template>
  </el-form>
</template>

<script setup>
import { computed, ref, watch } from 'vue'
import { useLocale } from '../../../composables/useLocale'
import {
  getProviderFixedType,
  getProviderModelFieldLabel,
  getProviderModelHint,
  getProviderModelOptions,
  getProviderModelPlaceholder,
  getProviderQuickUrl,
  getProviderRequestConfig,
  getProviderThinkingConfig,
  isProviderBaseURLEditable,
  resolveLLMProvider
} from './llmCatalog'

const { t } = useLocale()

const props = defineProps({
  model: { type: Object, required: true },
  rules: { type: Object, default: () => ({}) }
})

const formRef = ref()

const resolvedProvider = computed(() => resolveLLMProvider(props.model?.provider, props.model?.type))
const effectiveType = computed(() => getProviderFixedType(resolvedProvider.value))
const isOpenAIOrOllama = computed(() => effectiveType.value === 'openai' || effectiveType.value === 'ollama')
const isOllama = computed(() => effectiveType.value === 'ollama')
const isDify = computed(() => effectiveType.value === 'dify')
const isCoze = computed(() => effectiveType.value === 'coze')
const showBaseURL = computed(() => isProviderBaseURLEditable(resolvedProvider.value))
const apiKeyRequired = computed(() => !isOllama.value)

const defaultThinkingMode = 'default'

const provider = computed(() => resolvedProvider.value || '')
const modelFieldLabel = computed(() => getProviderModelFieldLabel(provider.value))
const modelPlaceholder = computed(() => getProviderModelPlaceholder(provider.value))
const modelOptions = computed(() => getProviderModelOptions(provider.value))
const thinkingDefinition = computed(() => getProviderThinkingConfig(provider.value, props.model?.model_name))
const modelHint = computed(() => {
  if (!thinkingDefinition.value?.visible && thinkingDefinition.value?.hint) {
    return thinkingDefinition.value.hint
  }
  return getProviderModelHint(provider.value)
})
const requestConfig = computed(() => getProviderRequestConfig(provider.value, props.model?.model_name))

const requestCapabilityHint = computed(() => {
  const blockedFields = []
  if (!requestConfig.value.allowMaxTokens) {
    blockedFields.push('max_tokens')
  }
  if (!requestConfig.value.allowTemperature) {
    blockedFields.push('temperature')
  }
  if (!requestConfig.value.allowTopP) {
    blockedFields.push('top_p')
  }
  if (!blockedFields.length) {
    return ''
  }
  return `当前模型按文档不建议单独设置 ${blockedFields.join('、')}，保存时不会透传这些字段。`
})

const thinkingConfig = computed(() => {
  const config = thinkingDefinition.value
  if (!config?.visible) {
    return {
      visible: false,
      label: t('deep_thinking'),
      options: [],
      showBudget: false,
      budgetMin: 1,
      budgetMax: 100000,
      budgetStep: 1,
      budgetRequired: false,
      showEffort: false,
      effortOptions: [],
      showClearThinking: false,
      clearThinkingOptions: [],
      hint: config?.hint || ''
    }
  }

  const showBudget = config.showBudgetFor.includes(props.model?.thinking_mode)
  const showEffort = config.showEffortFor.includes(props.model?.thinking_mode)
  const showClearThinking = config.showClearThinkingFor.includes(props.model?.thinking_mode)
  const budgetRequired = config.budgetRequiredFor.includes(props.model?.thinking_mode)

  return {
    visible: true,
    label: config.label,
    options: config.options,
    showBudget,
    budgetMin: config.budgetMin,
    budgetMax: config.budgetMax,
    budgetStep: config.budgetStep,
    budgetRequired,
    showEffort,
    effortOptions: config.effortOptions,
    showClearThinking,
    clearThinkingOptions: config.clearThinkingOptions,
    hint: config.hint || t('deep_thinking_warning')
  }
})

function normalizeThinkingState(provider) {
  if (!props.model) {
    return
  }

  const config = getProviderThinkingConfig(provider, props.model?.model_name)
  if (!config?.visible) {
    props.model.thinking_mode = defaultThinkingMode
    props.model.thinking_budget_tokens = null
    props.model.thinking_clear_thinking = 'default'
    return
  }

  const options = config.options.map(option => option.value)
  if (!options.includes(props.model.thinking_mode)) {
    props.model.thinking_mode = defaultThinkingMode
  }

  if (props.model.thinking_budget_tokens !== null && props.model.thinking_budget_tokens !== undefined && props.model.thinking_budget_tokens !== '') {
    const budgetValue = Number(props.model.thinking_budget_tokens)
    if (Number.isNaN(budgetValue) || budgetValue < (config.budgetMin || 1)) {
      props.model.thinking_budget_tokens = null
    }
  }

  if (!props.model.thinking_effort) {
    props.model.thinking_effort = 'medium'
  }

  if (props.model.thinking_clear_thinking === undefined || props.model.thinking_clear_thinking === null || props.model.thinking_clear_thinking === '') {
    props.model.thinking_clear_thinking = 'default'
  }
}

function applyProviderDefaults(value, forceEditableURL = false, resetModel = false) {
  if (!value || !props.model) {
    return
  }

  props.model.type = getProviderFixedType(value)
  if (isProviderBaseURLEditable(value)) {
    const quickUrl = getProviderQuickUrl(value)
    if (forceEditableURL || !props.model.base_url) {
      props.model.base_url = quickUrl
    }
  } else {
    props.model.base_url = ''
  }

  if (resetModel) {
    props.model.model_name = ''
  }
  if (value === 'dify' && (!props.model.model_name || resetModel)) {
    props.model.model_name = 'dify'
  }
  if (value === 'coze') {
    if (!props.model.model_name || resetModel) {
      props.model.model_name = 'coze'
    }
    if (!props.model.connector_id) {
      props.model.connector_id = '1024'
    }
  }
}

watch(() => props.model?.provider, (value) => {
  if (!value || !props.model) {
    return
  }
  applyProviderDefaults(value, false)
  normalizeThinkingState(value)
}, { immediate: true })

watch(() => props.model?.model_name, () => {
  if (!provider.value) {
    return
  }
  normalizeThinkingState(provider.value)
}, { immediate: true })

function onProviderChange(value) {
  if (!value || !props.model) {
    return
  }
  applyProviderDefaults(value, true, true)
}

function getJsonData() {
  const m = props.model
  const providerName = resolveLLMProvider(m?.provider, m?.type)
  const providerType = getProviderFixedType(providerName)
  const thinking = buildThinkingPayload(m)
  if (providerType === 'dify') {
    const config = {
      api_key: m.api_key,
      user_prefix: m.user_prefix
    }
    if (m.base_url) config.base_url = m.base_url
    return JSON.stringify(config, null, 2)
  }
  if (providerType === 'coze') {
    const config = {
      api_key: m.api_key,
      bot_id: m.bot_id,
      user_prefix: m.user_prefix,
      connector_id: m.connector_id
    }
    if (m.base_url) config.base_url = m.base_url
    return JSON.stringify(config, null, 2)
  }

  const config = {
    model_name: m.model_name,
    api_key: m.api_key
  }
  if (isProviderBaseURLEditable(providerName) && m.base_url) config.base_url = m.base_url
  if (requestConfig.value.allowMaxTokens && m.max_tokens !== undefined && m.max_tokens !== null && m.max_tokens !== '') {
    config.max_tokens = m.max_tokens
  }
  if (requestConfig.value.allowTemperature && m.temperature !== undefined && m.temperature !== null) config.temperature = m.temperature
  if (requestConfig.value.allowTopP && m.top_p !== undefined && m.top_p !== null) config.top_p = m.top_p
  if (thinking) config.thinking = thinking
  return JSON.stringify(config, null, 2)
}

function buildThinkingPayload(model) {
  const providerName = resolveLLMProvider(model?.provider, model?.type)
  const config = getProviderThinkingConfig(providerName, model?.model_name)
  if (!config?.visible) {
    return undefined
  }

  const mode = model?.thinking_mode || defaultThinkingMode
  if (mode === defaultThinkingMode) {
    return undefined
  }

  const payload = { mode }
  if ((config.showBudgetFor || []).includes(mode) && model?.thinking_budget_tokens !== null && model?.thinking_budget_tokens !== undefined && model?.thinking_budget_tokens !== '') {
    payload.budget_tokens = Number(model.thinking_budget_tokens)
  }
  if ((config.showEffortFor || []).includes(mode) && model?.thinking_effort) {
    payload.effort = model.thinking_effort
  }
  if ((config.showClearThinkingFor || []).includes(mode) && typeof model?.thinking_clear_thinking === 'boolean') {
    payload.clear_thinking = model.thinking_clear_thinking
  }
  return payload
}

function validate(callback) {
  if (callback) {
    return formRef.value?.validate((valid) => {
      let finalValid = valid
      if (finalValid && isCoze.value && !props.model?.bot_id) {
        finalValid = false
      }
      if (finalValid && thinkingConfig.value.showBudget && thinkingConfig.value.budgetRequired && (props.model?.thinking_budget_tokens === null || props.model?.thinking_budget_tokens === undefined || props.model?.thinking_budget_tokens === '')) {
        finalValid = false
      }
      if (finalValid && thinkingConfig.value.showBudget && props.model?.thinking_budget_tokens !== null && props.model?.thinking_budget_tokens !== undefined && props.model?.thinking_budget_tokens !== '' && Number(props.model?.thinking_budget_tokens) < thinkingConfig.value.budgetMin) {
        finalValid = false
      }
      callback(finalValid)
      return finalValid
    })
  }

  return formRef.value?.validate().then(() => {
    if (isCoze.value && !props.model?.bot_id) {
      return Promise.reject(new Error(t('enter_coze_bot_id_v2')))
    }
    if (thinkingConfig.value.showBudget && thinkingConfig.value.budgetRequired && (props.model?.thinking_budget_tokens === null || props.model?.thinking_budget_tokens === undefined || props.model?.thinking_budget_tokens === '')) {
      return Promise.reject(new Error(t('thinking_budget_required')))
    }
    if (thinkingConfig.value.showBudget && props.model?.thinking_budget_tokens !== null && props.model?.thinking_budget_tokens !== undefined && props.model?.thinking_budget_tokens !== '' && Number(props.model?.thinking_budget_tokens) < thinkingConfig.value.budgetMin) {
      return Promise.reject(new Error(`思考预算不能小于 ${thinkingConfig.value.budgetMin}`))
    }
    return true
  })
}

function resetFields() {
  formRef.value?.resetFields()
}

defineExpose({ validate, getJsonData, resetFields })
</script>
