// manager/frontend/src/routes/_auth/_layout/admin/speaker-config.tsx
import { useEffect, useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { toast } from 'sonner'
import api from '@/utils/api'
import { useLocale } from '@/hooks/use-locale'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Switch } from '@/components/ui/switch'
import { PageHeader } from '@/components/ui/page-header'

interface SpeakerForm { base_url: string; threshold: number; enabled: boolean }

const defaults: SpeakerForm = { base_url: 'http://192.168.208.214:8080', threshold: 0.4, enabled: true }

function SpeakerConfigPage() {
  const { t } = useLocale()
  const [loading, setLoading] = useState(false)
  const [saving, setSaving] = useState(false)
  const [currentId, setCurrentId] = useState<number | null>(null)
  const [form, setForm] = useState<SpeakerForm>(defaults)

  const setF = (patch: Partial<SpeakerForm>) => setForm((f) => ({ ...f, ...patch }))

  const load = async () => {
    setLoading(true)
    try {
      const res = await api.get('/admin/speaker-configs')
      const configs = res.data?.data || []
      if (configs.length > 0) {
        const c = configs[0]; setCurrentId(c.id)
        const d = JSON.parse(c.json_data || '{}')
        setForm({
          base_url: d.service?.base_url || d.base_url || 'http://192.168.208.214:8080',
          threshold: d.service?.threshold !== undefined ? d.service.threshold : (d.threshold ?? 0.4),
          enabled: d.enable !== false
        })
      } else { setCurrentId(null); setForm(defaults) }
    } catch { toast.error(t('load_config_failed')) }
    finally { setLoading(false) }
  }

  useEffect(() => { load() }, []) // eslint-disable-line react-hooks/exhaustive-deps

  const handleSave = async () => {
    if (!form.base_url.trim()) { toast.error(t('enter_service_address')); return }
    if (form.threshold < 0 || form.threshold > 1) { toast.error(t('threshold_0_to_1_decimal')); return }
    setSaving(true)
    try {
      const payload = {
        name: t('voiceprint_recognition_config'), config_id: 'asr_server', provider: 'asr_server', is_default: true, enabled: form.enabled,
        json_data: JSON.stringify({ service: { base_url: form.base_url.trim(), threshold: form.threshold }, enable: form.enabled })
      }
      if (currentId) { await api.put(`/admin/speaker-configs/${currentId}`, payload); toast.success(t('config_update_success')) }
      else { const r = await api.post('/admin/speaker-configs', payload); setCurrentId(r.data?.data?.id || null); toast.success(t('config_create_success')) }
      await load()
    } catch (e) { toast.error((e as Error).message || t('save_failed')) }
    finally { setSaving(false) }
  }

  if (loading) return <div className="p-6 text-center text-sm text-[var(--color-text-secondary)]">{t('loading')}</div>

  return (
    <div className="grid gap-6 px-6 pb-8">
      <PageHeader title={t('voiceprint_recognition_config')} />
      <div className="max-w-[640px] rounded-xl border border-[var(--color-line)] bg-[var(--color-surface-1)]">
        <div className="p-6 grid gap-5">
          <div className="flex items-center justify-between gap-4">
            <div>
              <p className="text-sm font-semibold text-[var(--color-text)]">{t('enabled_status')}</p>
              <p className="text-xs text-[var(--color-text-secondary)] mt-0.5">{t('enable_voiceprint_service')}</p>
            </div>
            <Switch checked={form.enabled} onCheckedChange={(v) => setF({ enabled: v })} />
          </div>
          <div className="grid gap-1.5">
            <label className="text-sm font-semibold text-[var(--color-text)]">{t('service_address')}</label>
            <Input value={form.base_url} onChange={(e) => setF({ base_url: e.target.value })} placeholder="http://192.168.0.1:8080" />
            <p className="text-xs text-[var(--color-text-secondary)]">{t('speaker_service_url_hint')}</p>
          </div>
          <div className="grid gap-1.5">
            <label className="text-sm font-semibold text-[var(--color-text)]">{t('recognition_threshold')}</label>
            <Input type="number" value={form.threshold} onChange={(e) => setF({ threshold: Number(e.target.value) })} min={0} max={1} step={0.01} />
            <p className="text-xs text-[var(--color-text-secondary)]">{t('threshold_0_to_1_hint')}</p>
          </div>
        </div>
      </div>

      <div className="flex items-center justify-end gap-3">
        <Button variant="outline" disabled={loading} onClick={load}>{t('reset_to_current')}</Button>
        <Button disabled={saving} onClick={handleSave}>{t('save_config')}</Button>
      </div>
    </div>
  )
}

export const Route = createFileRoute('/_auth/_layout/admin/speaker-config')({
  component: SpeakerConfigPage,
})

// manager/frontend/src/views/admin/SpeakerConfig.vue
<template>
  <div class="config-page">
    <el-card v-loading="loading" class="config-card">
      <el-alert
        :title="t('hint')"
        type="info"
        :closable="false"
        show-icon
        style="margin-bottom: 20px;"
      >
        <template #default>
          {{ t('docker_env_hint') }}
        </template>
      </el-alert>
      
      <el-form
        ref="formRef"
        :model="form"
        :rules="rules"
        label-width="120px"
      >
        <el-form-item :label="t('service_address')" prop="base_url">
          <el-input 
            v-model="form.base_url" 
            :placeholder="t('http_service_address_ph')"
            style="width: 100%"
          />
          <div class="form-tip">
            <el-icon><InfoFilled /></el-icon>
            {{ t('http_to_ws_hint') }}
          </div>
        </el-form-item>
        
        <el-form-item :label="t('recognition_threshold')" prop="threshold">
          <el-input-number 
            v-model="form.threshold" 
            :min="0" 
            :max="1" 
            :step="0.1" 
            :precision="2"
            placeholder="0.4"
            style="width: 100%"
          />
          <div class="form-tip">
            <el-icon><InfoFilled /></el-icon>
            {{ t('recognition_threshold_hint') }}
          </div>
        </el-form-item>
        
        <el-form-item :label="t('enabled_status')">
          <el-switch v-model="form.enabled" />
        </el-form-item>
      </el-form>
      
      <div class="form-actions">
        <el-button type="primary" @click="handleSave" :loading="saving">
          {{ t('save_config') }}
        </el-button>
      </div>
    </el-card>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import { InfoFilled } from '@element-plus/icons-vue'
import api from '../../utils/api'
import { useLocale } from '../../composables/useLocale'
const { t } = useLocale()

const loading = ref(false)
const saving = ref(false)
const formRef = ref()
const currentConfig = ref(null)

const form = reactive({
  base_url: 'http://192.168.208.214:8080',
  threshold: 0.4,
  enabled: true
})

const rules = {
  base_url: [
    { required: true, message: t('enter_service_address'), trigger: 'blur' },
    { 
      pattern: /^https?:\/\/.+/, 
      message: t('enter_valid_http_address'), 
      trigger: 'blur' 
    }
  ],
  threshold: [
    { required: true, message: t('enter_recognition_threshold'), trigger: 'blur' },
    { 
      type: 'number', 
      min: 0, 
      max: 1, 
      message: t('threshold_0_to_1_decimal'), 
      trigger: 'blur' 
    }
  ]
}

const loadConfig = async () => {
  loading.value = true
  try {
    const response = await api.get('/admin/speaker-configs')
    const configs = response.data.data || []
    
    if (configs.length > 0) {
      // 如果有配置，使用第一个（应该只有一个）
      currentConfig.value = configs[0]
      const configObj = JSON.parse(configs[0].json_data || '{}')
      
      // 解析配置
      if (configObj.service && configObj.service.base_url) {
        form.base_url = configObj.service.base_url
      } else if (configObj.base_url) {
        // 兼容旧格式
        form.base_url = configObj.base_url
      }
      // 读取阈值配置
      if (configObj.service && configObj.service.threshold !== undefined) {
        form.threshold = configObj.service.threshold
      } else if (configObj.threshold !== undefined) {
        // 兼容旧格式
        form.threshold = configObj.threshold
      } else {
        // 默认值
        form.threshold = 0.4
      }
      // 开关对应 json_data.enable（业务启用），不使用接口返回的 enabled 列
      form.enabled = configObj.enable !== undefined ? configObj.enable : true
    }
  } catch (error) {
    ElMessage.error(t('load_config_failed'))
  } finally {
    loading.value = false
  }
}

const handleSave = async () => {
  if (!formRef.value) return
  
  await formRef.value.validate(async (valid) => {
    if (valid) {
      saving.value = true
      try {
        // 构建配置数据：开关写入 json_data.enable，对外输出以该字段为准
        const configData = {
          service: {
            base_url: form.base_url,
            threshold: form.threshold
          },
          enable: form.enabled
        }
        
        const saveData = {
          name: t('voiceprint_recognition_config'),
          config_id: 'asr_server',
          provider: 'asr_server',
          is_default: true,
          enabled: form.enabled,
          json_data: JSON.stringify(configData)
        }
        
        if (currentConfig.value) {
          // 更新现有配置
          await api.put(`/admin/speaker-configs/${currentConfig.value.id}`, saveData)
          ElMessage.success(t('config_update_success'))
        } else {
          // 创建新配置
          await api.post('/admin/speaker-configs', saveData)
          ElMessage.success(t('config_create_success'))
        }
        
        // 重新加载配置
        await loadConfig()
      } catch (error) {
        ElMessage.error(t('save_failed_colon') + (error.response?.data?.message || error.message))
      } finally {
        saving.value = false
      }
    }
  })
}

onMounted(() => {
  loadConfig()
})
</script>

<style scoped>
.config-page {
  padding: 20px;
  background: rgba(255, 255, 255, 0.88);
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.config-card {
  max-width: 800px;
}

.form-tip {
  margin-top: 8px;
  font-size: 12px;
  color: var(--apple-text-secondary);
  display: flex;
  align-items: center;
  gap: 4px;
}

.form-tip .el-icon {
  font-size: 14px;
  color: var(--apple-primary);
}

.form-actions {
  margin-top: 20px;
  padding-top: 20px;
  border-top: 1px solid #ebeef5;
}
</style>
