// manager/frontend/src/routes/_auth/_layout/admin/users.tsx
import { useEffect, useState } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import { MoreHorizontal, Plus } from 'lucide-react'
import { toast } from 'sonner'
import api from '@/utils/api'
import { useLocale } from '@/hooks/use-locale'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { ConfirmDialog } from '@/components/ui/confirm-dialog'
import { PageHeader } from '@/components/ui/page-header'
import { UserQuotaDialog } from '@/components/admin/user-quota-dialog'

interface User { id: number; username: string; email: string; role: string; created_at: string }

const defaultForm = () => ({ username: '', email: '', password: '', role: '' })
const defaultPwdForm = () => ({ newPassword: '', confirmPassword: '' })

function UsersPage() {
  const { t } = useLocale()
  const [users, setUsers] = useState<User[]>([])
  const [loading, setLoading] = useState(false)
  const [page, setPage] = useState(1)
  const [total, setTotal] = useState(0)
  const [search, setSearch] = useState('')
  const pageSize = 20

  const [showUser, setShowUser] = useState(false)
  const [editingUser, setEditingUser] = useState<User | null>(null)
  const [userForm, setUserForm] = useState(defaultForm())
  const [showPwd, setShowPwd] = useState(false)
  const [userSaving, setUserSaving] = useState(false)

  const [showReset, setShowReset] = useState(false)
  const [resetTarget, setResetTarget] = useState<User | null>(null)
  const [pwdForm, setPwdForm] = useState(defaultPwdForm())
  const [resetSaving, setResetSaving] = useState(false)

  const [deleteTarget, setDeleteTarget] = useState<User | null>(null)
  const [deleting, setDeleting] = useState(false)
  const [quotaUser, setQuotaUser] = useState<User | null>(null)

  const setF = (p: Partial<typeof userForm>) => setUserForm(f => ({ ...f, ...p }))
  const setP = (p: Partial<typeof pwdForm>) => setPwdForm(f => ({ ...f, ...p }))

  const load = async (p = page) => {
    setLoading(true)
    try {
      const res = await api.get('/admin/users', { params: { page: p, page_size: pageSize } })
      setUsers(res.data.data || [])
      setTotal(res.data.total || 0)
    } catch { toast.error(t('load_user_list_failed')) }
    finally { setLoading(false) }
  }

  useEffect(() => { load(1) }, []) // eslint-disable-line react-hooks/exhaustive-deps

  const filtered = search ? users.filter(u => u.username.toLowerCase().includes(search.toLowerCase()) || (u.email || '').toLowerCase().includes(search.toLowerCase())) : users
  const totalPages = Math.ceil(total / pageSize) || 1

  const openAdd = () => { setEditingUser(null); setUserForm(defaultForm()); setShowPwd(false); setShowUser(true) }
  const openEdit = (u: User) => { setEditingUser(u); setUserForm({ username: u.username, email: u.email, password: '', role: u.role }); setShowUser(true) }

  const handleUserSave = async () => {
    if (!editingUser && !userForm.username.trim()) { toast.error(t('enter_username')); return }
    if (!userForm.email.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(userForm.email)) { toast.error(t('enter_valid_email')); return }
    if (!editingUser && userForm.password.length < 6) { toast.error(t('password_min_length')); return }
    if (!userForm.role) { toast.error(t('select_role')); return }
    setUserSaving(true)
    try {
      if (editingUser) { await api.put(`/admin/users/${editingUser.id}`, { email: userForm.email, role: userForm.role }); toast.success(t('user_update_success')) }
      else { await api.post('/admin/users', { username: userForm.username, email: userForm.email, password: userForm.password, role: userForm.role }); toast.success(t('user_add_success')) }
      setShowUser(false); await load(page)
    } catch { toast.error(editingUser ? t('update_user_failed') : t('add_user_failed')) }
    finally { setUserSaving(false) }
  }

  const handleReset = async () => {
    if (pwdForm.newPassword.length < 6) { toast.error(t('password_min_length')); return }
    if (pwdForm.newPassword !== pwdForm.confirmPassword) { toast.error(t('password_mismatch')); return }
    if (!resetTarget) return
    setResetSaving(true)
    try { await api.post(`/admin/users/${resetTarget.id}/reset-password`, { new_password: pwdForm.newPassword }); toast.success(t('password_reset_success')); setShowReset(false) }
    catch { toast.error(t('reset_password_failed')) }
    finally { setResetSaving(false) }
  }

  const handleDelete = async () => {
    if (!deleteTarget) return
    setDeleting(true)
    try { await api.delete(`/admin/users/${deleteTarget.id}`); toast.success(t('user_delete_success')); setDeleteTarget(null); await load(page) }
    catch { toast.error(t('delete_user_failed')) }
    finally { setDeleting(false) }
  }

  const roleBadge = (role: string) => role === 'admin'
    ? 'inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium status-danger'
    : 'inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium status-primary'

  return (
    <div className="grid gap-4 px-6 pb-8">
      <PageHeader title={t('user_management')} />
      <div className="flex items-center justify-between gap-4">
        <Input value={search} onChange={e => setSearch(e.target.value)} placeholder={t('search_user')} className="max-w-xs" />
        <Button onClick={openAdd}><Plus className="w-4 h-4 mr-1.5" />{t('add_user')}</Button>
      </div>
      <div className="rounded-xl border border-[var(--color-line)] overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-16">ID</TableHead>
              <TableHead>{t('username')}</TableHead>
              <TableHead>{t('email')}</TableHead>
              <TableHead className="w-28">{t('role')}</TableHead>
              <TableHead className="w-44">{t('created_at')}</TableHead>
              <TableHead className="w-16 text-center">{t('actions')}</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {loading ? <TableRow><TableCell colSpan={6} className="py-10 text-center text-sm text-[var(--color-text-secondary)]">{t('loading')}</TableCell></TableRow>
              : filtered.length === 0 ? <TableRow><TableCell colSpan={6} className="py-10 text-center text-sm text-[var(--color-text-secondary)]">{t('no_data')}</TableCell></TableRow>
              : filtered.map(u => (
                <TableRow key={u.id}>
                  <TableCell className="text-[var(--color-text-secondary)] text-xs font-mono">{u.id}</TableCell>
                  <TableCell className="font-semibold">{u.username}</TableCell>
                  <TableCell className="text-[var(--color-text-secondary)]">{u.email}</TableCell>
                  <TableCell><span className={roleBadge(u.role)}>{u.role === 'admin' ? t('admin') : t('normal_user')}</span></TableCell>
                  <TableCell className="text-[var(--color-text-secondary)] text-sm">{new Date(u.created_at).toLocaleString()}</TableCell>
                  <TableCell className="text-center">
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="h-8 w-8"><MoreHorizontal className="h-4 w-4" /></Button></DropdownMenuTrigger>
                      <DropdownMenuContent align="end">
                        <DropdownMenuItem onClick={() => openEdit(u)}>{t('edit')}</DropdownMenuItem>
                        <DropdownMenuItem disabled={u.role === 'admin'} onClick={() => u.role !== 'admin' && setQuotaUser(u)}>{t('voice_clone_quota')}</DropdownMenuItem>
                        <DropdownMenuItem onClick={() => { setResetTarget(u); setPwdForm(defaultPwdForm()); setShowReset(true) }}>{t('reset_password_title')}</DropdownMenuItem>
                        <DropdownMenuSeparator />
                        <DropdownMenuItem disabled={u.role === 'admin'} className="text-destructive" onClick={() => u.role !== 'admin' && setDeleteTarget(u)}>{t('delete')}</DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </TableCell>
                </TableRow>
              ))}
          </TableBody>
        </Table>
      </div>
      {total > pageSize && (
        <div className="flex items-center justify-between text-sm text-[var(--color-text-secondary)]">
          <span>{total} {t('total_items')}</span>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" disabled={page <= 1} onClick={() => { setPage(p => p - 1); load(page - 1) }}>{t('prev')}</Button>
            <span>{page} / {totalPages}</span>
            <Button variant="outline" size="sm" disabled={page >= totalPages} onClick={() => { setPage(p => p + 1); load(page + 1) }}>{t('next')}</Button>
          </div>
        </div>
      )}

      {/* Add/Edit user dialog */}
      <Dialog open={showUser} onOpenChange={v => { if (!v) setShowUser(false) }}>
        <DialogContent className="max-w-lg">
          <DialogHeader><DialogTitle>{editingUser ? t('edit_user') : t('add_user')}</DialogTitle></DialogHeader>
          <div className="grid gap-4 py-2">
            <div className="grid gap-1.5">
              <label className="text-sm font-semibold">{t('username')}</label>
              <Input value={userForm.username} disabled={!!editingUser} onChange={e => setF({ username: e.target.value })} placeholder={t('enter_username')} />
            </div>
            <div className="grid gap-1.5">
              <label className="text-sm font-semibold">{t('email')}</label>
              <Input type="email" value={userForm.email} onChange={e => setF({ email: e.target.value })} placeholder={t('enter_email')} />
            </div>
            {!editingUser && (
              <div className="grid gap-1.5">
                <label className="text-sm font-semibold">{t('password')}</label>
                <div className="relative">
                  <Input type={showPwd ? 'text' : 'password'} value={userForm.password} onChange={e => setF({ password: e.target.value })} placeholder={t('enter_password_min6')} className="pr-16" />
                  <button type="button" className="absolute right-2.5 top-1/2 -translate-y-1/2 text-xs text-[var(--color-text-secondary)] hover:text-[var(--color-text)]" onClick={() => setShowPwd(v => !v)}>
                    {showPwd ? t('hide') : t('show')}
                  </button>
                </div>
              </div>
            )}
            <div className="grid gap-1.5">
              <label className="text-sm font-semibold">{t('role')}</label>
              <Select value={userForm.role} onValueChange={v => setF({ role: v })}>
                <SelectTrigger><SelectValue placeholder={t('select_role')} /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="user">{t('normal_user')}</SelectItem>
                  <SelectItem value="admin">{t('admin')}</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowUser(false)}>{t('cancel')}</Button>
            <Button disabled={userSaving} onClick={handleUserSave}>{editingUser ? t('save') : t('add')}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Reset password dialog */}
      <Dialog open={showReset} onOpenChange={v => { if (!v) setShowReset(false) }}>
        <DialogContent className="max-w-md">
          <DialogHeader><DialogTitle>{t('reset_password_title')}</DialogTitle></DialogHeader>
          <div className="grid gap-4 py-2">
            <div className="grid gap-1.5"><label className="text-sm font-semibold">{t('user')}</label><Input value={resetTarget?.username || ''} disabled /></div>
            <div className="grid gap-1.5"><label className="text-sm font-semibold">{t('new_password')}</label><Input type="password" value={pwdForm.newPassword} onChange={e => setP({ newPassword: e.target.value })} placeholder={t('new_password_ph')} /></div>
            <div className="grid gap-1.5"><label className="text-sm font-semibold">{t('confirm_password')}</label><Input type="password" value={pwdForm.confirmPassword} onChange={e => setP({ confirmPassword: e.target.value })} placeholder={t('confirm_password_ph')} /></div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowReset(false)}>{t('cancel')}</Button>
            <Button disabled={resetSaving} onClick={handleReset}>{t('confirm_reset')}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <ConfirmDialog open={!!deleteTarget} onClose={() => setDeleteTarget(null)} onConfirm={handleDelete} isLoading={deleting} title={t('confirm_delete')} description={t('confirm_delete_user', { name: deleteTarget?.username || '' })} />
      <UserQuotaDialog open={!!quotaUser} user={quotaUser} onClose={() => setQuotaUser(null)} />
    </div>
  )
}

export const Route = createFileRoute('/_auth/_layout/admin/users')({
  component: UsersPage,
})

// manager/frontend/src/views/admin/Users.vue
<template>
  <div class="config-page">
    <div class="page-actions">
      <el-input
        v-model="searchKeyword"
        :placeholder="t('search_user')"
        style="width: 200px"
        prefix-icon="Search"
        clearable
      />
      <el-button type="primary" @click="openAddDialog">
        <el-icon><Plus /></el-icon>
        {{ t('add_user') }}</el-button>
    </div>

    <!-- User list table -->
    <el-table :data="filteredUserList" v-loading="tableLoading" style="width: 100%">
      <el-table-column prop="id" label="ID" width="80" />
      <el-table-column prop="username" :label="t('username')" width="150" />
      <el-table-column prop="email" :label="t('email')" width="200" />
      <el-table-column prop="role" :label="t('role')" width="120">
        <template #default="{ row }">
          <el-tag :type="row.role === 'admin' ? 'danger' : 'primary'">
            {{ row.role === 'admin' ? t('admin') : t('normal_user') }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column prop="created_at" :label="t('created_at')" width="180">
        <template #default="{ row }">
          {{ formatDateTime(row.created_at) }}
        </template>
      </el-table-column>
      <el-table-column :label="t('actions')" width="360">
        <template #default="{ row }">
          <el-button size="small" @click="openEditDialog(row)">{{ t('edit') }}</el-button>
          <el-button size="small" type="success" @click="openQuotaDialog(row)" :disabled="row.role === 'admin'">{{ t('voice_clone_quota') }}</el-button>
          <el-button size="small" type="warning" @click="openResetPasswordDialog(row)">
            {{ t('reset_password_title') }}
          </el-button>
          <el-button 
            size="small" 
            type="danger" 
            @click="handleDeleteUser(row)"
            :disabled="row.role === 'admin'"
          >
            {{ t('delete') }}
          </el-button>
        </template>
      </el-table-column>
    </el-table>

    <!-- Add/Edit user dialog -->
    <el-dialog 
      v-model="userDialogVisible" 
      :title="isEditMode ? t('edit_user') : t('add_user')"
      width="500px"
      @close="resetUserForm"
    >
      <el-form 
        ref="userFormRef" 
        :model="userForm" 
        :rules="userFormRules" 
        label-width="80px"
      >
        <el-form-item :label="t('username')" prop="username">
          <el-input 
            v-model="userForm.username" 
            :disabled="isEditMode"
            :placeholder="t('enter_username')"
          />
        </el-form-item>
        
        <el-form-item :label="t('email')" prop="email">
          <el-input v-model="userForm.email" :placeholder="t('enter_email')" />
        </el-form-item>
        
        <el-form-item v-if="!isEditMode" :label="t('password')" prop="password">
          <el-input 
            v-model="userForm.password" 
            type="password" 
            :placeholder="t('enter_password_min6')"
            show-password
          />
        </el-form-item>
        
        <el-form-item :label="t('role')" prop="role">
          <el-select v-model="userForm.role" :placeholder="t('select_role')" style="width: 100%">
            <el-option :label="t('normal_user')" value="user" />
            <el-option :label="t('admin')" value="admin" />
          </el-select>
        </el-form-item>
      </el-form>
      
      <template #footer>
        <el-button @click="userDialogVisible = false">{{ t('cancel') }}</el-button>
        <el-button type="primary" @click="handleUserSubmit" :loading="userSubmitLoading">
          {{ isEditMode ? t('save') : t('add') }}
        </el-button>
      </template>
    </el-dialog>

    <!-- Reset password dialog -->
    <el-dialog 
      v-model="resetPasswordDialogVisible" 
      :title="t('reset_password_title')"
      width="400px"
      @close="resetPasswordForm"
    >
      <el-form 
        ref="passwordFormRef" 
        :model="passwordForm" 
        :rules="passwordFormRules" 
        label-width="80px"
      >
        <el-form-item :label="t('user')">
          <el-input v-model="currentUser.username" disabled />
        </el-form-item>
        
        <el-form-item :label="t('new_password')" prop="newPassword">
          <el-input 
            v-model="passwordForm.newPassword" 
            type="password" 
            :placeholder="t('new_password_ph')"
            show-password
          />
        </el-form-item>
        
        <el-form-item :label="t('confirm_password')" prop="confirmPassword">
          <el-input 
            v-model="passwordForm.confirmPassword" 
            type="password" 
            :placeholder="t('confirm_password_ph')"
            show-password
          />
        </el-form-item>
      </el-form>
      
      <template #footer>
        <el-button @click="resetPasswordDialogVisible = false">{{ t('cancel') }}</el-button>
        <el-button type="primary" @click="handleResetPassword" :loading="resetPasswordLoading">{{ t('confirm_reset') }}</el-button>
      </template>
    </el-dialog>

    <!-- Voice clone quota dialog -->
    <el-dialog
      v-model="quotaDialogVisible"
      :title="t('voice_clone_quota_title', { name: quotaUser.username || '' })"
      width="900px"
      @close="resetQuotaDialog"
    >
      <div class="quota-hint">{{ t('quota_hint') }}</div>
      <el-table :data="quotaRows" v-loading="quotaLoading" style="margin-top: 12px">
        <el-table-column prop="tts_config_name" :label="t('tts_config_name_col')" min-width="180" />
        <el-table-column prop="tts_config_id" label="TTS Config ID" min-width="180" />
        <el-table-column prop="provider" label="Provider" width="120" />
        <el-table-column :label="t('used_count_col')" width="100">
          <template #default="{ row }">{{ row.used_count }}</template>
        </el-table-column>
        <el-table-column :label="t('remaining_count_col')" width="100">
          <template #default="{ row }">{{ row.remaining_count < 0 ? t('unlimited') : row.remaining_count }}</template>
        </el-table-column>
        <el-table-column :label="t('max_count_col')" width="180">
          <template #default="{ row }">
            <el-input-number v-model="row.max_count" :min="-1" :step="1" :precision="0" controls-position="right" style="width: 140px" />
          </template>
        </el-table-column>
      </el-table>
      <template #footer>
        <el-button @click="quotaDialogVisible = false">{{ t('cancel') }}</el-button>
        <el-button type="primary" :loading="quotaSaving" @click="saveQuotaSettings">{{ t('save_quota') }}</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive, computed, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
import api from '../../utils/api'
import { useLocale } from '../../composables/useLocale'
const { t } = useLocale()

// Data state
const userList = ref([])
const tableLoading = ref(false)
const userDialogVisible = ref(false)
const resetPasswordDialogVisible = ref(false)
const userSubmitLoading = ref(false)
const resetPasswordLoading = ref(false)
const quotaDialogVisible = ref(false)
const quotaLoading = ref(false)
const quotaSaving = ref(false)
const quotaRows = ref([])
const quotaUser = ref({})
const quotaOriginalMaxMap = ref({})
const isEditMode = ref(false)
const currentUser = ref({})
const searchKeyword = ref('')

// Computed properties
const filteredUserList = computed(() => {
  if (!searchKeyword.value) {
    return userList.value
  }
  return userList.value.filter(user => 
    user.username.toLowerCase().includes(searchKeyword.value.toLowerCase()) ||
    user.email.toLowerCase().includes(searchKeyword.value.toLowerCase())
  )
})

// Form refs
const userFormRef = ref()
const passwordFormRef = ref()

// User form data
const userForm = reactive({
  username: '',
  email: '',
  password: '',
  role: ''
})

// Password form data
const passwordForm = reactive({
  newPassword: '',
  confirmPassword: ''
})

// User form validation rules
const userFormRules = {
  username: [
    { required: true, message: t('enter_username'), trigger: 'blur' }
  ],
  email: [
    { required: true, message: t('enter_email'), trigger: 'blur' },
    { type: 'email', message: t('enter_valid_email'), trigger: 'blur' }
  ],
  password: [
    { required: true, message: t('enter_password'), trigger: 'blur' },
    { min: 6, message: t('password_min_length'), trigger: 'blur' }
  ],
  role: [
    { required: true, message: t('select_role'), trigger: 'change' }
  ]
}

// Password form validation rules
const passwordFormRules = {
  newPassword: [
    { required: true, message: t('enter_new_password'), trigger: 'blur' },
    { min: 6, message: t('password_min_length'), trigger: 'blur' }
  ],
  confirmPassword: [
    { required: true, message: t('confirm_password_prompt'), trigger: 'blur' },
    {
      validator: (rule, value, callback) => {
        if (value !== passwordForm.newPassword) {
          callback(new Error(t('password_mismatch')))
        } else {
          callback()
        }
      },
      trigger: 'blur'
    }
  ]
}

// Load user list
const loadUserList = async () => {
  tableLoading.value = true
  try {
    const response = await api.get('/admin/users')
    userList.value = response.data.data || []
  } catch (error) {
    ElMessage.error(t('load_user_list_failed'))
  } finally {
    tableLoading.value = false
  }
}

// Open add user dialog
const openAddDialog = () => {
  isEditMode.value = false
  userDialogVisible.value = true
}

// Open edit user dialog
const openEditDialog = (user) => {
  isEditMode.value = true
  currentUser.value = user
  userForm.username = user.username
  userForm.email = user.email
  userForm.role = user.role
  userDialogVisible.value = true
}

// Reset user form
const resetUserForm = () => {
  userForm.username = ''
  userForm.email = ''
  userForm.password = ''
  userForm.role = ''
  currentUser.value = {}
  if (userFormRef.value) {
    userFormRef.value.resetFields()
  }
}

// Handle user form submit
const handleUserSubmit = async () => {
  if (!userFormRef.value) return
  
  try {
    await userFormRef.value.validate()
    userSubmitLoading.value = true
    
    if (isEditMode.value) {
      // Edit user
      await api.put(`/admin/users/${currentUser.value.id}`, {
        email: userForm.email,
        role: userForm.role
      })
      ElMessage.success(t('user_update_success'))
    } else {
      // Add user
      await api.post('/admin/users', {
        username: userForm.username,
        email: userForm.email,
        password: userForm.password,
        role: userForm.role
      })
      ElMessage.success(t('user_add_success'))
    }
    
    userDialogVisible.value = false
    loadUserList()
  } catch (error) {
    ElMessage.error(isEditMode.value ? t('update_user_failed') : t('add_user_failed'))
  } finally {
    userSubmitLoading.value = false
  }
}

// Delete user
const handleDeleteUser = async (user) => {
  try {
    await ElMessageBox.confirm(
      t('confirm_delete_user', { name: user.username }),
      t('delete_confirm'),
      {
        confirmButtonText: t('confirm'),
        cancelButtonText: t('cancel'),
        type: 'warning'
      }
    )
    
    await api.delete(`/admin/users/${user.id}`)
    ElMessage.success(t('user_delete_success'))
    loadUserList()
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error(t('delete_user_failed'))
    }
  }
}

// Open reset password dialog
const openResetPasswordDialog = (user) => {
  currentUser.value = user
  resetPasswordDialogVisible.value = true
}

// Open voice clone quota settings
const openQuotaDialog = async (user) => {
  quotaUser.value = user
  quotaDialogVisible.value = true
  await loadQuotaSettings(user.id)
}

const loadQuotaSettings = async (userID) => {
  quotaLoading.value = true
  try {
    const response = await api.get(`/admin/users/${userID}/voice-clone-quotas`)
    const quotas = response.data?.data?.quotas || []
    quotaRows.value = quotas.map((item) => ({
      ...item,
      max_count: Number.isFinite(Number(item.max_count)) ? Number(item.max_count) : -1,
      used_count: Number(item.used_count || 0),
      remaining_count: Number.isFinite(Number(item.remaining_count)) ? Number(item.remaining_count) : -1
    }))
    quotaOriginalMaxMap.value = quotaRows.value.reduce((acc, row) => {
      acc[row.tts_config_id] = Number(row.max_count)
      return acc
    }, {})
  } catch (error) {
    ElMessage.error(t('load_clone_quota_failed'))
    quotaRows.value = []
    quotaOriginalMaxMap.value = {}
  } finally {
    quotaLoading.value = false
  }
}

const saveQuotaSettings = async () => {
  if (!quotaUser.value?.id) return
  const normalizedItems = quotaRows.value.map((row) => ({
    tts_config_id: row.tts_config_id,
    max_count: Number(row.max_count)
  }))
  for (const item of normalizedItems) {
    if (!item.tts_config_id) {
      ElMessage.error(t('invalid_tts_config_id'))
      return
    }
    if (!Number.isInteger(item.max_count) || item.max_count < -1) {
      ElMessage.error(t('max_count_integer_error'))
      return
    }
  }

  const items = normalizedItems.filter((item) => quotaOriginalMaxMap.value[item.tts_config_id] !== item.max_count)
  if (items.length === 0) {
    ElMessage.info(t('quota_unchanged'))
    return
  }

  quotaSaving.value = true
  try {
    await api.put(`/admin/users/${quotaUser.value.id}/voice-clone-quotas`, { items })
    ElMessage.success(t('clone_quota_save_success'))
    await loadQuotaSettings(quotaUser.value.id)
  } catch (error) {
    ElMessage.error(t('save_clone_quota_failed'))
  } finally {
    quotaSaving.value = false
  }
}

const resetQuotaDialog = () => {
  quotaRows.value = []
  quotaUser.value = {}
  quotaOriginalMaxMap.value = {}
}

// Reset password form
const resetPasswordForm = () => {
  passwordForm.newPassword = ''
  passwordForm.confirmPassword = ''
  if (passwordFormRef.value) {
    passwordFormRef.value.resetFields()
  }
}

// Handle reset password
const handleResetPassword = async () => {
  if (!passwordFormRef.value) return
  
  try {
    await passwordFormRef.value.validate()
    
    await ElMessageBox.confirm(
      t('confirm_reset_password', { name: currentUser.value.username }),
      t('reset_password_confirm'),
      {
        confirmButtonText: t('confirm'),
        cancelButtonText: t('cancel'),
        type: 'warning'
      }
    )
    
    resetPasswordLoading.value = true
    
    await api.post(`/admin/users/${currentUser.value.id}/reset-password`, {
      new_password: passwordForm.newPassword
    })
    
    ElMessage.success(t('password_reset_success'))
    resetPasswordDialogVisible.value = false
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error(t('reset_password_failed'))
    }
  } finally {
    resetPasswordLoading.value = false
  }
}

// Format date/time
const formatDateTime = (dateString) => {
  if (!dateString) return '--'
  return new Date(dateString).toLocaleString('zh-CN')
}

// Load data on component mount
onMounted(() => {
  loadUserList()
})
</script>

<style scoped>
.config-page {
  padding: 20px;
  background: rgba(255, 255, 255, 0.88);
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.page-actions {
  display: flex;
  justify-content: flex-end;
  align-items: center;
  gap: 10px;
  flex-wrap: wrap;
  margin-bottom: 20px;
}

.quota-hint {
  color: #666;
  font-size: 13px;
}
</style>
