// manager/frontend/src/views/user/APITokens.vue
<template>
  <div class="api-tokens-page">
    <div class="page-actions">
      <router-link class="doc-link" to="/openapi-docs">{{ t('view_public_openapi') }}</router-link>
      <el-button type="primary" @click="openCreateDialog">
        <el-icon><Plus /></el-icon>
        {{ t('create_token') }}</el-button>
    </div>

    <el-alert type="info" :closable="false" show-icon>
      <template #title>{{ t('call_method_hint') }}</template>
    </el-alert>

    <el-card class="table-card" shadow="never">
      <el-table :data="tokens" v-loading="loading" :empty-text="t('no_tokens')">
        <el-table-column prop="name" :label="t('name')" min-width="180" />
        <el-table-column prop="token_prefix" :label="t('prefix_col')" min-width="140" />
        <el-table-column :label="t('status')" width="100">
          <template #default="{ row }">
            <el-tag :type="row.is_active ? 'success' : 'info'">{{ row.is_active ? t('available') : t('revoked') }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column :label="t('last_used_col')" min-width="170">
          <template #default="{ row }">{{ formatTime(row.last_used_at) }}</template>
        </el-table-column>
        <el-table-column :label="t('expire_time_col')" min-width="170">
          <template #default="{ row }">{{ formatTime(row.expires_at) }}</template>
        </el-table-column>
        <el-table-column :label="t('created_at')" min-width="170">
          <template #default="{ row }">{{ formatTime(row.created_at) }}</template>
        </el-table-column>
        <el-table-column :label="t('actions')" width="120" fixed="right">
          <template #default="{ row }">
            <el-button
              link
              type="danger"
              :disabled="!row.is_active"
              @click="handleRevoke(row)"
            >{{ t('revoke') }}</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="showCreate" :title="t('create_api_token_title')" width="480px">
      <el-form :model="form" :rules="rules" ref="formRef" label-width="100px">
        <el-form-item :label="t('token_name_label')" prop="name">
          <el-input v-model="form.name" maxlength="100" :placeholder="t('token_name_ph')" />
        </el-form-item>
        <el-form-item :label="t('valid_days_label')">
          <el-input-number v-model="form.expires_in_days" :min="0" :max="3650" />
          <div class="form-tip">{{ t('valid_forever_hint') }}</div>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="showCreate = false">{{ t('cancel') }}</el-button>
        <el-button type="primary" :loading="creating" @click="handleCreate">{{ t('create') }}</el-button>
      </template>
    </el-dialog>

    <el-dialog v-model="showPlainToken" :title="t('save_token_now')" width="640px">
      <el-alert type="warning" :closable="false" show-icon>
        {{ t('plain_token_hint') }}
      </el-alert>
      <el-input class="token-input" v-model="latestToken" type="textarea" :rows="3" readonly />
      <template #footer>
        <el-button @click="showPlainToken = false">{{ t('close') }}</el-button>
        <el-button type="primary" @click="copyToken">{{ t('copy_token') }}</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
import api from '../../utils/api'
import { useLocale } from '../../composables/useLocale'
const { t } = useLocale()

const loading = ref(false)
const creating = ref(false)
const tokens = ref([])
const showCreate = ref(false)
const showPlainToken = ref(false)
const latestToken = ref('')
const formRef = ref()

const form = reactive({
  name: '',
  expires_in_days: 0
})

const rules = {
  name: [{ required: true, message: t('enter_token_name'), trigger: 'blur' }]
}

const formatTime = (val) => {
  if (!val) return '-'
  return new Date(val).toLocaleString()
}

const loadTokens = async () => {
  loading.value = true
  try {
    const res = await api.get('/user/api-tokens')
    tokens.value = res.data.data || []
  } finally {
    loading.value = false
  }
}

const openCreateDialog = () => {
  form.name = ''
  form.expires_in_days = 0
  showCreate.value = true
}

const handleCreate = async () => {
  if (!formRef.value) return
  await formRef.value.validate()

  creating.value = true
  try {
    const res = await api.post('/user/api-tokens', form)
    latestToken.value = res.data?.data?.token || ''
    showCreate.value = false
    showPlainToken.value = true
    ElMessage.success(t('token_created'))
    await loadTokens()
  } finally {
    creating.value = false
  }
}

const handleRevoke = async (row) => {
  await ElMessageBox.confirm(t('confirm_revoke_token', { name: row.name }), t('hint'), {
    confirmButtonText: t('confirm'),
    cancelButtonText: t('cancel'),
    type: 'warning'
  })
  await api.delete(`/user/api-tokens/${row.id}`)
  ElMessage.success(t('token_revoked'))
  await loadTokens()
}

const copyToken = async () => {
  if (!latestToken.value) return
  await navigator.clipboard.writeText(latestToken.value)
  ElMessage.success(t('token_copied'))
}

onMounted(loadTokens)
</script>

<style scoped>
.api-tokens-page { padding: 8px; }
.page-actions {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 12px;
  flex-wrap: wrap;
  margin-bottom: 12px;
}
.doc-link {
  display: inline-block;
  color: var(--apple-primary);
  text-decoration: none;
  font-size: 13px;
}
.doc-link:hover { text-decoration: underline; }
.table-card { margin-top: 12px; }
.form-tip { color: #909399; font-size: 12px; margin-top: 6px; }
.token-input { margin-top: 12px; }
</style>

// manager/frontend/src/routes/_auth/_layout/user/api-tokens.tsx
import { useEffect, useState } from 'react'
import { createFileRoute, Link } from '@tanstack/react-router'
import { Copy, Plus } from 'lucide-react'
import { toast } from 'sonner'
import api from '@/utils/api'
import { useLocale } from '@/hooks/use-locale'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { ConfirmDialog } from '@/components/ui/confirm-dialog'
import { PageHeader } from '@/components/ui/page-header'

interface Token { id: number; name: string; token_prefix: string; is_active: boolean; last_used_at: string; expires_at: string; created_at: string }

const fmt = (v: string) => v ? new Date(v).toLocaleString() : '-'
const activeBadge = 'inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium status-success'
const inactiveBadge = 'inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium status-muted'

function ApiTokensPage() {
  const { t } = useLocale()
  const [tokens, setTokens] = useState<Token[]>([])
  const [loading, setLoading] = useState(false)
  const [page, setPage] = useState(1)
  const [total, setTotal] = useState(0)
  const pageSize = 20

  const [showCreate, setShowCreate] = useState(false)
  const [creating, setCreating] = useState(false)
  const [form, setForm] = useState({ name: '', expires_in_days: 0 })

  const [showToken, setShowToken] = useState(false)
  const [latestToken, setLatestToken] = useState('')
  const [revokeTarget, setRevokeTarget] = useState<Token | null>(null)
  const [revoking, setRevoking] = useState(false)

  const totalPages = Math.ceil(total / pageSize) || 1

  const load = async (p = page) => {
    setLoading(true)
    try {
      const res = await api.get('/user/api-tokens', { params: { page: p, page_size: pageSize } })
      setTokens(res.data.data || [])
      setTotal(res.data.total || 0)
    } catch { toast.error(t('load_failed')) }
    finally { setLoading(false) }
  }

  useEffect(() => { load(1) }, []) // eslint-disable-line react-hooks/exhaustive-deps

  const handleCreate = async () => {
    if (!form.name.trim()) { toast.error(t('enter_token_name')); return }
    setCreating(true)
    try {
      const res = await api.post('/user/api-tokens', form)
      setLatestToken(res.data?.data?.token || '')
      setShowCreate(false)
      setShowToken(true)
      toast.success(t('token_created'))
      await load(page)
    } catch { toast.error(t('create_failed')) }
    finally { setCreating(false) }
  }

  const handleRevoke = async () => {
    if (!revokeTarget) return
    setRevoking(true)
    try {
      await api.delete(`/user/api-tokens/${revokeTarget.id}`)
      toast.success(t('token_revoked'))
      setRevokeTarget(null)
      await load(page)
    } catch { toast.error(t('revoke_failed')) }
    finally { setRevoking(false) }
  }

  const copyToken = async () => {
    await navigator.clipboard.writeText(latestToken)
    toast.success(t('token_copied'))
  }

  return (
    <div className="grid gap-4 px-6 pb-8">
      <PageHeader title={t('api_token_management')} />
      <div className="flex items-center justify-between gap-2 flex-wrap">
        <Link to="/openapi-docs" className="text-sm text-[var(--color-primary)] hover:underline">{t('view_public_openapi')}</Link>
        <Button onClick={() => { setForm({ name: '', expires_in_days: 0 }); setShowCreate(true) }}>
          <Plus className="w-4 h-4 mr-1.5" />{t('create_token')}
        </Button>
      </div>
      <div className="rounded-lg border p-3 text-sm status-primary">
        {t('call_method_hint')}
      </div>
      <div className="rounded-xl border border-[var(--color-line)] overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>{t('name')}</TableHead>
              <TableHead>{t('prefix_col')}</TableHead>
              <TableHead className="w-24">{t('status')}</TableHead>
              <TableHead>{t('last_used_col')}</TableHead>
              <TableHead>{t('expire_time_col')}</TableHead>
              <TableHead>{t('created_at')}</TableHead>
              <TableHead className="w-20 text-center">{t('actions')}</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {loading ? (
              <TableRow><TableCell colSpan={7} className="py-10 text-center text-sm text-[var(--color-text-secondary)]">{t('loading')}</TableCell></TableRow>
            ) : tokens.length === 0 ? (
              <TableRow><TableCell colSpan={7} className="py-10 text-center text-sm text-[var(--color-text-secondary)]">{t('no_data')}</TableCell></TableRow>
            ) : tokens.map(row => (
              <TableRow key={row.id}>
                <TableCell className="font-medium">{row.name}</TableCell>
                <TableCell className="font-mono text-xs">{row.token_prefix}</TableCell>
                <TableCell><span className={row.is_active ? activeBadge : inactiveBadge}>{row.is_active ? t('available') : t('revoked')}</span></TableCell>
                <TableCell className="text-sm text-[var(--color-text-secondary)]">{fmt(row.last_used_at)}</TableCell>
                <TableCell className="text-sm text-[var(--color-text-secondary)]">{fmt(row.expires_at)}</TableCell>
                <TableCell className="text-sm text-[var(--color-text-secondary)]">{fmt(row.created_at)}</TableCell>
                <TableCell className="text-center">
                  <Button variant="ghost" size="sm" disabled={!row.is_active} className="text-destructive hover:text-destructive" onClick={() => row.is_active && setRevokeTarget(row)}>
                    {t('revoke')}
                  </Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
      {total > pageSize && (
        <div className="flex items-center justify-between text-sm text-[var(--color-text-secondary)]">
          <span>{total} {t('total_items')}</span>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" disabled={page <= 1} onClick={() => { setPage(p => p - 1); load(page - 1) }}>{t('prev')}</Button>
            <span>{page} / {totalPages}</span>
            <Button variant="outline" size="sm" disabled={page >= totalPages} onClick={() => { setPage(p => p + 1); load(page + 1) }}>{t('next')}</Button>
          </div>
        </div>
      )}

      <Dialog open={showCreate} onOpenChange={v => { if (!v) setShowCreate(false) }}>
        <DialogContent className="max-w-md">
          <DialogHeader><DialogTitle>{t('create_api_token_title')}</DialogTitle></DialogHeader>
          <div className="grid gap-4 py-2">
            <div className="grid gap-1.5">
              <label className="text-sm font-medium">{t('token_name_label')}</label>
              <Input value={form.name} onChange={e => setForm(f => ({ ...f, name: e.target.value }))} maxLength={100} placeholder={t('token_name_ph')} />
            </div>
            <div className="grid gap-1.5">
              <label className="text-sm font-medium">{t('valid_days_label')}</label>
              <Input type="number" value={form.expires_in_days} onChange={e => setForm(f => ({ ...f, expires_in_days: Number(e.target.value) }))} min={0} max={3650} />
              <p className="text-xs text-[var(--color-text-tertiary)]">{t('valid_forever_hint')}</p>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCreate(false)}>{t('cancel')}</Button>
            <Button disabled={creating} onClick={handleCreate}>{t('create')}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={showToken} onOpenChange={v => { if (!v) setShowToken(false) }}>
        <DialogContent className="max-w-xl">
          <DialogHeader><DialogTitle>{t('save_token_now')}</DialogTitle></DialogHeader>
          <div className="grid gap-3 py-2">
            <div className="rounded-lg border p-3 text-sm status-warning">
              {t('plain_token_hint')}
            </div>
            <textarea value={latestToken} readOnly rows={3} className="dark:bg-input/30 border-input rounded-md border bg-transparent px-2.5 py-2 text-sm font-mono w-full resize-none focus-visible:outline-none" />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowToken(false)}>{t('close')}</Button>
            <Button onClick={copyToken}><Copy className="w-4 h-4 mr-1.5" />{t('copy_token')}</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <ConfirmDialog open={!!revokeTarget} onClose={() => setRevokeTarget(null)} onConfirm={handleRevoke} isLoading={revoking} title={t('hint')} description={t('confirm_revoke_token', { name: revokeTarget?.name || '' })} />
    </div>
  )
}

export const Route = createFileRoute('/_auth/_layout/user/api-tokens')({
  component: ApiTokensPage,
})
